[[welcome]]
== ¡Bienvenidos estudiantes y profesores!

:nofooter:

¡Bienvenidos a EarSketch!

*Maestros*: Ve a nuestra https://earsketch.gatech.edu/teachermaterials/EarSketch_Alignment_Guide.pdf[nueva guía curricular^], y visita nuestra  https://www.teachers.earsketch.org[Página web de EarSketch para profesores^] para recursos adicionales.

*Estudiantes*: Continúa para aprender más sobre EarSketch

Aquí aprenderás ciencia de cómputos y tecnología musical a la misma vez. Usarás Python o JavaScript para crear tu propia música.

Los músicos y programadores escriben código computacional para crear nuevos sonidos, efectos y canciones.

[role="curriculum-mp4"]
[[video0]]
video::../landing/media/homepagevid.a1cf3d01.mp4[poster=../landing/img/homepagevid-poster.8993a985.png]

Aprender a programar es una habilidad que te servirá en una variedad de carreras profesionales.

¡Tal vez te conviertas en un productor legendario de música o el ingeniero de grabación más prestigioso de la industria! Te deseamos buena suerte en tu viaje con EarSketch.

Haz clic en la flecha derecha encima de este texto para empezar.

Maestros, ¡consigue aceso a materiales gratuitos de enseñanza y a la comunidad https://www.teachers.earsketch.org/[aquí^]!