[[customizeyourfirstsong]]
== تخصيص أغنيتك الأولى
:nofooter:

في هذا الفصل ستتعلم كيفية تغيير إيقاع أغنيتك وإضافة التعليقات إلى الكود الخاص بك وتحميل الأصوات الخاصة بك لتحسين رسالة أغنيتك.

[[settempo]]
=== الدالة
 ()setTempo 

[role="curriculum-python"]
--
لقد لاحظت الآن أنه عند إنشاء سكريبت، هناك عناصر موجودة مسبقًا يجب عليك الاحتفاظ بها تمامًا حتى يعمل الكود الخاصة بك:

. هناك ملاحظات التي تبدأ بـ `#` باللون الرمادي: سوف نغطي شرح ذلك في القسم التالي.
. السطر 
from Earsketch import*
الذي يضيف دوال Earsketch  مثل 
  ()fitMedia  
للمشروع
. الدالة `setTempo(120)` التي سنشرحها بالتفصيل أدناه
--

[role="curriculum-javascript"]
--
لقد لاحظت الآن أنه عند إنشاء سكريبت، هناك عناصر موجودة مسبقًا يجب عليك الاحتفاظ بها تمامًا حتى يعمل الكود الخاصة بك:

. هناك ملاحظات التي تبدأ بـ`//` باللون الرمادي: سوف نغطي شرح ذلك في القسم التالي.
. الدالة `setTempo(120)` التي سنشرحها بالتفصيل أدناه.
--

ستحدد دالة ()setTempo سرعة أغنيتك. tempo (إيقاع بالعربية) في الموسيقى الغربية. هو عدد النبضات (beats) في الدقيقة (bpm). في EarSketch ، يتم تعيين الإيقاع الافتراضي (أي القيمة الأولية لtempo) إلى 120 جزء من المليون، وهو ما يقابل للمشي السريع في حياتنا. لتغيير الايقاع tempo، فقط قم بتغيير الرقم بين قوسين لوظيفة `setTempo()`. كلما ارتفع الايقاع tempo كلما زادت سرعة موسيقاك. يمكنك تحديد الإيقاع بين    45 bpm  و  220 bpm.

.تدريب
****
. إنشاء سكريبت جديد. 
. ضع الأصوات على مسارين مختلفين،
. قم بتعديل الإيقاع الخاص بك والاستماع إلى الأغنية،
. شغل أغنيتك في 3 ايقاعات مختلفة لصديق. ثم اطلب منهم ترتيب الايقاعات من الأبطأ إلى الأسرع.
****

القالب الموسيقي هو فئة من الانتاجات الفنية مثل (الموسيقى) والتي تتشابه بصفاتها وشكلها او محتواها. قوالب مختلفة لها ايقاعات مختلفة على سبيل المثال:

[cols="^3*"]
|===
|القالب الفني|BPM|مثال

|Hip Hop

|85-95

|Coolio - Gangsta Paradise (feat. L.V.)

|البوب Pop
|110-130

|Lizzo - Juice
 
|تكنو Techno
|120-125

|Boris Brejcha - Schleierwolken
|إلكترو Electro
|100-130

|Apashe - Behind My Eyes (feat. LIA)

|هاوس House
|115-130

|DJ Breezy - Kimpinstik (feat. Dahlin Gage & Medikal)
|دب ستيب & تراب Dubstep and Trap

|140-150

|Jessica Audiffred & Walshy Fire - Stupid Love (feat. Nia V)
|درام & باس Drum & Bass
|160-180

|Mollie Collins - Lost & Found
|===

.تدريب
****
. اختر فنانًا واحداً تحبه حقًا و اكتشف نوع القالب الفني الذي ينتمي إليه.
. ابحث عن هذا النوع من القالب الفني (على ساوندكلود أو ما شابه ذلك) واستمع إلى بضعة من الأغاني هذا النوع.
. اصغي لأوجه التشابه بين الأغاني.
. بإمكانك أيضاً أن تبحث عن نوع القالب في ويكيبيديا للحصول على مزيد من المعلومات عنه.
****
 
لاحظ أن مقطع صوت واحد سيبدو في بعض الأحيان مختلفا جدا عند معاينته وعند تشغيله في أغنيتك. قد يكون ذلك لأن سرعة ايقاع مقطع الصوت مختلفة عن سرعة ايقاع أغنيتك temp. لمعرفة الإيقاع الدقيق للمقطع، مرر الماوس (الفأره) فوق اسم المقطع في متصفح (Browser) الصوت. وعندها يمكنك تعديل إيقاع أغنيتك وفقًا لذلك أو اختيار مقطع صوت يتناسب بشكل أفضل مع إيقاع أغنيتك.


[[comments]]
=== أضف الملاحظات إلى تعليماتك البرمجية (الكود) 

[role="curriculum-python"]
*الملاحظات في Python* هي أسطر من التعليمات البرمجية التي لا يتم تنفيذها بواسطة الكمبيوتر. وهي تستخدم فقط من قبل الانسان لجعل التعليمات البرمجية (الكود) أسهل فهمها، أو للمساعدة في تنظيم التعليمات البرمجية أو لعمل ملاحظات للاستخدام في المستقبل. في Python، يشار إلى الملاحظات بواسطة سطر يبدأ بالرمز `#` 

[role="curriculum-javascript"]
*الملاحظات في JavaScript* هي أسطر من التعليمات البرمجية التي لا يتم تنفيذها بواسطة الكمبيوتر. وهي تستخدم فقط من قبل الانسان لجعل التعليمات البرمجية (الكود) أسهل فهمها، أو للمساعدة في تنظيم التعليمات البرمجية أو لعمل ملاحظات للاستخدام في المستقبل. في JavaScript، يشار إلى التعليقات بواسطة سطر يبدأ بخطين أمامين، `//`.

لاحظ أن السطر الأول من كل سكريبت هو ملاحظات التي تصف النص البرمجي (الكود). لكل سريبت جديد، سوف تحتاج إلى ملء هذه المعلومات. هذا يجعل من الأسهل على المبرمجين الآخرين فهم ما هو الكود الخاص بك.

.تدريب
****
على السكريبت الحالي الخاص بك، قم بتعبئة المعلومات التالية في الملاحظات في بداية الكود الخاص بك:

. اسم السكريبت: اسم أغنيتك،
. المؤلف : اسمك،
. الوصف: هنا اكتب وصفاً مختصراً لمشروعك
****

يمكنك أيضًا استخدام الملاحظات لوصف ما تفعله الأقسام المختلفة من الكود. فيما يلي مثال: يمكنك لصق الكود وتشغيله. لاحظ كيف تصف الملاحظات الفروع المختلفة:

[role="curriculum-python"]
[source,python]
----
# Comments: Using comments to describe what the code does

# Setup
from earsketch import *
setTempo(130)

# Music
# Leads
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9)
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5)
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9)

# Beat
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9)
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3)
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5)
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9)

# Bass and noise
fitMedia(ELECTRO_ANALOGUE_BASS_008, 5, 1, 9)
fitMedia(TECHNO_WHITENOISESFX_001, 6, 7, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Comments: Using comments to describe what the code does

// Setup
setTempo(130);

// Music
// Leads
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9);
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5);
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9);

// Beat
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9);
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3);
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5);
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9);

// Bass and noise
fitMedia(ELECTRO_ANALOGUE_BASS_008, 5, 1, 9);
fitMedia(TECHNO_WHITENOISESFX_001, 6, 7, 9);
----


[[uploadingsounds]]
=== تحميل الأصوات الخاصة بك


يمكنك تحميل الصوت الخاص بك من خلال متصفح الصوت. افتح متصفح الصوت الخاص بك وانقر على زر "إضافة صوت" أسفل الفلاتر (إذا لم يظهر الزر، تأكد من أنك مسجل الدخول)-- ستفتح نافذة، لنستكشف الخيارات الثلاثة الأولى:

. *تحميل صوت جديد* يسمح لك باختيار ملفات صوتية (.mp3, .aiff, وما إلى ذلك) من جهاز الكمبيوتر الخاص بك. يمكنك تعديل اسم الملف إذا لزم الأمر ("constant value(required)")، وانقر على "UPLOAD".
. *تسجيل سريع* يتيح لك تسجيل مقطوعات قصيرة مباشرة في مكتبة EarSketch. شاهد الفيديو أدناه لمزيد من المعلومات.
. *Freesound* تسمح لك باستيراد الأصوات مباشرة من Freesound.org، قاعدة بيانات صوتية مفتوحة المصدر. في شريط البحث، يمكنك البحث عن نوع من الصوت المطلوب (على سبيل المثال: أغاني الطيور، الأمطار، الشارع المزدحم..). تحت "النتائج"، ستظهر قائمة بالأصوات. يمكنك معاينة الأصوات بالنقر على زر التشغيل، وإذا أعجبتك، انقر زر التبديل أمام اسم الملف ثم انقر فوق "UPLOAD" في الأسفل تماما.

للعثور على الصوت الذي قمت برفعه أو تسجيله للتو، اكتب اسمه في شريط البحث في متصفح الصوت.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.تدريب
****
الموسيقى، والفن بشكل عام، غالباً ما تكون طريقة لنقل رسالة. ويمكن أن يكون إما من خلال كلمات الأغنية، و/أو من خلال نوع الأغنية. نود أن نصنع أغنية قصيرة تعبر عن شيء ما. يمكن أن يكون الشعور الذي ترغب'في مشاركته، أو قصة.

. فكر في ما ترغب'في التعبير عنه 
. ثم 1- إما أن تكتب بعض كلمات الأغنية وتسجل نفسك تغنيها أو تقرأها أو 2- تسجيل أو تحميل بعض الأصوات الموسيقية المرتبطة برسالتك
. أضف هذه التسجيلات إلى أغنيتك باستخدام دالة fitMedia()
. ثم أضف بعض المقاطع الإضافية من EarSketch باستخدام دالة fitMedia()
. اعرض اغنيتك لصديق
. يمكنك مناقشة أغنيتك والأشياء التي كنت تحاول التعبير عنها
****

////
OPTIONAL
////

* العمليات * ، أو المهام ، هي برامج تعمل على جهاز الحاسوب الخاص بك. تقوم وحدة المعالجة' المركزية للحاسوب ، أو * وحدة المعالجة المركزية * بتنفيذها. 

تحتفظ ذاكرة الحاسوب' * * بالبيانات وتعليمات المعالجة لاستخدام وحدة المعالجة المركزية. الذاكرة ، وتسمى أيضًا التخزين الأساسي أو ذاكرة الوصول العشوائي (ذاكرة الوصول العشوائي) ، تخزن بياناتها مؤقتًا. يتم تخزين المعلومات الخاصة بالعمليات التي يتم تشغيلها بنشاط فقط في ذاكرة الوصول العشوائي RAM. يتيح ذلك الوصول السريع إلى الإرشادات والبيانات الخاصة بوحدة المعالجة المركزية CPU.

هناك فرق بين الذاكرة (أو التخزين قصير المدى) والتخزين طويل المدى. يشار إلى التخزين طويل المدى ، مثل محرك الأقراص الثابتة أو السحابة(cloud) ، على أنه تخزين ثانوي. * التخزين الثانوي * يحتوي على كميات كبيرة من البيانات لفترات طويلة من الوقت ، حتى بعد إيقاف تشغيل الحاسوب. لا تتفاعل وحدة المعالجة المركزية-CPU-بشكل مباشر مع وحدات التخزين الثانوية. عندما تنفذ وحدة المعالجة المركزية CPU عملية ما ، يجب أولاً وضع البيانات من التخزين الثانوي في الذاكرة حتى تتمكن وحدة المعالجة المركزيةCPU من الوصول إليها بسرعة.

في بعض الأحيان ، تأتي البيانات الموجودة في الذاكرة لاستخدام وحدة المعالجة المركزيةCPU من جهاز إدخال بدلاً من التخزين الثانوي. * المدخلات * هي الإشارات أو البيانات التي يتلقاها الكمبيوتر ، مثل الصوت من الميكروفون. وبالمثل ، فإن مخرجات * * هي الإشارات أو البيانات المرسلة منه ، مثل الصوت عبر مكبر الصوت. الإدخال / الإخراج ، أو I / O ، هو كيفية تواصل الحاسوب مع العالم الخارجي ، بما في ذلك البشر!

دعونا 'نفحص تسجيل الصوت في EarSketch كمثال للعملية. أولاً ، نقوم بتسجيل البيانات في الحاسوب باستخدام جهاز الإدخال ، الميكروفون. تقوم وحدة المعالجة المركزيةCPU بتخزين تلك البيانات الصوتية في ذاكرتها. إذا قمت بالضغط على زر التشغيل لسماع التسجيل الخاص بك ، فإن وحدة المعالجة المركزيةCPU تصل إلى البيانات وترسلها إلى أحد المخرجات أو مكبرات الصوت أو سماعات الرأس. عندما تضغط على زر التحميل ، تقوم وحدة المعالجة المركزيةCPU بتشغيل عملية تقوم بتحويل البيانات الصوتية إلى تنسيق ملف صوتي قياسي (ملف WAV أو .wav) وترسله إلى خادم EarSketch. الخادم (The server) هو نظام خارجي يوفر خدمات لجميع مستخدمي EarSketch ، بما في ذلك جهاز الكمبيوتر الخاص بك. يحفظ خادم EarSketch ملف الصوت من الذاكرة إلى التخزين الثانوي للخوادم 'بحيث يمكنك الوصول إليه في المستقبل.

شاهد الشرح بالفيديو التالي:

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== استخدم حقوق النشر بحكمة

* حقوق الطبع والنشر * هي جزء من القانون يغطي * الملكية الفكرية * ، أو ملكية العمل الإبداعي ، مثل الموسيقى. عند استخدام عينات (مقطوعات صغيرة من الموسيقى) أو إعادة مزج الموسيقى الموجودة ، فأنت بحاجة إلى منح الفضل للمؤلفين ، ويمكنك القيام بذلك في تعليقات التعليمات البرمجية الخاصة بك. قبل استخدام أصوات الموسيقيين الآخرين ومشاركة الموسيقى الخاصة بك ، تعرف على المزيد حول حقوق النشر!

* حقوق الطبع والنشر * هي جزء من القانون يغطي * الملكية الفكرية * ، أو ملكية العمل الإبداعي ، مثل الموسيقى. 

عندما تنشئ شيئًا أصليًا وكبيرًا بدرجة كافية ، تحصل على حقوق الطبع والنشر تلقائيًا! في الولايات المتحدة ، هذا يعني أنه يمكنك: عمل نسخ وإجراء تعديلات ومشاركة ما تقوم بإنشائه.

هناك نوعان من حقوق الطبع والنشر للأغنية: حقوق الأغنية (للكاتب أو الملحن) وحقوق التسجيل الصوتي (غالبًا بواسطة شركة التسجيل). تذهب عائدات العروض العامة إلى كاتب الأغاني وتذهب معظم الارباح من مبيعات التسجيلات إلى شركة التسجيلات. 

يعد * انتهاك حقوق الطبع والنشر * انتهاكًا لحقوق الطبع والنشر ، مثل تنزيل الموسيقى بشكل غير قانوني. في الولايات المتحدة ، يسمح * الاستخدام العادل * باستخدام المحتوى المحمي بحقوق الطبع والنشر في ظل ظروف معينة ، مثل الأغراض التعليمية أو الحرجة ، وإعادة استخدام كميات صغيرة فقط من العمل. يتم تحديد الاستخدام العادل لكل حالة من قبل الحكم على أساس كل حالة على حدة.

إلى جانب الاستخدام العادل ، هناك طريقة لاستخدام الموسيقى ومشاركتها بشكل مفتوح. يجب أن تساعدنا حقوق الطبع والنشر في صنع ومشاركة المزيد من الفن ، وليس أقل. يعمل EarSketch لأن الفنانين شاركوا أعمالهم معك من خلال * امثلة لعينات * (جزء صغير من التسجيل الصوتي) في مكتبة الأصوات. شارك هؤلاء الفنانون عيناتهم بموجب ترخيص * المشاع الإبداعي * ، والذي يمنح الإذن للآخرين لاستخدام أعمالهم. في EarSketch ، لديك إذن وصول مفتوح إلى هذه العينات ، وكل الموسيقى التي تنشئها في EarSketch قابلة للمشاركة ، على الرغم من أنه لا يمكنك بيعها. تعد مشاركة الموسيقى الخاصة بك أو السماح للطلاب الآخرين بإعادة مزج التعليمات البرمجية الخاصة بك طريقة لدفع هذا الأمر إلى الأمام والمساعدة في وضع فن جديد في العالم.

تتيح تراخيص المشاع الإبداعي <strong> (أو CC) للمبدعين تحديد الحقوق التي يحتفظون بها والحقوق التي يتنازلون عنها. فيما يلي الأجزاء الممكنة من رخصة المشاع الإبداعي: ​​"يمكنك استخدام هذا العمل كيفما تشاء ، باستثناء ​...

* ​...عليك أن تضع اسمي عليها " - Attribution (BY) - بدون مشتقات (ND)
* ...&8203لا يمكنك تغييره على الإطلاق." - No Derivatives (ND)
- بدون مشتقات (ND)
* ​...لا يمكنك كسب المال منه " Non-Commercial (NC) - بدون مشتقات (ND)
* ​...عليك مشاركة أي شيء جديد تصنعه بموجب نفس الترخيص " - شارك على حد سواء (SA)

لتحديد ترخيص المشاع الإبداعي ، كل ما عليك فعله هو اختيار نوع ووضعه في عملك. في EarSketch ، عندما تشارك نصًا ، سيُطلب منك تحديد ترخيص لأغنيتك. 



[[chapter2summary]]
=== ملخص الفصل 2

[role="curriculum-python"]
* * الإيقاع * هو السرعة التي يتم بها تشغيل مقطوعة موسيقية ، محددة بعدد الدقات في الدقيقة (دقة في الدقيقة). الإيقاع مرتبط بالنوع الموسيقي.
* يتم تنظيم المقاطع الموجودة في مكتبة اصوات EarSketch في مجلدات من الأصوات ذات الصلة. لمعرفة الإيقاع الدقيق للمقطع ، مرر مؤشر الماوس فوق الاسم في متصفح الصوت.
* التعليقات هي أسطر من التعليمات البرمجية لا يتم تنفيذها بواسطة الحاسوب. ومع ذلك ، فهي مفيدة لادخال الملاحظات داخل البرنامج النصي.
* `من مستورد earsketch*` يضيف EarSketch API إلى مشروعك. يجب أن يتم تضمينه في الجزء العلوي من كل نص.
* `setTempo()`يتيح لك تحديد إيقاع أغنيتك. يجب تضمينه في كل برنامج نصي من EarSketch.
* يمكنك تحميل الأصوات الخاصة بك إلى EarSketch من خلال مكتبة الاصوات. فقط انقر فوق "إضافة صوت".
* <strong>المعالجة/0> هي مهمة تعمل على الحاسوب. تتم المعالجة بواسطة جهاز الحاسوب' * وحدة المعالجة المركزية CPU * ، وهو المسؤول عن تنفيذ تعليمات البرنامج.
* * الذاكرة * (المعروفة أيضًا باسم ذاكرة الوصول العشوائي أو التخزين الأساسي) تحتفظ بالبيانات وتعليمات المعالجة مؤقتًا لاستخدام وحدة المعالجة المركزية.
* * التخزين الثانوي * يشير إلى التخزين طويل المدى للبيانات ، غالبًا بكميات كبيرة. يجب وضع البيانات من التخزين الثانوي في الذاكرة قبل أن تتمكن وحدة المعالجة المركزية CPU من الوصول إليها.
* * حقوق الطبع والنشر * هي جزء من القانون يغطي ملكية العمل الإبداعي ، مثل الموسيقى. إنه مهم للموسيقيين لأنه يحدد كيف يمكن استخدام عمل شخص آخر 'ومشاركته.
* إذا أنشأت عملاً موسيقيًا ملموسًا وجديدًا ، فلديك حقوق نشر تلقائية. بمعنى آخر ، لديك حقوق على العمل الذي قمت بإنشائه.
* * ترخيص * يمنح للآخرين الإذن باستخدام مقطوعة موسيقية. في بعض الأحيان ، يتم الاحتفاظ بحقوق معينة للعمل مع تراخيص * المشاع الإبداعي *. يسمح لك EarSketch بإضافة تراخيص Creative Commons-المشاع الإبداعي إلى الموسيقى الخاصة بك عبر نافذة المشاركة.

[role="curriculum-javascript"]
* * الإيقاع * هو السرعة التي يتم بها تشغيل مقطوعة موسيقية ، محددة بعدد الدقات في الدقيقة (دقة في الدقيقة). الإيقاع مرتبط بالنوع الموسيقي.
* يتم تنظيم المقاطع الموجودة في مكتبة EarSketch Sounds في مجلدات من الأصوات ذات الصلة. لمعرفة الإيقاع الدقيق للمقطع ، مرر مؤشر الماوس فوق الاسم في متصفح الصوت.
* التعليقات هي أسطر من التعليمات البرمجية لا يتم تنفيذها بواسطة الحاسوب. ومع ذلك ، فهي مفيدة لتدوين الملاحظات داخل البرنامج النصي.
* `setTempo();`يتيح لك تحديد إيقاع أغنيتك. يجب تضمينه في كل برنامج نصي من EarSketch.
* يمكنك تحميل الأصوات الخاصة بك إلى EarSketch من خلال متصفح الصوت. فقط انقر فوق "إضافة صوت".
* *عملية  * هي مهمة تعمل على الكمبيوتر. تتم المعالجة بواسطة وحدة المعالجة المركزية CPU ، وهي المسؤولة عن تنفيذ تعليمات البرنامج.
* * الذاكرة * (المعروفة أيضًا باسم ذاكرة الوصول العشوائي أو التخزين الأساسي RAM) تحتفظ بالبيانات وتعليمات المعالجة مؤقتًا لاستخدام وحدة المعالجة المركزية.
* * التخزين الثانوي * يشير إلى التخزين طويل المدى للبيانات ، غالبًا بكميات كبيرة. يجب وضع البيانات من التخزين الثانوي في الذاكرة قبل أن تتمكن وحدة المعالجة المركزية من الوصول إليها.
* * حقوق الطبع والنشر * هي جزء من القانون يغطي ملكية العمل الإبداعي ، مثل الموسيقى. إنه مهم للموسيقيين لأنه يحدد كيف يمكن استخدام ومشاركة عمل الأشخاص الآخرين.
* إذا أنشأت عملاً موسيقيًا ملموسًا وجديدًا ، فلديك حقوق نشر تلقائية. بمعنى آخر، لديك حقوق على العمل الذي قمت بإنشائه.
* *الترخيص* قطعة من الموسيقى تعطي الآخرين الإذن لاستخدامها. في بعض الأحيان ، يتم الاحتفاظ بحقوق معينة للعمل مع تراخيص  *Creative Commons*. يسمح لك EarSketch بإضافة تراخيص اCreative Commons إلى الموسيقى الخاصة بك عبر نافذة المشاركة.




[[chapter-questions]]
=== الأسئلة

[question]
--
ماذا تسمح لك `()setTempo` بفعله في EarSketch؟
[answers]
* غيّر وتيرة الأغنية
* أضف صوت إلى المسار
* اصنع قرع طبلة
* غيّر نوعية الصوت داخل المشروع
--

[question]
--
ما هي الوحدة للتمبو؟
[answers]
* بيتات لكل دقيقة (BPM)
* قياس
* ديسيبلس(دبي)
* ثوانٍ
--

[question]
--
ما الهدف من استخدام الملاحظات؟
[answers]
* كل ما ورد اعلاه
* تنظيم التعليمات البرمجية/الكود الخاصة بك
* كتابة وصف للسكريبت في بداية السكريبت الخاص بك
* جعل التعليمات البرمجية (الكود) الخاصة بك سهلة القراءة للمبرمجين الآخرين
--

[question]
--
أي من التصريحات التالية صحيحة؟
[answers]
* القرص الصلب هو مثال للتخزين الثانوي
* يتم حفظ بيانات الصوت في وحدة المعالجة المركزية للكمبيوتر
* تحتوي وحدة المعالجة المركزية على بيانات تعليمية للبرامج
* بيانات المخازن الثانوية لفترات قصيرة
--

[question]
--
كيف تحصل على حقوق التأليف والنشر؟
[answers]
* عن طريق إنشاء ونشر أي عمل جديد
* عن طريق شراء براءة اختراع
* بالانضمام إلى منظمة سرية
* عن طريق اختيار ترخيص لعملك
--

[question]
--
ما هو المشاع الإبداعي (Creative Commons)؟
[answers]
* رخصة لمشاركة عملك علناً بموجب قيود معينة
* عملية التأليف
* الحق في مقاضاة أي شخص يستخدم موسيقاك
* رخصة تسمح لك بجمع الإتاوات
--
