[[SubmittotheYourVoiceisPowerCompetition]]
== Your Voice is Power: Submit Your Remix

[[SubmitYourRemix]]

=== Submit Your Remix
:nofooter:

[.youtube-container]
video::r1TE0phH_oA[youtube]

Are you ready? The time is now to create your remix. For your final challenge,
you will code a song in EarSketch remixing stems from Pharrell’s song Entrepreneur that uses
your “voice” (or includes a message). Think about the call to action and how you can build on your EarSketch knowledge to use code to express your voice.  Below you will find resources to help you continue to work on your submission.  When you have completed your code, debug (see directions below) and then submit to the competition.  Pharrell is so excited to see what you can produce.

==== EarSketch Skills

// [options="header"]
|======================================
| *Topic* | *Description* | *Resources*
| Custom Functions    |Write your own functions to define sections of your song
|<<musical-form-and-custom-functions#,Musical Form and Custom Functions>>
 <<musical-form-and-custom-functions#customfunctions,Custom Functions Video>>
|   Uploading Sounds     |If you want to add your “actual voice to the song by singing or uploading lyrics.  You may want to add some community sounds or other sounds that are not in the EarSketch library.   By choosing uploading sounds from the sound browser, you  will have the options to Upload a New Sound, do a quick record or find a clip on Freesound.

|<<recording-and-uploading-sounds#,Uploading Sounds>>

link:https://earsketch.gatech.edu/yvip/Uploading-Sounds.pdf[Tutorials^]|setEffect() |You will learn how to adjust track volume, code for fades, create echos, distort their sounds, change the pitch,  and create a reverb in their sounds.|<<effects-in-earsketch#,Effects in EarSketch>>

<<every-effect-explained-in-detail#,Every Effect in Detail>>
|  Looping  |You  will learn how to code more efficiently and add repetition to your music.|:<<looping#,Looping Tutorials>>
|======================================

==== Debugging
Once you have finished your code, you need to go through a final check for errors called the *debugging process*

*Follow the instructions below to debug your code:*

1. *Run your code*
2. *Check the console - are there any errors?*
     a. If there are no errors, move on to  Part 2 in the song submission process.
     b. If you have an error in your code, continue to step 3 in the debugging process
3. *Read the console for clues* (such as line number or type of error).
4. *Locate the error in your code:* If the console provided a line number, take a look at that line and the previous line in your code. Check any arguments carefully. You can also comment out the lines of code one at a time to identify where a possible error could be.
5.* Print debugging* can also be used to locate an error. Insert print statements throughout your code to obtain the value of variables and check your logic.
6. *Squash the bug:* Check for syntax errors, like unclosed parentheses, quotations, or brackets. Edit the ode, and run it to verify its correctness.
7. *Ask for help:* If you find you have spent too much time on a bug, then ask someone for help! A fresh pair of eyes can do wonders for spotting mistakes.




==== Check Your Song & Submit:

*Directions*: Check to make sure that your song meets all competition criteria before submitting.

****
* *Make Beats*
** Your song is a minimum of 30 seconds (16 measures)  and a maximum of 3 minutes.
** Your song has at least 5 unique music tracks.
** Your song includes one sound clip (stem) from Pharell’s song “Entrepreneur.
** Play your song - Does the song sound like a remix of Entrepreneur?  Have you changed the style, tempo, order of beats? Have you mixed other sounds with Entrepreneur stems?
** Check your audio clips. Do you have any sounds that are not from the EarSketch library or recorded by you in your code?   Did you attribute the source in the comments? Any copyrighted sound clips must be removed from your song. Information on copyright can be found here.

* *Learn Code*
** Your song includes the EarSketch API function `fitMedia()` to insert sound clips.
** Your song uses variables.
** Your song includes Custom/User-defined functions to define song sections.
** Your song uses comments to describe code and document the message in the song.
** Share your code with a peer (if possible).  Do they understand the flow of the code?  Are there places you can add additional comments?  If you can’t share your code, do one last read through to see if you should add.

* *Promote Equity*
** Your song includes a message or call to action that promotes equity.
** Your song demonstrates student awareness or analysis of racial injustice.
** Are you able to write a short reflection about your song in the submission form?  Do you have any documents that you want to upload with your song?
****

*It's time to submit*.  Click on the 3 white lines next to your *Your Voice is Power* script.  Scroll down and find "Submit to Competition". It will take you to the competition submission form.  Answer the questions on the form, include a short reflection on your work, and click the submit button.  The first submission deadline is *March 12th, 2021*

Good Luck!
