[[ch_17]]
== Console Input and Conditionals
:nofooter:

This chapter covers methods for adding interactivity and decision making to programs.

[[consoleinput]]
=== Console Input

Printing to the console allows information to be displayed to the user. *Console Input* is text-based data taken from the keyboard, giving a program access to information from the user. Together, printing and console input can be used to allow the user to interact with a program.

In EarSketch, the `readInput()` function is used for console input. This opens a dialog box asking for input and returns the string typed into the dialog box. It has one parameter, a string that is displayed in the dialog box as a prompt. Try interacting with the following example. Remember to check the console!

[role="curriculum-python"]
[source,python]
----
# Simple Input: Interacting with a prompt

# Setup
from earsketch import *
setTempo(120)

# Body
print("Hello.")
n = readInput("What is your name? ")
print("Hi " + n + "! It is nice to meet you.")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Simple Input: Interacting with a prompt

setTempo(120);

// Body
println("Hello.");
var n = readInput("What is your name? ");
println("Hi " + n + "! It is nice to meet you.");
----

[role="curriculum-python"]
.DATA TYPE CONVERSION
****
Sometimes we want to take a string input from the user and convert it to another data type so it can be used for a different purpose. Functions for converting between data types in Python are listed below.

* `str()` - convert any value into a string
* `int()` - convert a string containing digits into an integer
* `float()` - convert a string containing digits with a decimal point into a float
****

[role="curriculum-javascript"]
.DATA TYPE CONVERSION
****
Sometimes we want to take a string input from the user and convert it to another data type so it can be used for a different application. Functions for converting between data types in JavaScript are listed below.

* `String()` - convert any value into a string
* `Number()` - convert a string into a number
****

In the example below, console input is used to determine some characteristics of the song. First, the user is prompted to select a tempo from a recommended range. The returned string is converted to an integer and used as the `setTempo()` argument. The user is also prompted to specify a clip number. The number is concatenated with `DUBSTEP_BASS_WOBBLE_0` to form a complete clip name.

[role="curriculum-python"]
[source,python]
----
# Musical Input: Creating a dubstep song with user-specified parameters

# Setup
from earsketch import *
t = readInput("Set a valid tempo for this song (120 - 160): ")
print("You set a tempo of " + t + "bpm")
tempo = int(t)
setTempo(tempo)

# Music
kick = OS_KICK02
clap = OS_CLAP04
beatString1 = "0+++++--------00"
beatString2 = "0++0++0++++++---"
clipNum = readInput("Select a clip number between 10 and 46: ")
dubStepClip = "DUBSTEP_BASS_WOBBLE_0"
finalClip = dubStepClip + clipNum

# user selected dubstep wobbles
fitMedia(finalClip, 1, 1, 5)
# kick
for measure in range(1, 5, 2):
    makeBeat(kick, 2, measure, (beatString1 + beatString2))
# clap
for measure in range(2, 6):
    fitMedia(clap, 3, measure - 0.5, measure - 0.25)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Musical Input: Creating a dubstep song with user-specified parameters

// Setup
var t = readInput("Set a valid tempo for this song (120 - 160): ");
println("You set a tempo of " + t + "bpm");
var tempo = Number(t);
setTempo(tempo);

// Music
var kick = OS_KICK02;
var clap = OS_CLAP04;
var beatString1 = "0+++++--------00";
var beatString2 = "0++0++0++++++---";
var clipNum = readInput("Select a clip number between 10 and 46: ");
var dubStepClip = "DUBSTEP_BASS_WOBBLE_0";
var finalClip = dubStepClip + clipNum;

// user-selected dubstep wobbles
fitMedia(finalClip, 1, 1, 5);
// kick
for (var measure = 1; measure < 5; measure += 2) {
    makeBeat(kick, 2, measure, (beatString1 + beatString2)); // concatenating beat strings
}
// clap
for (measure = 1.5; measure < 5; measure++) {
    fitMedia(clap, 3, measure, measure + 0.25);
}
----

[[booleans]]
=== Booleans

[role="curriculum-python"]
All computer decisions are based on conditions built out of a simple logic called *Boolean Logic*. The boolean data type has 2 possible values, `True` and `False`. This contrasts with the other data types (int, float, string) that have many possible values. The `True` and `False` values always start with a capital letter and, unlike string values, do not have quotes.

[role="curriculum-javascript"]
All computer decisions are based on conditions built out of a simple logic called *Boolean Logic*. The boolean data type has 2 possible values, `true` and `false`. This contrasts with the other data types (int, float, string) that have many possible values. The `true` and `false` values always start with a lower-case letter and, unlike string values, do not have quotes.

[role="curriculum-python"]
.COMPARISON OPERATORS
****
The comparison operators are used to generate boolean values. They compare 2 values of the same data type and return either `True` or `False`.
[cols="^h,"]
|===
|==
| is identical to
|!=
|is not identical to
|>
|greater than
|>=
|greater than or equal
|<
|less than
|\<=
|less than or equal
|===

Note: Checking if two values are identical (==) is unrelated to assigning a value to a variable (=).
****

[role="curriculum-javascript"]
.COMPARISON OPERATORS
****
The comparison operators are used to generate boolean values. They compare 2 values of the same data type and return either `true` or `false`.
[cols="^h,"]
|===
| ==
| is identical to
|!=
|is not identical to
|>
|greater than
|>=
|greater than or equal
|<
|less than
|\<=
|less than or equal
|===

Note: Checking if two values are identical (==) is unrelated to assigning a value to a variable (=).
****

[role="curriculum-python"]
Just like numbers have numeric operators (`+-*/`), booleans have their own operators. The 3 boolean operators (sometimes referred to as logical operators) are `and`, `or`, and `not`.

[role="curriculum-javascript"]
Just like numbers have numeric operators (`+-*/`), booleans have their own operators. The 3 boolean operators (sometimes referred to as logical operators) are `&&`, `||`, and `!`, read as "AND," "OR," and "NOT," respectively.

[role="curriculum-python"]
* `and`: Takes 2 boolean inputs and returns `True` only when both inputs are `True`, otherwise returns `False`.
* `or`: Takes 2 boolean inputs and returns `True` when at least 1 input is `True`, otherwise returns `False`.
* `not`: Takes 1 boolean input and returns the opposite (negated) boolean.

[role="curriculum-javascript"]
* `&&`: Takes 2 boolean inputs and returns `true` only when both inputs are `true`, otherwise returns `false`.
* `||`: Takes 2 boolean inputs and returns `true` when at least 1 input is `true`, otherwise returns `false`.
* `!`: Takes 1 boolean input and returns the opposite (negated) boolean.

////
JAF: some examples might be useful here, e.g. True and False = False, etc.
////

[role="curriculum-python"]
.OPERATORS, EXPRESSIONS, AND STATEMENTS
****
The following is a review of terminology used throughout the curriculum, listed from lowest to highest level:

* *Operator*: a character that represents an action. We have seen arithmetic operators (`+-*=`), comparison operators (`>`, `>=`, `<`, `\<=`, `==`, `!=`), and boolean operators (`and`, `or`, `not`).
* *Expression*: A combination of one or more values, constants, variables, operators, and functions. The computer evaluates expressions to produce a another value, usually a single numeric or boolean value.
* *Statements*: An element of a programming language that expresses some action to be taken by the computer. Statements contain and combine expressions.
****

[role="curriculum-javascript"]
.OPERATORS, EXPRESSIONS, AND STATEMENTS
****
The following is a review of terminology used throughout the curriculum, listed from lowest to highest level:

* *Operator*: a character that represents an action. We have seen arithmetic operators (`+-*=`), comparison operators (`>`, `>=`, `<`, `\<=`, `==`, `!=`), and boolean operators (`&&`, `||`, `!`).
* *Expression*: A combination of one or more values, constants, variables, operators, and functions. The computer evaluates expressions to produce a another value, usually a single numeric or boolean value.
* *Statements*: An element of a programming language that expresses some action to be taken by the computer. Statements contain and combine expressions.
****

Here are some simple boolean expressions.  Before running the code, try to determine if each of the expression is TRUE or FALSE.

[role="curriculum-python"]
[source,python]
----
# Booleans: Before running the code, determine if each of the expression is true or false

from earsketch import *
setTempo(120)

# Expression 1
# Is it true that 1 + 1 equals to 2?
a = (1 + 1) == 2
print(a)

# Expression 2
# Is it true that 2 + 2 does not equal to 5?
b = (2 + 2) != 5
print(b)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Booleans: Before running the code, determine if each of the expression is true or false

setTempo(120);

// Expression 1
// Is it true that 1 + 1 equals to 2?
var a = (1 + 1 == 2);
println(a);

// Expression 2
// Is it true that 2 + 2 does not equal to 5?
var b = (2 + 2 != 5);
println(b);
----

Here is a compound Boolean example.  Do you see the difference between the last two expressions?

[role="curriculum-python"]
[source,python]
----
# Compound Booleans: Before running the code, determine if each of the expression is true or false

from earsketch import *
setTempo(120)

# Expression 1
startMeasure = 1
endMeasure = 9

# Is it true that startMeasure equals to 1 AND endMeasure is greater than 10?
a = (startMeasure == 1) and (endMeasure > 10)
print(a)

# Expression 2
# Is it true that startMeasure equals to 1 OR endMeasure is greater than 10?
b = (startMeasure == 1) or (endMeasure > 10)
print(b)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Compound Booleans: Before running the code, determine if each of the expression is true or false

setTempo(120);

// Expression 1
var startMeasure = 1;
var endMeasure = 9;

// Is it true that startMeasure equals to 1 AND endMeasure is greater than 10?
var a = (startMeasure == 1 && endMeasure > 10);
println(a);

// Expression 2
// Is it true that startMeasure equals to 1 OR endMeasure is greater than 10?
var b = (startMeasure == 1 || endMeasure > 10);
println(b);
----

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/Screencast-Ch17-2-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/Screencast-Ch17-2-JS.mp4[]

[[conditionalstatements]]
=== Conditional Statements

[role="curriculum-python"]
Boolean logic allows a program to make a decision based on a condition. A *condition* is an expression that evaluates to a boolean, either `True` or `False`.  The _if_ statement executes specific lines of code only when its condition is `True`. Like other Python constructs, the lines of code to be executed are grouped into an indented block beneath the statement. Additionally, a colon (`:`) follows the statement. The syntax for an _if_ statement is shown below.

[role="curriculum-javascript"]
Boolean logic allows a program to make a decision based on a condition. A *condition* is an expression that evaluates to a boolean, either `true` or `false`.  The _if_ statement executes specific lines of code only when its condition is `true`. Like other JavaScript constructs, the lines of code to be executed are surrounded by curly brackets (`{}`). The syntax for an _if_ statement is shown below.


[role="curriculum-python"]
[source,python]
----
if condition:
    statement to execute if condition evaluates to True
----

[role="curriculum-javascript"]
[source,javascript]
----
if (condition){
    statement to execute if condition evaluates to true
}
----

In the event that an _if_ statement's condition is false, its code block is not executed; the code block is skipped. In some situations, we want some other code to be executed when the condition is false. This can be done with an _if-else_ statement. Interact with the example below to discover how _if_ and _if-else_ statements work.

[role="curriculum-python curriculum-mp4"]
[[video17bpy]]
video::./videoMedia/Screencast-Ch17-3-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17bjs]]
video::./videoMedia/Screencast-Ch17-3-JS.mp4[]

Let’s start off very simple.  Before running this code, take a guess as to what the code will print out.

[role="curriculum-python"]
[source,python]
----
# Conditionals 1: Using Simple Conditionals

# Setup
from earsketch import *
setTempo(120)

# Example 1: What is 1 + 1?  Take a guess as to what will be printed out.
answer = 1 + 1
if answer == 2:
    print("The answer is 2")

if answer == 3:
    print("The answer is 3")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Conditionals 1: Using Simple Conditionals

// Setup
setTempo(120);

// Example 1: What is 1 + 1?  Take a guess as to what will be printed out.
var answer = 1 + 1;
if (answer == 2) {
    println("The answer is 2");
}

if (answer == 3) {
    println("The answer is 3");
}
----

Now let’s do something that relates to music.

[role="curriculum-python"]
[source,python]
----
# Conditionals 2: Musical example of conditionals

# Setup
from earsketch import *
setTempo(140)

# What music do you want to listen to?
a = "energetic"
b = "rock"

# Did you want to listen to energetic hip hop?
if (a == "energetic") and (b == "hip hop"):
    print("Here is an energetic hiphop song!")
    fitMedia(RD_TRAP_MAIN808_BEAT_6, 1, 1, 9)
    fitMedia(RD_TRAP_ANALOGSINELEAD_1, 2, 1, 9)

# Energetic hip hop isn't what you were looking for?
else:
    print("Here is an energetic rock song!")
    fitMedia(RD_ROCK_POPRHYTHM_MAINDRUMS_6, 1, 1, 9)
    fitMedia(RD_ROCK_POPRHYTHM_GUITAR_12, 2, 1, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Conditionals 2: Musical example of conditionals

// Setup
setTempo(140);

// What music do you want to listen to?
var a = "energetic";
var b = "rock";

// Did you want to listen to energetic hip hop?
if (a == "energetic" && b == "hip hop") {
    println("Here is an energetic hiphop song!");
    fitMedia(RD_TRAP_MAIN808_BEAT_6, 1, 1, 9);
    fitMedia(RD_TRAP_ANALOGSINELEAD_1, 2, 1, 9);

// Energetic hip hop isn't what you were looking for?
} else {
    println("Here is an energetic rock song!");
    fitMedia(RD_ROCK_POPRHYTHM_MAINDRUMS_6, 1, 1, 9);
    fitMedia(RD_ROCK_POPRHYTHM_GUITAR_12, 2, 1, 9);
}
----

Let’s now use the Console Input along with Conditional Statements to create an interactive program.  In the following examples, your input will determine what music will be played.

[role="curriculum-python"]
[source,python]
----
# Conditionals 3: Change your answer to see how it affects the conditional statement

# Setup
from earsketch import *
setTempo(120)

# Body

a = readInput("Do you like hip-hop music? Type yes or no.")
# using logical OR, in case user capitalizes their response.
if (a == "yes") or (a == "Yes") or (a == "YES"):
    print("Hip-hop it is!")
    fitMedia(YG_NEW_HIP_HOP_ARP_1, 1, 1, 9)
    fitMedia(RD_TRAP_MAIN808_BEAT_1, 2, 1, 9)
# an answer other than "Yes" or "yes" was entered
else:
    print("Ok, here is some funk.")
    fitMedia(YG_NEW_FUNK_ELECTRIC_PIANO_4, 1, 1, 9)
    fitMedia(YG_NEW_FUNK_DRUMS_4, 2, 1, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Conditionals 3: Change your answer to see how it affects the conditional statement

// Setup
setTempo(120);

// Body
var a = readInput("Do you like hip-hop music? Type yes or no.");
// using logical OR, in case user capitalizes their response.
if ((a == "yes") || (a == "Yes") || (a == "YES")) {
    println("Hip-hop it is!");
    fitMedia(YG_NEW_HIP_HOP_ARP_1, 1, 1, 9);
    fitMedia(RD_TRAP_MAIN808_BEAT_1, 2, 1, 9);
// anything other than "yes" or "Yes" was typed
} else {
    println("Ok, here is some funk.");
    fitMedia(YG_NEW_FUNK_ELECTRIC_PIANO_4, 1, 1, 9);
    fitMedia(YG_NEW_FUNK_DRUMS_4, 2, 1, 9);
}
----

[role="curriculum-python"]
In some situations we want to choose to execute one block out of three or more options. This is achieved by using _elif_ (short for else-if) statements in between _if_ and _else_ statements. A series of _if_, _elif_, and _else_ statements can be used to check multiple conditions.

[role="curriculum-javascript"]
In some situations we want to choose to execute one block out of three or more options. This is achieved by using _else if_  statements in between _if_ and _else_ statements. A series of _if_, _else if_, and _else_ statements can be used to check multiple conditions.


[role="curriculum-python"]
_if_, _elif_, and _else_ statements can be used create interesting musical variations by making changes based on the status of variables. The following example lets the user choose the instrumentation. User input is taken as a string and assigned to a variable. Then, conditions are checked in a series of statements to determine which instrument plays first.

[role="curriculum-javascript"]
_if_, _else if_, and _else_ statements can be used create interesting musical variations by making changes based on the status of variables. The following example lets the user choose the instrumentation. User input is taken as a string and assigned to a variable. Then, conditions are checked in a series of statements to determine which instrument plays first.

[role="curriculum-javascript"]
[source,javascript]
----
// Which Comes First: Let the user choose which instrument plays first

// Setup
setTempo(120);

// Body

var first_inst = readInput("Which instrument comes first? Type Guitar, Bass, or Drums.");

if (first_inst == "guitar" || first_inst == "Guitar" || first_inst == "GUITAR") {
    println("Guitar comes first");
    fitMedia(Y02_GUITAR_1, 1, 1, 9);
    fitMedia(Y01_BASS_1, 2, 3, 9);
    fitMedia(Y02_DRUM_SAMPLES_1, 3, 3, 9);
} else if (first_inst == "bass" || first_inst == "Bass" || first_inst == "BASS") {
    println("Bass comes first");
    fitMedia(Y01_BASS_1, 1, 1, 9);
    fitMedia(Y02_GUITAR_1, 2, 3, 9);
    fitMedia(Y02_DRUM_SAMPLES_1, 3, 3, 9);
} else if (first_inst == "drums" || first_inst == "Drums" || first_inst == "DRUMS") {
    println("Drums come first");
    fitMedia(Y02_DRUM_SAMPLES_1, 1, 1, 9);
    fitMedia(Y02_GUITAR_1, 2, 3, 9);
    fitMedia(Y01_BASS_1, 3, 3, 9);
} else {
    println("Please select Guitar, Bass, or Drums.");
}
----


[role="curriculum-python"]
[source,python]
----
# Which Comes First: Let the user choose which instrument plays first

# Setup
from earsketch import *
setTempo(120)

# Body

input = readInput("Which instrument comes first? Type Guitar, Bass, or Drums.")
first_inst = str(input)

if (first_inst == "guitar") or (first_inst == "Guitar") or (first_inst == "GUITAR"):
    print("Guitar comes first")
    fitMedia(Y02_GUITAR_1, 1, 1, 9)
    fitMedia(Y01_BASS_1, 2, 3, 9)
    fitMedia(Y02_DRUM_SAMPLES_1, 3, 3, 9)

elif (first_inst == "bass") or (first_inst == "Bass") or (first_inst == "BASS"):
    print("Bass comes first")
    fitMedia(Y01_BASS_1, 1, 1, 9)
    fitMedia(Y02_GUITAR_1, 2, 3, 9)
    fitMedia(Y02_DRUM_SAMPLES_1, 3, 3, 9)

elif (first_inst == "drums") or (first_inst == "Drums") or (first_inst == "DRUMS"):
    print("Drums come first")
    fitMedia(Y02_DRUM_SAMPLES_1, 1, 1, 9)
    fitMedia(Y02_GUITAR_1, 2, 3, 9)
    fitMedia(Y01_BASS_1, 3, 3, 9)

else:
    print("Please select Guitar, Bass, or Drums.")
----

////
JAF: I am commenting out the nesting example below. I do not find nesting anywhere in the CSP curriculum framework and feel that this is too advanced for this course.

Leaving this here for now in case it could be useful in another context.

BMW - 9/20/16



=== Nesting Statements

Boolean values can change as a result of a program running. For example, a boolean can be used to execute a conditional statement based off the value of a loop counter. Placing a statement inside another statement is known as *nesting*. Indentation increases for each level of nesting.

[role="curriculum-python"]
[source,python]
----
# Additive structure with nested statements

# Setup
from earsketch import *
setTempo(125)

# Music
drums = TECHNO_MAINLOOP_003
bass = ELECTRO_ANALOGUE_BASS_003
lead = TECHNO_POLYLEAD_004

for measure in range(1, 9):

    if measure != 4:  # Place clip on all measures except for measure 4
        fitMedia(drums, 1, measure, measure + 1)

    if measure >= 3:  # Start placing lead clip at measure 3
        fitMedia(lead, 2, measure, measure + 1)

    if measure >= 5:  # Start placing bass clip at measure 5
        fitMedia(bass, 3, measure, measure + 1)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Additive structure with nested statements

// Setup
setTempo(130);

// Music
var drums = TECHNO_MAINLOOP_003;
var bass = ELECTRO_ANALOGUE_BASS_003;
var lead = TECHNO_POLYLEAD_004;

for (var measure = 1; measure < 9; measure++) {
    if (measure != 4) { // Place clip on all measures except for measure 4
        fitMedia(drums, 1, measure, measure + 1);
    }
    if (measure >= 3) { // Start placing lead clip at measure 3
        fitMedia(lead, 2, measure, measure + 1);
    }
    if (measure >= 5) { // Start placing bass clip at measure 5
        fitMedia(bass, 3, measure, measure + 1);
    }
}
----

JAF: Big picture suggestions and questions:
* Can we make the last example with console input more compelling in terms of the musical application of the input?
* Can we bring in one more example of compound booleans (i.e. a > b and b > c) without having to add a whole new example? Perhaps as part of the revision of this last example?

I'm not satisfied with the solutions to the big picture suggestions above currently. Revisiting this section.

BMW - 9/20/16
////

////
Video Idea(s): I think theres a number of opportunities for videos in this chapter. At the end of the "Booleans" section, I think it would be good to run through some boolean expression examples. I'm thinking of this block from GGC curriculum:

----
tempo = 90

start = 1

clipName = "Y03_DRUMS_SAMPLE_1"

track = 3

a = (tempo > 100)

b = (start < 4)

c = (clipName !=  "Y03_DRUMS_SAMPLE_2")

d = (track == 3)

e = (start >= track)
----

Run through these one by one, preferably writing on the screen to replace each variable with its value and checking to see if it evaluates to true or false. Write true and false on the screen. These expressions should be expanded or added to to include boolean (logical) operators as well.

Information above may still apply, especially if we make new videos.

BMW - 9/20/16
////

[[chapter17summary]]
=== Chapter 17 Summary

[role="curriculum-python"]
* A program can access information from the user via *console input*, text-based data taken from the keyboard. The `readInput()` function is used to take console input. It displays its argument to the user as a prompt.
* The *boolean* data type has only two possible values, `True` and `False`.
* Boolean values are generated by comparison operators. They are: `==`, `!=`, `>`, `>=`, `<`, `<=`.
* Boolean operators
** `and`: only `True` when both inputs are `True`
** `or`: `True` when at least one input is `True`
** `not`: returns the opposite boolean value
* An *operator* is a character that represents an action.
* *Expressions* are evaluated by the computer to produce a value.
* A *statement* is an element of a programming language that expresses some action to be taken by the computer.
* A *condition* is an expression that evaluates to a boolean using comparison operators. Furthermore, boolean operators can be used to check multiple conditions.
* The _if_ statement only executes its code block when its condition is `True`. Revisit its syntax <<console-input-and-conditionals#conditionalstatements,here>>.
* In the event that an _if_ statement's condition is `False`, an optional _else_ statement allows an alternative code block to be executed.
* Interesting musical variations can be created using a combination of _if_, _elif_, and _else_ statements. Each statement checks the status of a variable with conditions.

[role="curriculum-javascript"]
* A program can access information from the user via *console input*, text-based data taken from the keyboard. The `readInput()` function is used to take console input. It displays its argument to the user as a prompt.
* The *boolean* data type has only two possible values, `true` and `false`.
* Boolean values are generated by comparison operators. They are: `==`, `!=`, `>`, `>=`, `<`, `<=`.
* Boolean operators
** `&&`: only `true` when both inputs are `true`
** `||`: `true` when at least one input is `true`
** `!`: returns the opposite boolean value
* An *operator* is a character that represents an action.
* *Expressions* are evaluated by the computer to produce a value.
* A *statement* is an element of a programming language that expresses some action to be taken by the computer.
* A *condition* is an expression that evaluates to a boolean using comparison operators. Furthermore, boolean operators can be used to check multiple conditions.
* The _if_ statement only executes its code block when its condition is `true`. Revisit its syntax <<console-input-and-conditionals#conditionalstatements,here>>.
* In the event that an _if_ statement's condition is `false`, an optional _else_ statement allows an alternative code block to be executed.
* Interesting musical variations can be created using a combination of _if_, _else if_, and _else_ statements. Each statement checks the status of a variable with conditions.

[[chapter-questions]]
=== Questions

[question]
--
Which of the following would be considered an example of data type conversion?
[answers]
* Turning a string into a number.
* Storing a user-defined tempo in a variable.
* Using readInput() to ask a user for a genre.
* Producing a Boolean through a comparison operator.
--

[role="curriculum-python"]
[question]
--
What would the output of this block of code be (what would print to the console)?
[source,python]
----
n = 5
if (n * 3) == 15:
    n = 5 + n
    print(n)
----
[answers]
* `10`
* `n`
* `True`
* `False`
--

[role="curriculum-javascript"]
[question]
--
What would the output of this block of code be (what would print to the console)?
[source,javascript]
----
var n = 5;
if (n * 3 == 15) {
    n = 5 + n;
    println(n);
}
----
[answers]
* `10`
* `n`
* `True`
* `False`
--
