[[ch_31]]
== Creating Beats with makeBeat
:nofooter:

The 16 elements of a beat string make up the 16 sixteenth notes found in one measure of 4/4 time. In creating beats with `makeBeat()` the style, instrument, and role of the beat should be taken into consideration in creating the rhythm pattern. This guide will provide sample rhythm patterns in the style of 4/4 Time, Hip Hop, Funk, Dubstep, and African Drum Ensemble based patterns. This will not represent a complete list of patterns, rather it will act as a guide in identifying the characteristics of percussion beats and provide string example for `makeBeat()`.

[[thethreeelementsofapercussionline]]
=== The three elements of a percussion line

The drum set or percussion line can be divided into three elements:

. *Bass Drum or Lowest Pitched Drum:* Usually provides the “center of beat.” The ear will gravitate towards the lowest pitches in a drum pattern to "center in" on the meter and feel for the music. Bass Drum beats usually emphasize beats 1 and 3 in 4/4 time.
. *Back Beat:* This is usually a snare drum, clap, snap, or other mid-pitched percussion instrument. The Back Beats complement the Bass Drum Line, provide syncopation and "pull", and emphasize beats 2 and 4 in 4/4 time. The Bass Drum and BackBeat work together to provide the bulk of the sense of style and feel in percussion lines.
. *Running 8^th^ or 16^th^ Patterns:* These running lines of 8^th^ or 16^th^ notes usually are played with a high pitched metallic instrument such as a Hi Hat, Ride Cymbal, Tambourine, or other non-pitched instrument. The "running" pattern provides a "motor" that lays down a foundation for the Bass Drum and Back Beat lines. The running patterns also provide the listener with a clear sense of the "microbeat" and meter for the music. Changing the timbre within the running pattern (Closed and Open Hi hat for example) can supplement the rhythmic interest of the Back Beat.

At the core level, you can visualize the Bass Drum, Back Beat, and Running 8^th^ / 16^th^ in the following manner with `makeBeat()`. Note: the beat strings in the following tables have spaces in between each character in order to ensure proper display in a web browser (e.g., "– – – –"). Remove the extraneous spaces when using the strings in your own code.

*Bass Drum:*

|==========================================================================
|  | Beats |  |  |
| String Pattern | 1 | 2 | 3 | 4
| "0 + + + – – – – 0 + + + – – – –" | 0 + + + | – – – – | 0 + + + | – – – –
|==========================================================================


*Back Beat:*

|==========================================================================
|  | Beats |  |  |
| String Pattern | 1 | 2 | 3 | 4
| "– – – – 0 + + + – – – – 0 + + +" | – – – – | 0 + + + | – – – – | 0 + + +
|==========================================================================


*Running 8^th^:*

|==========================================================================
|  | Beats |  |  |
| String Pattern | 1 | 2 | 3 | 4
| "0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 +" | 0 + 0 + | 0 + 0 + | 0 + 0 + | 0 + 0 +
|==========================================================================

4/4 Time General Patterns (Typical of “Rock Beat” or straight 4/4 type music)

*Bass Drum String Patterns:*

bassBeat01 = "0 + + + – – – – 0 + + + – – – –"

bassBeat02 = "0 + + + – – 0 + 0 + + + – – – –"

"0 + + + – – 0 + 0 + + + – – 0 +"

"0 + + + 0 + + + 0 + + + 0 + + +"

"0 + + + 0 + + + 0 + 0 + 0 + + +"

"0 + + + 0 + + + 0 + + + 0 + 0 +"

*Back Beat String Patterns:*

"– – – – 0 + + + – – – – 0 + + +"

"– – – – 0 + + + – – – – 0 + 0 +"

"– – – – 0 + 0 + – – – – 0 + + +"

"– – – – 0 + + + – 0 + – 0 + + +"

*8th Note Running Pattern:*

“ 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 +”

*Code Example with Fill:*

[role="curriculum-python"]
[source,python]
----
# Rock Beat: Example
# Tempo best between 110 and 132 bpm

from earsketch import *
setTempo(120)

bass = OS_LOWTOM01
snare = OS_SNARE01
hiOpen = OS_OPENHAT01
hiClosed = OS_CLOSEDHAT01
bassBeat = "0+++--0+0+++----"
snareBeat = "----0+++-0+-0+++"
running = "0+0+0+0+0+0+0+0+"
fillBass = "0+++0+++0+0+0+0+"
fillSnare = "0+++0+++0+0+0000"

for measure in range(1, 9):
    if measure % 4 != 0:
        makeBeat(hiClosed, 1, measure, running)
        makeBeat(snare, 2, measure, snareBeat)
        makeBeat(bass, 3, measure, bassBeat)
    else:
        makeBeat(hiClosed, 1, measure, running)
        makeBeat(snare, 2, measure, fillSnare)
        makeBeat(bass, 3, measure, fillBass)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Rock Beat: Example
// Tempo best between 110 and 132 bpm

setTempo(120);

var bass = OS_LOWTOM01;
var snare = OS_SNARE01;
var hiOpen = OS_OPENHAT01;
var hiClosed = OS_CLOSEDHAT01;
var bassBeat = "0+++--0+0+++----";
var snareBeat = "----0+++-0+-0+++";
var running = "0+0+0+0+0+0+0+0+";
var fillBass = "0+++0+++0+0+0+0+";
var fillSnare = "0+++0+++0+0+0000";

for (var measure = 1; measure < 9; measure++) {
    if (measure % 4 != 0) {
        makeBeat(hiClosed, 1, measure, running);
        makeBeat(snare, 2, measure, snareBeat);
        makeBeat(bass, 3, measure, bassBeat);
    } else {
        makeBeat(hiClosed, 1, measure, running);
        makeBeat(snare, 2, measure, fillSnare);
        makeBeat(bass, 3, measure, fillBass);
    }
}
----


[[somefunkandhiphopbeats]]
=== Some Funk and Hip Hop Beats

Hip Hop and Funk both function well at tempos between 84 and 92 beats per minute. If you use a running beat of 8ths, the style will gravitate closer to Hip Hop. A running beat of 16ths will simulate a funk style.

*Bass Drum Strings:*

funkbassbeat1 = " 0 + 0 + – – – – 0 + 0 + – 0 + +"

funkbassbeat2 = "0 – 0 – – – – – – – 0 – – 0 – –"

*Back Beat Strings:*

funkbackbeat1 = "– – – – 0 – – 0 – 0 – 0 0 – – –"

funkbackbeat2 = "– – – – 0 – – 0 – 0 – 0 0 – – 0"

*‘Amen Beat’ style strings (using a list to store snare and bass sounds):*

drumList = [bass, snare]

amenbeat1 = " 0 + 0 + 1 + + 1 – 1 0 0 1 + + 1"

amenbeat2 = "0 + 0 + 1 + + 1 – 1 0 0 – – 1 +"

amenbeat3 = "– 1 0 0 1 + + 1 – 1 0 + – – 1 +"

*16^th^ Beat Running (using a list to store closed and open hi hat sounds):*

Hats = [closed, open]

sixteenthHL1 = "0000100000001000"

sixteenthHL2 = "0000100101011000"

sixteenthHL3 = "0000100101011100"

sixteenthHL4 = "0000100101011101"

sixteenthHLFill = "0000100101011111"

*Funk Beat Example with Fill:*

[role="curriculum-python"]
[source,python]
----
# Funk Beat: Example
# Tempo best between 92 and 100 bpm

from earsketch import *
setTempo(92)

funkbassbeat1 = "0+0+----0+0+-0++"
funkbassbeat2 = "0-0-------0--0--"
funkbackbeat1 = "----0--0-0-00---"
funkbackbeat2 = "----0--0-0-00--0"
sixteenthHL2 = "0000100101011000"
sixteenthHLFill = "0000100101011111"

bass = OS_LOWTOM01
snare = OS_SNARE01
hiOpen = OS_OPENHAT01
hiClosed = OS_CLOSEDHAT01
hats = [hiClosed, hiOpen]

for measure in range(1, 9):
    if (measure % 4) != 0:
        makeBeat(hats, 1, measure, sixteenthHL2)
        makeBeat(snare, 2, measure, funkbackbeat1)
        makeBeat(bass, 3, measure, funkbassbeat1)
    else:
        makeBeat(hats, 1, measure, sixteenthHLFill)
        makeBeat(snare, 2, measure, funkbackbeat2)
        makeBeat(bass, 3, measure, funkbassbeat2)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Funk Beat: Example
// Tempo best between 92 and 100 bpm

setTempo(92);

var funkbassbeat1 = "0+0+----0+0+-0++";
var funkbassbeat2 = "0-0-------0--0--";
var funkbackbeat1 = "----0--0-0-00---";
var funkbackbeat2 = "----0--0-0-00--0";
var sixteenthHL2 = "0000100101011000";
var sixteenthHLFill = "0000100101011111";

var bass = OS_LOWTOM01;
var snare = OS_SNARE01;
var hiOpen = OS_OPENHAT01;
var hiClosed = OS_CLOSEDHAT01;
var hats = [hiClosed, hiOpen];

for (var measure = 1; measure < 9; measure++) {
    if (measure % 4 != 0) {
        makeBeat(hats, 1, measure, sixteenthHL2);
        makeBeat(snare, 2, measure, funkbackbeat1);
        makeBeat(bass, 3, measure, funkbassbeat1);
    } else {
        makeBeat(hats, 1, measure, sixteenthHLFill);
        makeBeat(snare, 2, measure, funkbackbeat2);
        makeBeat(bass, 3, measure, funkbassbeat2);
    }
}
----



*Amen Beat Example:*

[role="curriculum-python"]
[source,python]
----
# Amen Break: Example
# Tempo best between 82 to 92 bpm

from earsketch import *
setTempo(88)

bass = OS_LOWTOM01
snare = OS_SNARE01
hiOpen = OS_OPENHAT01
hiClosed = OS_CLOSEDHAT01
hats = [hiClosed, hiOpen]
bassSnare = [bass, snare]

amenbeat1 = "0+0+1++1-1001++1"
amenbeat2 = "0+0+1++1-100--1+"
amenbeat3 = "-1001++1-10+--1+"
sixteenth = "0000100000001000"
sixteenthHL2 = "0000100101011000"

for measure in range(1, 9, 4):
    makeBeat(bassSnare, 2, measure, amenbeat1)
    makeBeat(bassSnare, 2, measure + 1, amenbeat2)
    makeBeat(bassSnare, 2, measure + 2, amenbeat2)
    makeBeat(bassSnare, 2, measure + 3, amenbeat3)

for measure in range(1, 9):
    makeBeat(hats, 1, measure, sixteenthHL2)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Amen Break: Example
// Tempo best between 82 to 92 bpm

setTempo(88);

var bass = OS_LOWTOM01;
var snare = OS_SNARE01;
var hiOpen = OS_OPENHAT01;
var hiClosed = OS_CLOSEDHAT01;
var hats = [hiClosed, hiOpen];
var bassSnare = [bass, snare];

var amenbeat1 = "0+0+1++1-1001++1";
var amenbeat2 = "0+0+1++1-100--1+";
var amenbeat3 = "-1001++1-10+--1+";
var sixteenth = "0000100101011000";

for (var measure = 1; measure < 9; measure += 4) {
    makeBeat(bassSnare, 2, measure, amenbeat1);
    makeBeat(bassSnare, 2, measure + 1, amenbeat2);
    makeBeat(bassSnare, 2, measure + 2, amenbeat2);
    makeBeat(bassSnare, 2, measure + 3, amenbeat3);
}

for (var measure = 1; measure < 9; measure++) {
    makeBeat(hats, 1, measure, sixteenth);
}
----


[[dubstepstylebeats]]
=== Dubstep Style Beats:

Dubstep music usually is played faster than 136 beats per minute with a ‘halftime’ feel using triplet style rhythms in the Bass Drum and Back Beat. Beats here will simulate the triplet style with a 3-sixteenth, 3-sixteenth, 2-sixteenth pattern. Dubstep music also has longer patterns, usually extending across 4 measures, so the different beats are meant to be played in succession. Dubstep music also ‘breaks’ the Bass on 1 and 3 and the Back Beat on 2 and 4 rules.

*Dub Bass Patterns (Played in succession)*

dubBass1 = "0 + + + + + + + – – – – – – 0 +"

dubBass2 = "0 + + 0 + + 0 + – – – 0 + + 0 +"

dubBass3 = "0 + + 0 + + 0 + – – – – – – 0 +"

dubBass4 = "0 0 + 0 0 + 0 + – – – – – – – –"

*Dub Snare Patterns (This example only plays on measure 4 of the pattern)*

dubSnare = "– – – – – – – – – – 0 0 0 + – –"

*Dub Clap Patterns:*

dubClap = "– – – – – – – – 0 + + + + + + +"

dubClap1 = "– – – – – – – – 0 + + + + + 0 +"

*Dub Hat Patterns: (With [closed, open] list)*

dubHats1 = "– – – – 0 0 0 + 1 + + + + + + +"

dubHats2 = "– – 0 + + 0 + + 1 + + + + + + +"

dubHats3 = "– – – – 0 0 0 + 1 + + + + + + +"

dubHats4 = "– – 0 + + 0 + + 1 + + 0 + + 0 +"



*Dubstep Example:*

[role="curriculum-python"]
[source,python]
----
# Dubstep Beat: Example
# Tempo best if faster than 136 bpm

from earsketch import *
setTempo(140)

dubBass1 = "0+++++++------0+"
dubBass2 = "0++0++0+---0++0+"
dubBass3 = "0++0++0+------0+"
dubBass4 = "00+00+0+--------"
dubSnare = "----------000+--"

# Only Used on measure 4
dubClap = "--------0+++++++"
dubClap1 = "--------0+++++0+"
dubHats1 = "----000+1+++++++"

# Should be a triplet on beat 2
dubHats2 = "--0++0++1+++++++"
dubHats3 = "----000+1+++++++"
dubHats4 = "--0++0++1++0++0+"

bass = OS_LOWTOM01
snare = OS_SNARE01
hiOpen = OS_OPENHAT01
hiClosed = OS_CLOSEDHAT01
hats = [hiClosed, hiOpen]

for measure in range(1, 9, 4):
    makeBeat(hats, 1, measure, dubHats1)
    makeBeat(hats, 1, measure + 1, dubHats2)
    makeBeat(hats, 1, measure + 2, dubHats3)
    makeBeat(hats, 1, measure + 3, dubHats4)
    makeBeat(snare, 2, measure, dubClap)
    makeBeat(snare, 2, measure + 1, dubClap)
    makeBeat(snare, 2, measure + 2, dubClap)
    makeBeat(snare, 2, measure + 3, dubClap1)
    makeBeat(snare, 3, measure + 3, dubSnare)
    makeBeat(bass, 4, measure, dubBass1)
    makeBeat(bass, 4, measure + 1, dubBass2)
    makeBeat(bass, 4, measure + 2, dubBass3)
    makeBeat(bass, 4, measure + 3, dubBass4)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Dubstep Beat: Example
// Tempo best if faster than 136 bpm

setTempo(140);

var dubBass1 = "0+++++++------0+";
var dubBass2 = "0++0++0+---0++0+";
var dubBass3 = "0++0++0+------0+";
var dubBass4 = "00+00+0+--------";
var dubSnare = "----------000+--";

// Only Used on measure 4
var dubClap = "--------0+++++++";
var dubClap1 = "--------0+++++0+";
var dubHats1 = "----000+1+++++++";

// Should be a triplet on beat 2
var dubHats2 = "--0++0++1+++++++";
var dubHats3 = "----000+1+++++++";
var dubHats4 = "--0++0++1++0++0+";

var bass = OS_LOWTOM01;
var snare = OS_SNARE01;
var hiOpen = OS_OPENHAT01;
var hiClosed = OS_CLOSEDHAT01;
var hats = [hiClosed, hiOpen];

for (var measure = 1; measure < 9; measure += 4) {
    makeBeat(hats, 1, measure, dubHats1);
    makeBeat(hats, 1, measure + 1, dubHats2);
    makeBeat(hats, 1, measure + 2, dubHats3);
    makeBeat(hats, 1, measure + 3, dubHats4);
    makeBeat(snare, 2, measure, dubClap);
    makeBeat(snare, 2, measure + 1, dubClap);
    makeBeat(snare, 2, measure + 2, dubClap);
    makeBeat(snare, 2, measure + 3, dubClap1);
    makeBeat(snare, 3, measure + 3, dubSnare);
    makeBeat(bass, 4, measure, dubBass1);
    makeBeat(bass, 4, measure + 1, dubBass2);
    makeBeat(bass, 4, measure + 2, dubBass3);
    makeBeat(bass, 4, measure + 3, dubBass4);
}
----


[[africanstyledrummingpatterns]]
=== African Style Drumming Patterns

These patterns seek to emulate the style of drumming ensembles and multi-layered percussion music based on African music. The patterns here are adapted from the “Unifix Patterns” as presented on the link:http://www.philtulga.com/unifix.html[Phil Tulga website^]. The drum patterns are designed to “weave” in and out and each pattern complements the other. These patterns also demonstrate the use of lists.

*Unifix Pattern Set 1:*

ftBeat = "0 – – 0 1 – – 1 0 – – 0 1 – – 1"

tcBeat = "1 – 1 – 1 1 – 1 – 0 – 0 – 1 1 –"

guiroBeat = "1 – 0 0 1 – 0 0 – 0 – 0 1 – 0 0"

skakerBeat = "1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1"

tubeBeat = "1 – – – 0 – – – 1 – – – 0 – – –"

bottleBeat = "0 – 0 – 1 1 – 0 – 0 – 0 – 1 1 –"

*High Life from Nigeria:*

ftBeat = "0 – – 0 0 – 1 – 0 – – 0 0 – 1 1"

tcBeat = "0 – – 0 0 – 1 – 0 – – 0 0 – 1 1"

guiroBeat = "0 – – 1 0 – 1 – – 1 – 1 0 – 1 –"

shakerBeat = "1 0 0 1 1 – 0 1 – 1 0 1 1 – 1 0"

tubeBeat = "1 – – 1 1 – 0 – – 1 – 1 – 1 0 –"

bottleBeat = "– 1 – 0 – – – 1 – 0 – – – 1 – 0"

*Fanga Beat from Liberia:*

ftBeat = "0 – – 1 – 1 1 – 0 – 0 – 1 1 – –"

tcBeat = "0 – – 1 – 1 1 – 0 – 0 – 1 1 – –"

guiroBeat = "0 – 1 – – – – 0 – – 1 1 1 – – 1"

shakerBeat = "1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1"

tubeBeat = "0 – – 0 – – – – 1 – 1 – – – – 1"

bottleBeat = "– – – 1 – 1 1 – 0 – 0 – 1 1 – 0"

*From Ghana:*

ftBeat = "0 0 0 1 – 1 0 – 0 0 0 1 – 1 0 –"

tcBeat = "0 – – 1 – 1 0 – 0 – – 1 – 1 0 –"

guiroBeat = "0 – – 1 0 – 1 – – 1 – 1 0 – 1 –"

shakerBeat = "1 0 0 1 – 1 0 1 – 1 0 1 1 0 0 1"

tubeBeat = "0 – – 1 – – 0 – – 1 – – 1 – – 0"

bottleBeat = "0 – 0 – – – – – 0 0 – 1 – – – 0"

*Example of Unifix Patterns*

[role="curriculum-python"]
[source,python]
----
# Unifix-style Beat: Example
# Tempo best between 92 and 110 bpm, but can be faster
from earsketch import *
setTempo(100)

fractionTubes = [HOUSE_BREAKBEAT_020, HIPHOP_TRAPHOP_BEAT_007]
tinCanDrum = [OS_COWBELL01, OS_COWBELL02]
guiro = [ELECTRO_DRUM_MAIN_BEAT_004, ELECTRO_DRUM_MAIN_BEAT_007]
shaker = [OS_OPENHAT02, OS_OPENHAT03]
tubeDrums = [OS_CLAP01, OS_CLAP02]
waterBottles = [OS_SNARE01, OS_OPENHAT06]

uniList = [fractionTubes, tinCanDrum, guiro, shaker, tubeDrums, waterBottles]

# From Ghana
ftBeat = "0001-10-0001-10-"
tcBeat = "0--1-10-0--1-10-"
guiroBeat = "0--10-1--1-10-1-"
shakerBeat = "1001-101-1011001"
tubeBeat = "0--1--0--1--1--0"
bottleBeat = "0-0-----00-1---0"

ghanaList = [ftBeat, tcBeat, guiroBeat, shakerBeat, tubeBeat, bottleBeat]

for measure in range(1, 9):
    for i in range(len(ghanaList)):
        track = i + 1
        makeBeat(uniList[i], track, measure, ghanaList[i])
----

[role="curriculum-javascript"]
[source,javascript]
----
// Unifix-style Beat: Example
// Tempo best between 92 and 110 bpm, but can be faster

setTempo(100);

var fractionTubes = [HOUSE_BREAKBEAT_020, HIPHOP_TRAPHOP_BEAT_007];
var tinCanDrum = [OS_COWBELL01, OS_COWBELL02];
var guiro = [ELECTRO_DRUM_MAIN_BEAT_004, ELECTRO_DRUM_MAIN_BEAT_007];
var shaker = [OS_OPENHAT02, OS_OPENHAT03];
var tubeDrums = [OS_CLAP01, OS_CLAP02];
var waterBottles = [OS_SNARE01, OS_OPENHAT06];

var uniList = [fractionTubes, tinCanDrum, guiro, shaker, tubeDrums, waterBottles];

// From Ghana
var ftBeat = "0001-10-0001-10-";
var tcBeat = "0--1-10-0--1-10-";
var guiroBeat = "0--10-1--1-10-1-";
var shakerBeat = "1001-101-1011001";
var tubeBeat = "0--1--0--1--1--0";
var bottleBeat = "0-0-----00-1---0";

var ghanaList = [ftBeat, tcBeat, guiroBeat, shakerBeat, tubeBeat, bottleBeat];

for (var measure = 1; measure < 9; measure++) {
    for (var i = 0; i < ghanaList.length; i++) {
        var track = i + 1;
        makeBeat(uniList[i], track, measure, ghanaList[i]);
    }
}
----
