[[ch_3]]
== Debugging and Documenting
:nofooter:

Sometimes programmers make mistakes that cause code to work incorrectly, or not run at all. Strategies for overcoming these mistakes are presented in this chapter.

[[whatisdebugging]]
=== What is Debugging?
All programmers encounter occasional flaws and unexpected results when running code; no one is immune to mistakes. In programming, coding faults are called *errors*, or *bugs*. The process of finding and fixing bugs is called *debugging*.

Here are three types of errors you can encounter while programming:

. *Syntax errors*: Your program does not run because your code breaks the language's *syntax* rules, which tell how to arrange the code.
. *Runtime errors*: Your program starts to run, but halts due to an error.
. *Logic errors*: Your program runs, but it doesn't do what is expected.

In EarSketch, you can fix logic errors by looking at the DAW to check if the clips you meant to add were actually added in the right place. Print debugging, detailed in <<debugging-logic#,Chapter 15>>, can be used for syntax and runtime errors.

[[usingtheconsole]]
=== Using the Console

[role="curriculum-python curriculum-mp4"]
[[video3py]]
video::./videoMedia/003-02-UsingtheConsole-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video3js]]
video::./videoMedia/003-02-UsingtheConsole-JS.mp4[]

[[documentingcode]]
=== Documenting Code
[role="curriculum-python"]
*Comments* are added to programs to make the code easier to understand for programmers and collaborators. They can also be used to help organize code or to make notes for future use. In Python, comments are indicated by a line starting with a `#` symbol. This symbol tells the computer not to execute the statement on that line.

[role="curriculum-javascript"]
*Comments* are added to programs to make the code easier to understand for programmers and collaborators. They can also be used to help organize code or to make notes for future use. In JavaScript, comments are indicated by a line starting with two forward slashes, `//`. This symbol tells the computer not to execute the statement on that line.

You can narrow down an error by putting comment syntax around a block of code, or *Commenting it out*. Since code that is commented out does not run, the error is somewhere in the commented block if no errors occur when the program is run.

The following script contains an error, but the console does not point to the exact line it is on when the script is executed. Try to locate the error by commenting out blocks of code in the music section. Then, fix the error and verify that the script runs successfully.

////
Code Error in these examples breaks AsciiDoc syntax coloring.
////

[role="curriculum-python"]
[source,python]
----
# Finding Errors 1: Fix the error by commenting out blocks

# Setup
from earsketch import *
setTempo(130)

# Music
claps = HOUSE_BREAKBEAT_006
singleClap = OS_CLAP03
hiHat = HOUSE_BREAKBEAT_012
kick = HOUSE_BREAKBEAT_023
chords = RD_EDM_ANALOGPLUCK_2
lead1 = RD_EDM_ANALOGPLUCK_1
lead2 = RD_TRAP_ARPBLEEPLEAD_5
lead3 = HOUSE_DEEP_ARPLEAD_001
bass1 = ELECTRO_ANALOGUE_BASS_013
bass2 = ELECTRO_ANALOGUE_BASS_008
noiseSweep = TECHNO_WHITENOISESFX_001

# Leads
# Try commenting out this block first
fitMedia(lead1, 3, 17, 24)
fitMedia(lead2, 8, 17, 25)
fitMedia(lead2, 8, 9, 10)
fitMedia(lead2, 8, 11, 12)
fitMedia(lead2, 8, 13, 14)
fitMedia(lead2, 8, 15, 17)
fitMedia(lead3, 4, 5, 24)

# Beat
# Try commenting out this block next
fitMedia(kick, 1, 1, 24)
fitMedia(claps, 2, 5, 16)
fitMedia(claps, 2, 17, 24)
fitMedia(singleClap, 9, 16.75, 16.875)
fitMedia(singleClap, 9, 16.875, 17)
fitMedia(hiHat, 7, 17, 24

# Auxiliary
fitMedia(chords, 3, 1, 17)
fitMedia(noiseSweep, 6, 15, 17)
fitMedia(bass2, 5, 9, 17)
fitMedia(bass1, 5, 17, 24)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Finding Errors 1: Fix the error by commenting out blocks

// Setup
setTempo(130)

// Music
var claps = HOUSE_BREAKBEAT_006;
var singleClap = OS_CLAP03;
var hiHat = HOUSE_BREAKBEAT_012;
var kick = HOUSE_BREAKBEAT_023;
var chords = RD_EDM_ANALOGPLUCK_2;
var lead1 = RD_EDM_ANALOGPLUCK_1;
var lead2 = RD_TRAP_ARPBLEEPLEAD_5;
var lead3 = HOUSE_DEEP_ARPLEAD_001;
var bass1 = ELECTRO_ANALOGUE_BASS_013;
var bass2 = ELECTRO_ANALOGUE_BASS_008;
var noiseSweep = TECHNO_WHITENOISESFX_001;

// Leads
// Try commenting out this block first
fitMedia(lead1, 3, 17, 24);
fitMedia(lead2, 8, 17, 25);
fitMedia(lead2, 8, 9, 10);
fitMedia(lead2, 8, 11, 12);
fitMedia(lead2, 8, 13, 14);
fitMedia(lead2, 8, 15, 17);
fitMedia(lead3, 4, 5, 24);

// Beat
// Try commenting out this block next
fitMedia(kick, 1, 1, 24);
fitMedia(claps, 2, 5, 16);
fitMedia(claps, 2, 17, 24);
fitMedia(singleClap, 9, 16.75, 16.875);
fitMedia(singleClap, 9, 16.875, 17);
fitMedia(hiHat, 7, 17, 24

// Auxiliary
fitMedia(chords, 3, 1, 17);
fitMedia(noiseSweep, 6, 15, 17);
fitMedia(bass2, 5, 9, 17);
fitMedia(bass1, 5, 17, 24);
----

Large, collaborative programming projects often involve large-scale distribution, and have specific standards and methods. For such projects, it is helpful to agree on how to comment. This will ensure that all team members know how to comment and maintain your program in the future. In <<evaluating-correctness-3#Chapter21,Chapter 21>>, we will discuss creative, collaborative work in detail.

[[commonerrors]]
=== Common Errors

The following list of common errors can help you identify and prevent bugs in your scripts.

[role="curriculum-python"]
. *Misspelling:* Spelling mistakes are the most common error across programming languages. When using variables, make sure to use the same name you gave at assignment. Likewise, check the spelling of EarSketch API functions and sound constants.
. *Case sensitivity:* Most words used in programming are case-sensitive. Pay attention to lowercase and uppercase letters used in variable names and EarSketch API functions.
. *Parentheses:* Forgetting an opening or closing parenthesis where needed will cause a <<every-error-explained-in-detail#syntaxerror,syntax error>>. When using functions like `fitMedia()` (or any other EarSketch API function), make sure your arguments are enclosed by parentheses on both ends.
. *Initializing variables*: Do not forget to initialize, or assign values to, variables before you use them. You usually do this at the top of your script.
. *Script setup:* EarSketch adds some code to a new script automatically, but you might accidentally delete `from earsketch import *`.
. *Comments:* Improper commenting will cause a syntax error. Remember that Python comments must start with a `#` symbol.

[role="curriculum-javascript"]
. *Misspelling:* Spelling mistakes are the most common error across programming languages. When using variables, make sure to use the same name you gave at assignment. Likewise, check the spelling of EarSketch API functions and sound constants.
. *Case sensitivity:* Most words used in programming are case-sensitive. Pay attention to lowercase and uppercase letters used in variable names and EarSketch API functions.
. *Parentheses:* Forgetting an opening or closing parenthesis where needed will cause a <<every-error-explained-in-detail#syntaxerror,syntax error>>. When using functions like `fitMedia()` (or any other EarSketch API function), make sure your arguments are enclosed by parentheses on both ends.
. *Initializing variables*: Do not forget to initialize, or assign values to, variables before you use them. You usually do this at the top of your script.
. *Initializing without var:* Forgetting to initialize a variable with `var` in JavaScript can cause some confusing errors. Remember, the correct way to initialize a variable looks like this: `var measure = 1`.
. *Comments:* Improper commenting will cause a syntax error. Remember that JavaScript comments must start with `//`.

[[debuggingexercise]]
=== Debugging Exercise

////
Considering moving the above example into this section.
////

Let's use knowledge of common errors to debug some example code. The two scripts that follow are supposed to produce the same code, but each contains an error. Paste the scripts into the Code Editor and try to correct each error. You may find that running the code is helpful.

[role="curriculum-python"]
[source,python]
----
# Finding Errors 2: Find and fix the error in this script

from earsketch import *
setTempo(88)

fitMedia(electroString, 1, 1, 9)
electroString = Y13_STRING_1

fitMedia(drums, 2, 5, 9)
drums = HIPHOP_DUSTYGROOVE_017
----

[role="curriculum-javascript"]
[source,javascript]
----
// Finding Errors 2: Find and fix the error in this script

setTempo(88);

fitMedia(electroString, 1, 1, 9);
var electroString = Y13_STRING_1;

fitMedia(drums, 2, 5, 9);
var drums = HIPHOP_DUSTYGROOVE_017;
----

[role="curriculum-python"]
[source,python]
----
# Finding Errors 3: Find and fix the error in this script

from earsketch import *
setTempo(88)

electroString = Y13_STRING_1
drums = HIPHOP_DUSTYGROOVE_017

fitMedia(electrostring, 1, 1, 9)
fitMedia(drum, 2, 5, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Finding Errors 3: Find and fix the error in this script

setTempo(88);

var electroString = Y13_STRING_1;
var drums = HIPHOP_DUSTYGROOVE_017;

fitMedia(electrostring, 1, 1, 9);
fitMedia(drum, 2, 5, 9);
----

[role="curriculum-python"]
The console clearly indicates an error in the first script. It throws a <<every-error-explained-in-detail#nameerror,name error>>, stating that the `electroString` variable is not defined. `electroString` is defined, but not until after we try to use it. Remember that all variables must be defined _before_ they are used.

[role="curriculum-javascript"]
The console clearly indicates an error in the first script. It throws a <<every-error-explained-in-detail#typeerror,type error>> on line 13, telling us that we used the wrong data type. The `electroString` variable is defined, but not until after we try to use it. Remember that all variables must be defined _before_ they are used.

A similar error message appears for the next script. The console points us to the line where we forgot a capital "S" in `electroString`. On the next line, we made another name error by referencing the non-existent `drum` variable instead of `drums`.

Corrected scripts are provided below for reference:

[role="curriculum-python"]
[source,python]
----
# Debugged: Errors fixed

from earsketch import *
setTempo(88)

electroString = Y13_STRING_1
drums = HIPHOP_DUSTYGROOVE_017

fitMedia(electroString, 1, 1, 9)
fitMedia(drums, 2, 5, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Debugged: Errors fixed

setTempo(88);

var electroString = Y13_STRING_1;
var drums = HIPHOP_DUSTYGROOVE_017;

fitMedia(electroString, 1, 1, 9);
fitMedia(drums, 2, 5, 9);
----

EarSketch provides some additional resources to help you debug your scripts. Take a look at <<every-error-explained-in-detail#,Every Error Explained in Detail>> for a description of different error types and what you can do to prevent them.

[[chapter3summary]]
=== Chapter 3 Summary

[role="curriculum-python"]
* *Debugging* is the process of finding and fixing *bugs*, errors made by the programmer.
* The three types of errors are *syntax errors*, *runtime errors*, and *logic errors*.
* *Syntax* rules define the arrangement of code for a particular programming language.
* The *console* shows information about the state of a program, making it useful for debugging syntax errors. If a program does not run, check the console for guidance.
* *Comments* make code easier to understand and help keep code organized. Inserting a `#` symbol at the start of a line *comments out* the line.
* Common beginner errors include typos, incorrect case, missing parentheses, lack of variable initialization, improper script setup, and improper commenting.

[role="curriculum-javascript"]
* *Debugging* is the process of finding and fixing *bugs*, errors made by the programmer.
* The three types of errors are *syntax errors*, *runtime errors*, and *logic errors*.
* *Syntax* rules define the arrangement of code for a particular programming language.
* The *console* shows information about the state of a program, making it useful for debugging syntax errors. If a program does not run, check the console for guidance.
* *Comments* make code easier to understand and help keep code organized. Inserting a two forward slashes, `//`,  at the start of line *comments out* the line.
* Common beginner errors include typos, incorrect case, missing parentheses, lack of variable initialization, improper script setup, and improper commenting.




[[chapter-questions]]
=== Questions

[question]
--
Which of the following is not a common type of error found in code?
[answers]
* Random Errors
* Runtime Errors
* Logic Errors
* Syntax Errors
--

[question]
--
What happens if your program has a Syntax Error?
[answers]
* The program does not run at all.
* The program runs, but doesn’t do what you expect.
* The program runs, but prints a warning to the console.
* The program runs at first, but eventually crashes.
--

