[[ch_32]]
== EarSketch Sound Library
:nofooter:

To find sounds that work well together in your music, choose them from the same folder. For example, pick all your sounds from `DUBSTEP_140_BPM` or all of them from `Y30_68_BPM_B_MINOR`.

To hear a sound, click the play button next to its name. To use a sound in EarSketch, click the paste button to paste the sound constant into your script at the current cursor position. To help you find sounds, you can search by keyword and you can filter by artist, genre, and instrument.

Most of the sound folders are labeled with a tempo. Tempo is the speed of music (how slow or fast). In EarSketch, you always specify the tempo of your song using the `setTempo` function. For example, `setTempo(120)` will set the tempo of your project at 120 beats per minute. Though not required, we suggest you set the tempo to match the original tempo of the sounds you choose. To find the original tempo, click on the tags button next to the sound.

As you get more comfortable creating music with EarSketch, you may want to experiment some more by combining sounds from several different folders in the same song and by trying out different tempos. When experimenting, use your musical ear to help you decide what sounds good and what doesn’t, and try a bunch of different possibilities to figure out what you like best.

Some of the sound folders also list a key for the sounds in that folder. For instance, the sounds in `Y57_87_BPM_G_MINOR` are in the key of G minor. In music, a key indicates a scale (like major or minor) and a particular “home” note (called the tonic) from which most of the pitches are drawn. So, if you want to combine sounds from two different folders (other than just drums), they are more likely to sound good together if they are in the same key.

The sounds in the EarSketch library come from several different sources. https://en.wikipedia.org/wiki/Richard_Devine[Richard Devine^] (a well-known sound designer and electronic musician) and https://en.wikipedia.org/wiki/Young_Guru[Young Guru^] (a Grammy-nominated DJ and audio engineer best known for his work with Jay-Z) each created about 2000 sounds specifically for EarSketch. Some additional sounds in the `MAKEBEAT` folder contains a collection of single drum hits suitable for use with EarSketch’s makeBeat function. These were created by Thom Jordan, a member of the EarSketch research team.

To add your own sounds to EarSketch, follow the instructions on our web site for <<making-custom-beats#>>. Your sounds will then be displayed in the `USER_SOUNDS` folder.
