[[ch_16]]
== Evaluating Correctness: Part Two
:nofooter:

The idea of correct and complete code was examined in <<evaluating-correctness#,Chapter 8>>. Here, we further extend the concept of correctness to improve the overall conciseness and clarity of a script.

[[conciseness]]
=== Conciseness

*Conciseness* means brief, but comprehensive, code that accomplishes its goal efficiently. We have seen some examples of improving conciseness in previous chapters. For-loops can replace repetitive `fitMedia()` and `makeBeat()` calls. Custom functions package up repetitive blocks of code, allowing the same code to be easily reused. It is still important to note that conciseness should not sacrifice completeness.

Here are some sample questions for determining a script's conciseness:

* Can parts of my code be written more efficiently?
* Did I copy/paste function calls several times in a row? (If so, simplify with a loop!)
* Am I reusing any blocks of code? (If so, put them in a function!)
* Are there sound constants or mathematical expressions that I use repeatedly throughout my code? (If so, assign them to variables!)

[[clarity]]
=== Clarity

*Clarity* relates to how well code communicates its function and the programmer's intent. Others are likely to read your code at some point. If your peers are getting lost or confused by your code, it is probably unclear. In EarSketch, we can improve clarity by using appropriate variable and function names and using computational structures like loops and custom functions. For example, the name of a for-loop counter variable should reflect its purpose, like `measure` or `track`, whenever possible. Although it will not affect musical output, it is most logical to write code in the order sounds will appear in the DAW. Commenting is also essential; comment on any logic that may be confusing or challenging to understand, and add a short description of what each block of code does to help the user determine program flow.

Here are some sample questions for determining the clarity of a script:

* How long did it take me to fully understand this code?
* Would someone else be able to understand what my code does?
* Are the names of my variables and functions descriptive?
* Have I used comments to explain each block of code and any potentially confusing lines of code?
* Have I used computational structures like custom functions and loops to help organize my code?
* Does the structure of my script mirror the structure of my song?

[[scriptheaders]]
=== Script Headers
The *script header* is an important part of every EarSketch script. It is broken into four sections: language, script name, author, and description. The purpose of a script header is simple; it helps the programmer and others understand the function and purpose of the script. The description section of the header should make clear the main goals and objectives of the script. In this way, it is useful for checking the correctness and completeness of your script (refer back to <<evaluating-correctness#,Chapter 8>>). If your output does not match the description, a reevaluation of correctness is needed.

Follow this template when writing your own script headers:

[role="curriculum-python"]
[source,python]
----
# title: [A meaningful title for your script]
# author: [Your name, or your team's name]
# description: [A brief, but detailed description of your program]
----

[role="curriculum-javascript"]
[source,javascript]
----
// title: [A meaningful title for your script]
// author: [Your name, or your team's name]
// description: [A brief, but detailed description of your program]
----

[[chapter16summary]]
=== Chapter 16 Summary

* *Concise* code is brief, but comprehensive, and accomplishes its goal efficiently. However, writing code that is concise should not come at the expense of completeness.
* *Clarity* is a measure of how well code communicates its function and intent, both to the programmer and peers.
* The EarSketch *script header* consists of four sections: language, script name, author, and description. Its purpose is to help the programmer and others understand the function and purpose of the script.
