[[ch_20]]
== Randomness
:nofooter:

Introducing randomness in music creates a sense of novelty, leading to a more improvisational feel. In this chapter, we turn some control over to the computer, allowing it to introduce elements of randomness into our music.

[[randomnumbers]]
=== Random numbers

[role="curriculum-python"]
A *random number* is a generated value that is impossible to predict. A random integer can be generated in Python with the `randint()` function. `randint()` is part of Python's random API, so we need to import it as part of our script setup. Just like we import the EarSketch API with `from earsketch import *`, the random API is imported with `from random import *`.

[role="curriculum-javascript"]
A *random number* is a generated value that is impossible to predict. A random number can be generated in JavaScript with the `random()` method. Its syntax is `Math.random()`, as it is part of a collection of utilities called `Math`.

[role="curriculum-python"]
`randint()` produces a random number within a range specified by its two arguments, `minimum` and `maximum`. _Both_ arguments are inclusive in this case. For example, `randint(1, 5)` would produce either 1, 2, 3, 4, or 5. These integers can be used for things like list indices, track numbers, or measure numbers.

[role="curriculum-javascript"]
`Math.random()` produces a random floating point number between 0 (inclusive) and 1 (exclusive). To obtain usable values, we scale this range by a multiplier, like `Math.random() * multiplier`. For example, `Math.random() * 5` would produce 0, 1, 2, 3, or 4. To convert this random floating point value to an integer, we call the method `Math.floor()`, which rounds its argument down to the nearest whole number. This way, the random value can be used as a list index, a track, or a measure number. The formula for generating random numbers in JavaScript is `Math.floor(Math.random() * multiplier)`.

[role="curriculum-python"]
In the example below, random numbers are used to pick random clips from a list. The range of random numbers generated is identical to the list indices. Using these clips in function calls produces musical variety each time the script runs.

[role="curriculum-javascript"]
In the example below, random numbers are used to pick random clips from an array. The range of random numbers generated is identical to the array indices. Using these clips in functions calls produces musical variety each time the script runs.

[role="curriculum-python"]
[source,python]
----
# Random Clip: Randomly selecting clips from a list

# Setup
from earsketch import *
from random import *  # need to import the random library to use randint()
setTempo(100)

# Music
sampleBank = [YG_TRAP_SYNTH_BELL_1,
              YG_TRAP_STRINGS_1,
              YG_TRAP_SHORT_SYNTH_1,
              YG_TRAP_HIT_1,
              YG_TRAP_SYNTH_LEAD_6,
              YG_TRAP_BELLS_1]

for i in range(1, 9):

    # Generates a random index number between 0 and 5 because the length of sampleBank list is 6 (total number of samples)
    index = randint(0, len(sampleBank) - 1)
    fitMedia(sampleBank[index], 1, i, i + 1)  # Use the random index to get a list element

fitMedia(YG_TRAP_KICK_4, 2, 1, 9)
fitMedia(YG_TRAP_BASS_1, 3, 1, 9)
fitMedia(YG_TRAP_SNARE_5, 4, 1, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Random Clip: Randomly selecting clips from an array

// Setup
setTempo(100);

// Music
var sampleBank = [
    YG_TRAP_SYNTH_BELL_1,
    YG_TRAP_STRINGS_1,
    YG_TRAP_SHORT_SYNTH_1,
    YG_TRAP_HIT_1,
    YG_TRAP_SYNTH_LEAD_6,
    YG_TRAP_BELLS_1,
];

for (var i = 1; i < 9; i++) {
    // Generates a random index number between 0 and 5 because the length of sampleBank array is 6 (total number of samples)
    var index = Math.floor(Math.random() * sampleBank.length);

    // Use the random index to pick a sample
    fitMedia(sampleBank[index], 1, i, i + 1);
}

fitMedia(YG_TRAP_KICK_4, 2, 1, 9);
fitMedia(YG_TRAP_BASS_1, 3, 1, 9);
fitMedia(YG_TRAP_SNARE_5, 4, 1, 9);
----

[[remixingarhythm]]
=== Remixing a Rhythm

Let's remix a popular rhythm, the amen break, by introducing a random drum pattern. The amen break is widely sampled in electronic music. The code for this particular rhythm is shown below. Two separate `makeBeat()` calls are used, one to handle the kick and snare, and the other for a series of cymbals. The beat strings used in these function calls are the result of concatenating a set of smaller substrings. This allows us to better understand the structure of the rhythm.

[role="curriculum-python curriculum-mp4"]
video::./videoMedia/020-02-RemixingaRhythm-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
video::./videoMedia/020-02-RemixingaRhythm-JS.mp4[]

[role="curriculum-python"]
[source,python]
----
# Amen Break: Constructing the amen break with string concatenation

# Setup
from earsketch import *
setTempo(140)

# Music
drums = [OS_KICK05, OS_SNARE06, Y24_HI_HATS_1, Y58_HI_HATS_1, OS_OPENHAT01]

a = "0+0-1+-1+1001+-1"
b = "0+0-1+-1-10---1+"
c = "-1001+-1+10---1+"
cym1 = "2+2+2+2+2+2+2+2+"
cym2 = "2+2+2+2+2+3+2+2+"
cym3 = "2+2+2+2+2+4+2+2+"

amenBreak = a + a + b + c
amenCymbals = cym1 + cym1 + cym2 + cym3

makeBeat(drums, 1, 1, amenBreak)
makeBeat(drums, 2, 1, amenCymbals)
----


[role="curriculum-javascript"]
[source,javascript]
----
// Amen Break: Constructing the amen break with string concatenation

// Setup
setTempo(140);

// Music
var drums = [OS_KICK05, OS_SNARE06, Y24_HI_HATS_1, Y58_HI_HATS_1, OS_OPENHAT01];

var a = "0+0-1+-1+1001+-1";
var b = "0+0-1+-1-10---1+";
var c = "-1001+-1+10---1+";
var cym1 = "2+2+2+2+2+2+2+2+";
var cym2 = "2+2+2+2+2+3+2+2+";
var cym3 = "2+2+2+2+2+4+2+2+";

var amenBreak = a + a + b + c;
var amenCymbals = cym1 + cym1 + cym2 + cym3;

makeBeat(drums, 1, 1, amenBreak);
makeBeat(drums, 2, 1, amenCymbals);
----

Next, a random drum pattern is added to the amen break. A for-loop is used to generate a random beat string. On each loop iteration, a random number is generated, converted to a string type, and concatenated with the new beat string. The range of the random numbers is set to match the indices of our drum samples. Check out the code snippet for this process below.

[role="curriculum-python"]
[source,python]
----
insertSection = ""

for i in range(8):
    insertSection = insertSection + str(randint(0, 4))
----

[role="curriculum-javascript"]
[source,javascript]
----
var insertSection = "";

for (var i = 0; i < 8; i++) {
    insertSection = insertSection + Math.floor(Math.random() * 5);
}
----

We want to introduce the random beat string without changing the total length of the amen break. Thus, substrings are required. The snippet below shows code to concatenate the randomly-generated string (which is 8 characters long) with the last 8 characters of the `a` beatString to create a new 16-character string. We then create the new amen break by concatenating `a`, `newA`, `b`, and `c` together.

[role="curriculum-python"]
[source,python]
----
newA = insertSection + a[8:16]
newBeat = a + newA + b + c
----

[role="curriculum-javascript"]
[source,javascript]
----
var newA = insertSection + a.substring(8, 16);
var newBeat = a + newA + b + c;
----

Adding the two code snippets above into the amen break script results in the following code. We have remixed the amen break!

[role="curriculum-python"]
[source,python]
----
# Amen Remix: Replacing part of the amen break string with a random beat string

# Setup
from earsketch import *
from random import *
setTempo(140)

# Music
drums = [OS_KICK05, OS_SNARE06, Y24_HI_HATS_1, Y58_HI_HATS_1, OS_OPENHAT01]

a = "0+0-1+-1+1001+-1"
b = "0+0-1+-1-10---1+"
c = "-1001+-1+10---1+"
cym1 = "2+2+2+2+2+2+2+2+"
cym2 = "2+2+2+2+2+3+2+2+"
cym3 = "2+2+2+2+2+4+2+2+"

amenBreak = a + a + b + c
amenCymbals = cym1 + cym1 + cym2 + cym3

insertSection = ""

for i in range(8):
    # building the random beat string, 8 characters long
    insertSection += str(randint(0, 4))

newA = insertSection + a[8:16]
newBeat = a + newA + b + c

makeBeat(drums, 1, 1, newBeat)
makeBeat(drums, 2, 1, amenCymbals)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Amen Remix: Replacing part of the amen break string with a random beat string

// Setup
setTempo(140);

// Music
var drums = [OS_KICK05, OS_SNARE06, Y24_HI_HATS_1, Y58_HI_HATS_1, OS_OPENHAT01];

var a = "0+0-1+-1+1001+-1";
var b = "0+0-1+-1-10---1+";
var c = "-1001+-1+10---1+";
var cym1 = "2+2+2+2+2+2+2+2+";
var cym2 = "2+2+2+2+2+3+2+2+";
var cym3 = "2+2+2+2+2+4+2+2+";

var amenBreak = a + a + b + c;
var amenCymbals = cym1 + cym1 + cym2 + cym3;

var insertSection = "";

for (var i = 0; i < 8; i++) {
    // building the random beat string, 8 characters long
    insertSection += Math.floor(Math.random() * 5);
}

var newA = insertSection + a.substring(8, 16);
var newBeat = a + newA + b + c;

makeBeat(drums, 1, 1, newBeat);
makeBeat(drums, 2, 1, amenCymbals);
----

[[chapter20summary]]
=== Chapter 20 Summary

[role="curriculum-python"]
* *Random numbers* generated within a program are impossible to predict.
* A random integer can be generated using Python's random API function `randint()`. This function takes two arguments, `minimum` and `maximum`, both of which are inclusive.

[role="curriculum-javascript"]
* *Random numbers* generated within a program are impossible to predict.
* A random integer can be generated using JavaScript's `Math` utility and `random()` method. The method produces floating point values between 0 and 1, so the output needs to be scaled by a multiplier. The full syntax is `Math.random() * multiplier`.

[[chapter-questions]]
=== Questions

[role="curriculum-python"]
[question]
--
What set of numbers will `randint(1,5)` choose a random number from?
[answers]
* `1, 2, 3, 4, 5`
* `1, 2, 3, 4`
* `2, 3, 4, 5`
* `1, 5`
--

[role="curriculum-python"]
[question]
--
In order to use EarSketch functions, we must include the EarSketch API by including `from earsketch import *`. What do we need to include to use `randint()` ?
[answers]
* `from random import *`
* `from earsketch2 import *`
* `from integer import *`
* `from randint import *`
--

[role="curriculum-javascript"]
[question]
--
What set of numbers will (Math.floor(Math.random() * 5)) choose a random number from?
[answers]
* `0, 1, 2, 3, 4`
* `0, 1, 2, 3`
* `1, 2, 3, 4`
* `0, 4`
--

