[[ch_6]]
== Tempo and Pitch
:nofooter:

It is often challenging to choose sounds that work together when composing in EarSketch. This chapter provides strategies for planning your composition, choosing sounds, and transitioning between musical ideas.

[[tempo]]
=== Tempo
*Tempo* is the speed at which a piece of music is played. It affects the duration of each beat. Tempo is specified in beats per minute (bpm) in Western music. In EarSketch, we set the tempo of our song at the top of each script with `setTempo()`.

Songs of different genres fall within particular tempo ranges, especially in electronic music. Choosing a tempo can help define the track's genre and where it will fit in a DJ set. The following tempos are typical of each of the following genres:

* Hip Hop: 85-95 bpm
* Pop: 118 bpm
* Techno: 120-125 bpm
* Electro: 128 bpm
* House: 115-130 bpm
* Dubstep and Trap: 140 bpm
* Drum & Bass: 160 - 180 bpm

The EarSketch Sound Library is organized into folders of related sounds, often by genre. Each sample's tempo reflects where it fits in the list of genres above. If you would like to know the exact tempo of the sample, hover over the clip's name in the Sound Browser.

Note that the sounds do not have to be used with their original tempos or genre labels; the listed tempos are not set in stone. Certain genres, like rock or classical, have drastically varying tempos across their catalog. As you get more comfortable with EarSketch, try mixing sounds from different genres and experimenting with tempo. EarSketch will automatically play back the sounds you select from the sound library at the tempo you choose in `setTempo()`. In the end, your ear is what determines what tempo sounds best.

////
Tempo Change Info could go here eventually.

BMW
////

[[pitch]]
=== Pitch
*Pitch* is a quality of sound that determines how high or low it sounds. Humans order relative musical tones on a *scale*, or set of musical notes, based on how they hear the frequency of the sound. This means pitch and frequency are related, but not synonymous. Pitch, duration, loudness, and timbre all factor into a complete musical tone.

The *key* of a song indicates the scale, or group of pitches, in which the music is composed. The key also specifies the home note, called the tonic, from which the pitches are drawn. Keys can be major or minor. Major keys tend to sound pleasant, while minor keys sound darker, although this is not always the case.

In general, sounds within the same folder in the EarSketch sound library are all in the same key, which helps you choose clips that sound good together. Your compositions do not need to be limited to a single folder; sometimes multiple sounds with related keys can be mixed.

Listen to the audio clip below to hear the difference between major and minor keys:

++++
<div class="curriculum-mp3">audioMedia/MajorMinor.mp3</div>
++++

[[transitionstrategies]]
=== Transition Strategies
*Transitions* are passages of music that combine neighboring musical sections. They can connect verse and chorus, build up to a drop, combine collaboratively written sections, mix between tracks (DJing), or change keys. The goal of a transition is to grab the listener's attention and let them know a change is about to occur. Following are some popular strategies for creating musical transitions:

. *Crash Cymbal*: Signaling a change by placing a crash cymbal on the first beat of a new section.
. *Drum Fill*: A rhythmic variation used to fill the gap before a new section of music.
. *Track Dropouts*: Making certain tracks temporarily drop out to create rests or pauses. This grabs the listener's attention because the ear is used to repetition.
. *Melody Variation*: Introduce a variation of the chords, bassline, or melody before the new section. Often, a folder within the EarSketch sound library contains variations of a similar riff. For example, notice the sounds under the UK_HOUSE_ARPLEAD folder.
. *Riser*: A sustained note or noise that increases in pitch. It is often paired with another transition technique and is extremely common in EDM music. Risers create an anticipation of a drop. EarSketch has a number of sounds labeled as risers; use the search term "riser" in the Sound Browser to check them out. A reversed crash cymbal can also be used as a riser, like YG_EDM_REVERSE_CRASH_1.

Drum fills are used throughout all genres of music, but are used notoriously in rock music. Check out the example below.

[role="curriculum-python"]
[source,python]
----
# Drum Fill: Transitioning with a drum fill

# Setup
from earsketch import *
setTempo(130)

# Music
leadGuitar1 = RD_ROCK_POPLEADSTRUM_GUITAR_4
leadGuitar2 = RD_ROCK_POPLEADSTRUM_GUITAR_9
bass1 = RD_ROCK_POPELECTRICBASS_8
bass2 = RD_ROCK_POPELECTRICBASS_25
drums1 = RD_ROCK_POPRHYTHM_DRUM_PART_10
drums2 = RD_ROCK_POPRHYTHM_MAINDRUMS_1
drumFill = RD_ROCK_POPRHYTHM_FILL_4

# Section 1
fitMedia(leadGuitar1, 1, 1, 8)
fitMedia(bass1, 2, 1, 8)
fitMedia(drums1, 3, 1, 8)

# Drum Fill
fitMedia(drumFill, 3, 8, 9)

# Section 2
fitMedia(leadGuitar2, 1, 9, 17)
fitMedia(bass2, 2, 9, 17)
fitMedia(drums2, 3, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Drum Fill: Transitioning with a drum fill

// Setup
setTempo(130);

// Music
var leadGuitar1 = RD_ROCK_POPLEADSTRUM_GUITAR_4;
var leadGuitar2 = RD_ROCK_POPLEADSTRUM_GUITAR_9;
var bass1 = RD_ROCK_POPELECTRICBASS_8;
var bass2 = RD_ROCK_POPELECTRICBASS_25;
var drums1 = RD_ROCK_POPRHYTHM_DRUM_PART_10;
var drums2 = RD_ROCK_POPRHYTHM_MAINDRUMS_1;
var drumFill = RD_ROCK_POPRHYTHM_FILL_4;

// Section 1
fitMedia(leadGuitar1, 1, 1, 8);
fitMedia(bass1, 2, 1, 8);
fitMedia(drums1, 3, 1, 8);

// Drum Fill
fitMedia(drumFill, 3, 8, 9);

// Section 2
fitMedia(leadGuitar2, 1, 9, 17);
fitMedia(bass2, 2, 9, 17);
fitMedia(drums2, 3, 9, 17);
----

The track dropout technique only requires the modification of a couple `fitMedia()` calls. An example is shown below.

[role="curriculum-python"]
[source,python]
----
# Dropouts: Transitioning between sections with selective muting

# Setup
from earsketch import *
setTempo(120)

# Music
introLead = TECHNO_ACIDBASS_002
mainLead1 = TECHNO_ACIDBASS_003
mainLead2 = TECHNO_ACIDBASS_005
auxDrums1 = TECHNO_LOOP_PART_025
auxDrums2 = TECHNO_LOOP_PART_030
mainDrums = TECHNO_MAINLOOP_019
bass = TECHNO_SUBBASS_002

# Section 1
fitMedia(introLead, 1, 1, 5)
fitMedia(mainLead1, 1, 5, 9)
fitMedia(auxDrums1, 2, 3, 5)
fitMedia(auxDrums2, 2, 5, 8)  # Drums drop out
fitMedia(mainDrums, 3, 5, 8)

# Section 2
fitMedia(mainLead2, 1, 9, 17)
fitMedia(auxDrums2, 2, 9, 17)  # Drums enter back in
fitMedia(mainDrums, 3, 9, 17)
fitMedia(bass, 4, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Dropouts: Transitioning between sections with selective muting

// Setup
setTempo(120);

// Music
var introLead = TECHNO_ACIDBASS_002;
var mainLead1 = TECHNO_ACIDBASS_003;
var mainLead2 = TECHNO_ACIDBASS_005;
var auxDrums1 = TECHNO_LOOP_PART_025;
var auxDrums2 = TECHNO_LOOP_PART_030;
var mainDrums = TECHNO_MAINLOOP_019;
var bass = TECHNO_SUBBASS_002;

// Section 1
fitMedia(introLead, 1, 1, 5);
fitMedia(mainLead1, 1, 5, 9);
fitMedia(auxDrums1, 2, 3, 5);
fitMedia(auxDrums2, 2, 5, 8); // Drums drop out
fitMedia(mainDrums, 3, 5, 8);

// Section 2
fitMedia(mainLead2, 1, 9, 17);
fitMedia(auxDrums2, 2, 9, 17); // Drums enter back in
fitMedia(mainDrums, 3, 9, 17);
fitMedia(bass, 4, 9, 17);
----

Keep in mind that a musical phrase sounds most natural when clips are arranged into groups of 2, 4, 8, 16, etc. This informs where a transition should be placed. In the example above, the first section occupies the first 8 measures and the second section occupies the next 8 measures. Therefore, we should place a transition right before the 9th measure, the start of the second section. Notice that the drums drop out briefly at measure 8, signaling a change to the listener.

An effective transition is not limited to a single technique. The next example uses multiple risers and a crash cymbal during the transition.

[role="curriculum-python"]
[source,python]
----
# Risers: Transitioning between sections using risers and a crash cymbal

# Setup
from earsketch import *
setTempo(128)

# Music
synthRise = YG_EDM_SYNTH_RISE_1
airRise = RD_EDM_SFX_RISER_AIR_1
lead1 = YG_EDM_LEAD_1
lead2 = YG_EDM_LEAD_2
kick1 = YG_EDM_KICK_LIGHT_1
kick2 = ELECTRO_DRUM_MAIN_LOOPPART_001
snare = ELECTRO_DRUM_MAIN_LOOPPART_003
crash = Y50_CRASH_2
reverseFX = YG_EDM_REVERSE_FX_1

# Section 1
fitMedia(lead1, 1, 1, 17)
fitMedia(kick1, 2, 9, 17)

# Transition
fitMedia(reverseFX, 3, 16, 17)
fitMedia(synthRise, 4, 13, 17)
fitMedia(airRise, 5, 13, 17)
fitMedia(crash, 6, 17, 19)

# Section 2
fitMedia(lead2, 1, 17, 33)
fitMedia(kick2, 7, 25, 33)
fitMedia(snare, 8, 29, 33)

# Effects
setEffect(1, VOLUME, GAIN, 0, 16, 1, 17)  # Adjusting volumes for better matching
setEffect(4, VOLUME, GAIN, -10)
setEffect(7, VOLUME, GAIN, -20)
setEffect(8, VOLUME, GAIN, -20)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Risers: Transitioning between sections using risers and a crash cymbal.

// Setup
setTempo(128);

// Music
var synthRise = YG_EDM_SYNTH_RISE_1;
var airRise = RD_EDM_SFX_RISER_AIR_1;
var lead1 = YG_EDM_LEAD_1;
var lead2 = YG_EDM_LEAD_2;
var kick1 = YG_EDM_KICK_LIGHT_1;
var kick2 = ELECTRO_DRUM_MAIN_LOOPPART_001;
var snare = ELECTRO_DRUM_MAIN_LOOPPART_003;
var crash = Y50_CRASH_2;
var reverseFX = YG_EDM_REVERSE_FX_1;

// Section 1
fitMedia(lead1, 1, 1, 17);
fitMedia(kick1, 2, 9, 17);

// Transition
fitMedia(reverseFX, 3, 16, 17);
fitMedia(synthRise, 4, 13, 17);
fitMedia(airRise, 5, 13, 17);
fitMedia(crash, 6, 17, 19);

// Section 2
fitMedia(lead2, 1, 17, 33);
fitMedia(kick2, 7, 25, 33);
fitMedia(snare, 8, 29, 33);

// Effects
setEffect(1, VOLUME, GAIN, 0, 16, 1, 17); // Adjusting volumes for better matching
setEffect(4, VOLUME, GAIN, -10);
setEffect(7, VOLUME, GAIN, -20);
setEffect(8, VOLUME, GAIN, -20);
----

[[chapter6summary]]
=== Chapter 6 Summary

* *Tempo* is the speed at which a piece of music is played, specified in beats per minute (bpm). Tempo is tied to genre; often different genres adhere to a particular tempo range.
* The clips in the EarSketch Sound Library are organized into folders of related sounds. To see the exact tempo of a clip, hover over the name in the Sound Browser.
* The *pitch* of a sound determines how high or low it sounds on a relative scale.
* The *key* of a song defines the *scale*, or group of pitches, in which the piece is composed, as well as the *tonic* note. Keys are either major or minor, which tend to give a different impression to the listener.
* *Transitions* are passages of music used to connect consecutive musical sections, resulting in a natural sounding piece.

[[chapter-questions]]
=== Questions

[question]
--
What does `setTempo()` allow you to do in EarSketch?
[answers]
* Specify the tempo of a song
* Add a sound to a track
* Create a drum beat
* Change the qualities of sound within a project
--

[question]
--
____ is a quality of sound that determines how high or low it sounds.
[answers]
* Pitch
* Tempo
* Rhythm
* Transition
--

[question]
--
Which of these is NOT an example of a transition?
[answers]
* Melody Consistency
* Crash Cymbal
* Riser
* Track Dropouts
--
