[[mixingwithconditionnals]]
== למקסס עם תנאים!
:nofooter:

בתכנות, אפשר להפוך דברים לאוטומטיים. דוגמה לאוטומציה היא תכנות רובוט לעצור כשהוא מבחין במכשול: הרובוט לא זקוק לבן-אדם שיורה לו לעצור. לרובוט יש חיישן שמזהה מכשולים, וכשהוא נתקל במכשול הוא עוצר. אפשר לעשות אוטומציות מוסיקליות ב-EarSketch, תוך שימוש בתנאים (הוראות if). נראה כיצד להפוך את ערבול הערוצים (mixing) לאוטומטי. משמעותו של הערבול היא שאם הערוץ בעצמה (ווליום) גבוהה מדי נקטין את עצמתו, ואם הוא שקט מדי נגביר אותה.


[[analyzetrack]]
=== השימוש ב-`()analyzeTrack`

נלמד כיצד לקבוע מהי עצמת (ווליום) הערוץ. ודאו שההבדל בין עצמה (ווליום) וגובה (pitch) ברור ומובן. נשתמש בפונקציה שנקראת `()analyzeTrack`. העתיקו והריצו את הקוד הבא:

[role="curriculum-python"]
[source,python]
----
# analyzeTrack(): Using the analyzeTrack() function to print the loudness of a track

# Setup
from earsketch import *
setTempo(120)

# Placing a sound on track 1
sound = COMMON_LOVE_VOX_COMMON_1
fitMedia(sound, 1, 1, 9)

# Creating a variable to store the loudness of track 1
loudness1 = analyzeTrack(1, RMS_AMPLITUDE)

# Showing the loudness in the console
print(loudness1)
----

[role="curriculum-javascript"]
[source,javascript]
----
// analyzeTrack(): Using the analyzeTrack() function to print the loudness of a track

// Setup
setTempo(120);

// Placing a sound on track 1
var sound = COMMON_LOVE_VOX_COMMON_1;
fitMedia(sound, 1, 1, 9);

// Creating a variable to store the loudness of track 1
var loudness1 = analyzeTrack(1, RMS_AMPLITUDE);

// Showing the loudness in the console
println(loudness1);
----


בקונסול הודפס שהעצמה היא 0.0967737948641.

* העצמה יכולה לקבל ערכים מ-0 (שקט מוחלט) ל-1 (ווליום מקסימלי). 
* לפעמים המספר יכול להראות כך: 1.74630733714e-05. זה נקרא תצוגה מדעית. מה משמעות  ה-e-05 בסוף? משמעותו שיש לכתוב חמישה אפסים לפני המספר 17. כלומר, המספר הוא: 0.0000174630733714. 
* לרוב הצלילים עצמה הקטנה מ-0.4. 

לפונקציה`()analyzeTrack` שני פרמטרים:
* מספר הערוץ,
* הגודל אותו נרצה לדעת. עבור עצמה פרמטר התכונה הוא: `RMS_AMPLITUDE`.

.תרגלו
****
. הריצו את הקוד עם צלילים שונים (שנו את ערך המשתנה "sound"), ובדקו את עצמתם.
. הוסיפו ערוץ שני, ובעזרת הפונקציה `()analyzeTrack` הדפיסו את עצמתו בקונסול. לפני הרצת הקוד, האזינו לצלילים, ונסו לנחש למי משניהם ווליום חזק יותר.
****

פרמטר התכונה של `()analyzeTrack` יכול להיות `RMS_AMPLITUDE`, כדי לחשב את העצמה, או `SPECTRAL_CENTROID` כדי לחשב את בהירות הצליל. בפרק זה נתמקד בניתוח העצמה.

[[booleansandcomparisons]]
=== ביטויים בוליאניים והשוואות

כעת נראה כיצד *לוגיקה בוליאנית* עובדת, היא תעזור לנו להפוך משימות לאוטומטיות.

[role="curriculum-python"]
*ערכים בוליאניים (Booleans)* הם טיפוס נתונים. לטיפוס נתונים זה שני ערכים אפשריים, `True` ו-`False` (אמת ושקר). `True` ו-`False` מתחילות באות גדולה ולא מוקפות במירכאות.

[role="curriculum-javascript"]
*ערכים בוליאניים (Booleans)* הם טיפוס נתונים. לטיפוס נתונים זה שני ערכים אפשריים, `true` ו-`false` (אמת ושקר). `true` ו-`false` מתחילים באות קטנה ולא מוקפות במירכאות.

[role="curriculum-python"]
--
כדי ליצור משתנה בוליאני, אפשר לאתחל משתנה (`variable1 = True`), או להשתמש בהשוואה. כדי ליצור השוואה, נשתמש ב*אופרטור השוואה*. להלן האופרטורים להשוואה:
[cols="^h,1"]
|===
|==
| זהה ל...
|=!
| לא זהה ל...
|<
| גדול מ...
|=<
| גדול מ... או שווה לו
|>
| קטן מ...
|\=>
| קטן מ... או שווה לו
|===
--

[role="curriculum-javascript"]
--
כדי ליצור משתנה בוליאני, אפשר לאתחל משתנה (`var variable1 = true`), או להשתמש בהשוואה. כדי ליצור השוואה, נשתמש ב*אופרטור השוואה*. להלן האופרטורים להשוואה:
[cols="^h,1"]
|===
| ==
| זהה ל...
|=!
| לא זהה ל...
|<
| גדול מ...
|=<
| גדול מ... או שווה לו
|>
| קטן מ...
|\=>
| קטן מ... או שווה לו
|===
--

שימו לב להבדל בין:
1. השוואה בין שני ערכים כדי לבדוק האם הם זהים: `==`
2. הצבת ערך במשתנה: `=`

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/Screencast-Ch17-2-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/Screencast-Ch17-2-JS.mp4[]

// this video will be cut at 2' to delete the section about boolean operators//


[role="curriculum-python"]
.תרגלו
****
* צרו סקריפט חדש, והוסיפו צלילים בשני ערוצים.
* הדפיסו `True` אם הערוץ הראשון בעל עוצמה גבוהה יותר מאשר הערוץ השני, והדפיסו`False` אחרת.
* השתמשו בלולאת for עם המונה `track` כדי לבדוק, לכל ערוץ, האם עצמתו גדולה מ-0.01. אם כן, הדפיסו `True`, אחרת, הדפיסו `False`.
* תוכלו להוסיף הוראת הדפסה לפני הדפסת`True` או `False` כך שכשתקראו את מה שהודפס בקונסול, תדעו מה `True` או`False`.
****

[role="curriculum-javascript"]
.תרגלו
****
* צרו סקריפט חדש, והוסיפו צלילים בשני ערוצים.
* הדפיסו `true` אם הערוץ הראשון בעל עוצמה גבוהה יותר מאשר הערוץ השני, והדפיסו`talse` אחרת.
* השתמשו בלולאת for עם המונה `track` כדי לבדוק, לכל ערוץ, האם עצמתו גדולה מ-0.01. אם כן, הדפיסו `true`, אחרת, הדפיסו `false`.
* תוכלו להוסיף הוראת הדפסה לפני הדפסת`true` או `false` כך שכשתקראו את מה שהודפס בקונסול, תדעו מה `true` או`false`.
****

הנה דוגמה:

[role="curriculum-python"]
[source,python]
----
# Boolean Example: We analyze the loudness of our tracks

# Setup
from earsketch import *
setTempo(120)

# Creating 2 tracks
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 2, 1, 9)

# Evaluating the loudness of the tracks
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)

# Checking if track 1 is louder than track 2
# We create the boolean comparison1
comparison1 = loudnessTrack1 > loudnessTrack2
print("Is Track 1 louder than track 2?")
print(comparison1)

# Creating a for loop to compare each track's loudness to 0.5
for track in range(1, 3):
    loudness = analyzeTrack(track, RMS_AMPLITUDE)
    print("Is track number " + str(track) + " greater than 0.01?")
    print(loudness > 0.01)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Boolean Example: We analyze the loudness of our tracks
// Setup
setTempo(120);

// Creating 2 tracks
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 2, 1, 9);

// Evaluating the loudness of the tracks
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);

// Checking if track 1 is louder than track 2
// We create the boolean comparison1
var comparison1 = (loudnessTrack1 > loudnessTrack2);
println("Is Track 1 louder than track 2?");
println(comparison1);

// Creating a for loop to compare each track's loudness to 0.5
for (var track = 1; track < 3; track++) {
    var loudness = analyzeTrack(track, RMS_AMPLITUDE);
    println("Is track number " + track + " greater than 0.01?");
    println(loudness > 0.01);
}
----

[role="curriculum-python"]
שימו לב: בדוגמה זו, השתמשנו במספר הוראות print עם מחרוזות כדי לסייע בקריאת תוכן הקונסול. השתמשנו באופרטור`+` כדי *לשרשר*, או לחבר מחרוזות, ובפונקציה ()str כדי להמיר מספרים למחרוזות.

[role="curriculum-javascript"]
שימו לב: בדוגמה זו, השתמשנו במספר הוראות print עם מחרוזות כדי לסייע בקריאת תוכן הקונסול. השתמשנו באופרטור`+` כדי *לשרשר*, או לחבר מחרוזות.

[[conditionalstatements]]
=== הוראות תנאי

מהי הוראת תנאי? *הוראה* היא מה שהמחשב מבצע. *הוראת תנאי* היא הוראה שמתבצעת אם, ורק אם, *תנאי* מסוים מתקיים. למשל, אם נתכנת רובוט לעצור כשהוא לפני מכשול, התנאי יהיה "האם יש לפני הרובוט מכשול?". אם יש, עצור. אם אין, המשך בפעולה.

להלן דוגמה להוראת תנאי. שימו לב לדמיון ללולאת for:

[role="curriculum-python"]
[source,python]
----
if condition:
    # Here write the instructions the computer needs to execute if the condition evaluates to True
    # Note that the instructions are indented, just like in for loops
----

[role="curriculum-javascript"]
[source,javascript]
----
if (condition) {
    // Here write the instructions the computer needs to execute if the condition evaluates to true
    // Note that the instructions are indented, just like in for loops
}
----

.תרגלו
****
* צרו סקריפט חדש עם שני ערוצים.
* אם אחד הערוצים בעצמה גבוהה יותר מעצמת הערוץ האחר, הקטינו את הווליום שלו. השתמשו בפונקציות`()analyzeTrack`ו-`()setEffect`, וב-if.
* הגדירו הגבר שלילי (בין 1- ל-60dB-) כדי להקטין את העצמה. 
****

הנה דוגמה:
[role="curriculum-python"]
[source,python]
----
# Automatic mixing 1: If track 1 is louder than track 2, we'll reduce its volume

# Setup
from earsketch import *
setTempo(120)

# Creating 2 tracks
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 2, 1, 9)

# Evaluating the loudness of the tracks
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)

# If track 1 is louder than track 2, we reduce its volume
if loudnessTrack1 > loudnessTrack2:
    setEffect(1, VOLUME, GAIN, -10)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Automatic mixing 1: If track 1 is louder than track 2, we'll reduce its volume

// Setup
setTempo(120);

// Creating 2 tracks
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 2, 1, 9);

// Evaluating the loudness of the tracks
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);

// If track 1 is louder than track 2, we reduce its volume
if (loudnessTrack1 > loudnessTrack2) {
    setEffect(1, VOLUME, GAIN, -10);
}
----
לפעמים נדרש לבדוק מספר תנאים ולבצע בלוקים שונים של קוד, בהתאם לערכי התנאים. אפשר להוסיף כמה תנאים שצריך. יש להשתמש בתחביר (syntax) הבא:

[role="curriculum-python"]
[source,python]
----
if condition1:
    # Here write the instructions the computer needs to execute if the condition1 evaluates to True. If it's False, move to the next line
elif condition2:
    # Here write the instructions if condition2 is True. If condition2 is False, move to the next line
elif condition3:
    # Here write the instructions if condition3 is True. If condition3 is False, move to the next line
else:
    # Here write the instructions in case all 3 conditions are False
----

[role="curriculum-javascript"]
[source,javascript]
----
if (condition1) {
    // Here write the instructions the computer needs to execute if the condition1 evaluates to true
} else if (condition2) {
    // Here write the instructions if condition2 is True. If condition2 is False, move to the next line
    // elif is short for else if
} else if (condition3) {
    // Here write the instructions if condition3 is True. If condition3 is False, move to the next line
} else {
    // Here write the instructions in case all 3 conditions are False
}
----

[[mixingyourtracks]]
=== ערבול (מיקסוס)

נוכל להשתמש בכל הכלים האלה כדי למקסס שיר. למקסס, פירושו לשנות את עצמת הערוצים כל שישמעו מאוזנים (balanced). 

[role="curriculum-python"]
.תרגלו
****
* צרו סקריפט חדש.
* הוסיפו קליפים בשלושה ערוצים לפחות ולאורך 16 תיבות לפחות.
* השתמשו בפונקציה `()makeBeat`ובלולאת for כדי להוסיף כלי הקשה.
* בחרו את הערוץ "המרכזי". הוא יכול להיות ערוץ המלודיה או ערוץ אחר שתרצו להדגיש.
* אם עצמתו לא גדולה מעצמת הערוצים האחרים, הגבירו את עצמתו בעזרת הפונקציה `setEffect()`. התעלמו מערוץ כלי ההקשה, כי `()analyzeTrack` לא רלבנטי לכלי הקשה. `()analyzeTrack` מחזירה ממוצע, בעוד כלי הקשה מנגנים בפרצי צלילים, כך שממוצע לא מודד, באמת, את העצמה.
* השתמשו ב-print כדי להציג בקונסול את התהליך. הנה הוראת print לדוגמה: `print('Is track number' + str(track) + 'greater than 0.01?')`, אם המונה `track`שווה ל-`1`, יודפס 'Is track number 1 greater than 0.01?'. הפונקציה`()str`ממירה מספר (לדוגמה: 1) למחרוזת (לדוגמה: '1').
****

[role="curriculum-javascript"]
.תרגלו
****
* צרו סקריפט חדש.
* הוסיפו קליפים בשלושה ערוצים לפחות ולאורך 16 תיבות לפחות.
* השתמשו בפונקציה `()makeBeat`ובלולאת for כדי להוסיף כלי הקשה.
* בחרו את הערוץ "המרכזי". הוא יכול להיות ערוץ המלודיה או ערוץ אחר שתרצו להדגיש.
* אם עצמתו לא גדולה מעצמת הערוצים האחרים, הגבירו את עצמתו בעזרת הפונקציה `()setEffect`. התעלמו מערוץ כלי ההקשה, כי `()analyzeTrack` לא רלבנטי לכלי הקשה.
* השתמשו ב-print כדי להציג בקונסול את התהליך. הנה הוראת print לדוגמה: `print('Is track number' + str(track) + 'greater than 0.01?')`, אם המונה `track`שווה ל-`1`, יודפס 'Is track number 1 greater than 0.01?'.
****


נעשה חזרה קצרה על מספר מושגים: *אופרטור*: תו (או מספר תווים) שמייצג פעולה. We have seen arithmetic operators (`+`, `-`, `\*`, `=`) and comparison operators (`>`, `>=`, `<`, `\<=`, `==`, `!=`).
2. *ביטוי*: שילוב של ערכים, קבועים, משתנים, אופרטורים ופונקציות. המחשב מחשב את ערך הביטוי כדי לקבל תוצאה. בדרך כלל ערך הביטוי הוא ערך מספרי או בוליאני יחיד.  For example: `1+2` (evaluated to 3) or `1<2` (evaluated to True) or `analyzeTrack(1,RMS_AMPLITUDE)` (evaluated to the loudness of track 1, a float between 0 and 1).
3. *הוראות*: פקודות שעל המחשב לבצע.


למטה יש דוגמה של מיקסוס אוטומטי. המיקסוס אוטומטי במובן זה שאפשר לשנות צלילים, בלי שיהיה צורך לבדוק את העצמה שלהם ולשנות ווליום בהתאם ידנית. הקוד יעשה זאת אוטומטית.

[role="curriculum-python"]
[source,python]
----
# Automatic Mixing 2: Using conditional statements to mix the tracks

# Setup
from earsketch import *
setTempo(120)

# Adding a melody and bass
melody1 = YG_ALT_POP_GUITAR_3
melody2 = YG_ALT_POP_GUITAR_1
bass1 = YG_ALT_POP_BASS_1
bass2 = DUBSTEP_SUBBASS_008
strings = YG_HIP_HOP_STRINGS_4
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 1, 9, 17)
fitMedia(bass1, 2, 1, 9)
fitMedia(bass2, 2, 9, 17)
fitMedia(strings, 3, 9, 17)

# Adding percussion using makeBeat()
beatKick = "0---0-----0-0---"
beatSnare = "--0-0------000-"
soundKick = OS_KICK02
soundSnare = OS_SNARE06
for measure in range(5, 17):
    makeBeat(soundKick, 4, measure, beatKick)
    makeBeat(soundSnare, 5, measure, beatSnare)

# Mixing my tracks
# First, we analyze the tracks for loudness
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
print("The loudness of track 1 is" + str(loudnessTrack1))
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)
print("The loudness of track 2 is" + str(loudnessTrack2))
loudnessTrack3 = analyzeTrack(3, RMS_AMPLITUDE)
print("The loudness of track 3 is" + str(loudnessTrack3))

if loudnessTrack1 < loudnessTrack2:
    # if track 1 is quieter than track 2 then we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5)
    print("track 1 was quieter than track 2")
elif loudnessTrack1 < loudnessTrack3:
    # if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5)
    print("track 1 was quieter than track 3")
else:
    # if track 1 is louder than tracks 2 and 3, then we change nothing
    print("track 1 was the loudest track already")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Automatic Mixing 2: Using conditional statements to mix the tracks

// Setup
setTempo(120);

// Adding a melody and bass
var melody1 = YG_ALT_POP_GUITAR_3;
var melody2 = YG_ALT_POP_GUITAR_1;
var bass1 = YG_ALT_POP_BASS_1;
var bass2 = DUBSTEP_SUBBASS_008;
var strings = YG_HIP_HOP_STRINGS_4;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 1, 9, 17);
fitMedia(bass1, 2, 1, 9);
fitMedia(bass2, 2, 9, 17);
fitMedia(strings, 3, 9, 17);

//  Adding percussion using makeBeat()
var beatKick = "0---0-----0-0---";
var beatSnare = "--0-0------000-";
var soundKick = OS_KICK02;
var soundSnare = OS_SNARE06;
for (var measure = 5; measure > 17; measure++) {
    makeBeat(soundKick, 4, measure, beatKick);
    makeBeat(soundSnare, 5, measure, beatSnare);
}

// Mixing my tracks
// First, we analyze the tracks for loudness
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
println("The loudness of track 1 is" + loudnessTrack1);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);
println("The loudness of track 2 is" + loudnessTrack2);
var loudnessTrack3 = analyzeTrack(3, RMS_AMPLITUDE);
println("The loudness of track 3 is" + loudnessTrack3);

if (loudnessTrack1 < loudnessTrack2) {
    // if track 1 is quieter than track 2 then we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5);
    println("track 1 was quieter than track 2");
} else if (loudnessTrack1 < loudnessTrack3) {
    // if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5);
    println("track 1 was quieter than track 3");
} else {
    // if track 1 is louder than tracks 2 and 3, then we change nothing
    println("track 1 was the loudest track already");
}
----


[[chapter6summary]]
=== סיכום פרק שישי

[role="curriculum-python"]
* לפונקציה`()analyzeTrack` שני פרמטרים: מספר הערוץ והתכונה אותה נרצה לבדוק. כשהפרמטר השני הוא`RMS_AMPLITUDE`, הפונקציה תחזיר את עצמת הערוץ (מספר בין 0 ל-1). כשהפרמטר השני הוא`SPECTRAL_CENTROID`, הפונקציה תחזיר את בהירות הערוץ.
* לטיפוס הנתונים *boolean* יש רק שני ערכים אפשריים, `True` ו-`False`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` מחשב האם שני הערכים שווים, בעוד `=` מציב ערך במשתנה.
* *אופרטור* הוא תו (או מספר תווים) המייצג פעולה.
* *ביטויים* מחושבים על-ידי המחשב כדי לקבל את ערכם.
* *הוראה (statement)* היא פקודה לביצוע על-ידי המחשב.
* *תנאי* הוא ביטוי שערכו יכול להיות `True` או `False`. 
* הוראת _if_ מבצעת את בלוק הקוד שלה אם, ורק אם, ערך התנאי שלה הוא `True`. 
* אם בהוראת _if_ ערך התנאי הוא`False`, הוראת _else_ אופציונלית, מאפשרת לבלוק קוד אלטרנטיבי להתבצע.

[role="curriculum-javascript"]
* לפונקציה`()analyzeTrack` שני פרמטרים: מספר הערוץ והתכונה אותה נרצה לבדוק. כשהפרמטר השני הוא`RMS_AMPLITUDE`, הפונקציה תחזיר את עצמת הערוץ (מספר בין 0 ל-1). כשהפרמטר השני הוא`SPECTRAL_CENTROID`, הפונקציה תחזיר את בהירות הערוץ.
* לטיפוס הנתונים *boolean* יש רק שני ערכים אפשריים, `true` ו-`false`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` מחשב האם שני הערכים שווים, בעוד `=` מציב ערך במשתנה.
* *אופרטור* הוא תו (או מספר תווים) המייצג פעולה.
* *ביטויים* מחושבים על-ידי המחשב כדי לקבל את ערכם.
* *הוראה (statement)* היא פקודה לביצוע על-ידי המחשב.
* *תנאי* הוא ביטוי שערכו יכול להיות `true` או `false`.
* הוראת _if_ מבצעת את בלוק הקוד שלה אם, ורק אם, ערך התנאי שלה הוא `true`.
* אם בהוראת _if_ ערך התנאי הוא`false`, הוראת _else_ אופציונלית, מאפשרת לבלוק קוד אלטרנטיבי להתבצע.


[[chapter-questions]]
=== שאלות

[question]
--
מי מהביטויים הבאים הוא בוליאני?
[answers]
* `5+4 == 5`
* `measure = 1`
* `2<3<4`
* `()False`
--

[role="curriculum-python"]
[question]
--
מה יהי הפלט של קטע הקוד הבא (כלומר, מה הוא ידפיס לקונסול)?
[source,python]
----
n = 5
if (n * 3) == 15:
    print(n + 5)
else:
    print(n)
----
[answers]
* 10
* 5
* True
* False
--

[role="curriculum-javascript"]
[question]
--
מה יהי הפלט של קטע הקוד הבא (כלומר, מה הוא ידפיס לקונסול)?
[source,javascript]
----
var n = 5;
if (n * 3 == 15) {
    println(5 + n);
} else {
    println(n);
}
----
[answers]
* 10
* 5
* True
* False
--

[question]
--
מה זה mixing?
[answers]
* התאמת הווליום של כל ערוץ כך שהם ישמעו מאוזנים (balanced)
* התאמת גובה הצלילים בכל ערוץ כך שהם ישמעו מאוזנים (balanced)
* הוספת fade in
* הוספת fade out
--

[question]
--
כמה תנאים ניתן לבדוק בהוראת תנאי?
[answers]
* כל מספר של תנאים
* תנאי אחד
* שני תנאים
* שלושה תנאים
--
