[[customizeyourfirstsong]]
== שנו, לפי טעמכם/ן, את השיר הראשון שלכן/ם
:nofooter:

בפרק זה תלמדו איך לשנות את הקצב של השיר שלכם, להוסיף הערות לקוד ולטעון צלילים משלכם כדי להדגיש את המסר של השיר.

[[settempo]]
=== הפונקציה `()setTempo`

[role="curriculum-python"]
--
בוודאי כבר שמתם לב לכך, שכאשר אתם יוצרים סקריפט חדש, יש אלמנטים עליהם עליכם לשמור כדי שהקוד שלכם ירוץ:

. יש הערות שמתחילות ב-`#` באפור: נדון בהן בסעיף הבא
. השורה `*from earsketch import`, שמוסיפה פונקציות (כמו `()fitMedia`) לפרויקט
. הפונקציה `setTempo(120)` בה נדון בפירוט בהמשך
--

[role="curriculum-javascript"]
--
בוודאי כבר שמתם לב לכך, שכאשר אתם יוצרים סקריפט חדש, יש אלמנטים עליהם עליכם לשמור כדי שהקוד שלכם ירוץ:

. יש הערות שמתחילות ב-`//` באפור: נדון בהן בסעיף הבא
. הפונקציה `setTempo(120)` בה נדון בפירוט בהמשך
--

הפונקציה `()setTempo` קובעת את המהירות של השיר. *tempo* (בעברית: מפעם) מציין במוזיקה המערבית, את מספר הפעימות לדקה (bpm). ב-EarSketch ערך ברירת המחדל של הטמפו (כלומר, הערך הראשוני של המפעם) הוא 120bpm, שמתואם להליכה מהירה או מהירות צעידה. כדי לשנות את הטמפו, שנו את הערך שבסוגריים של הפונקציה `()setTempo`. ככל שהטמפו יותר גבוה, המוסיקה יותר מהירה. מותר להציב בפונקציה ערכים בין 45 ל-220.

.תרגלו
****
. צרו סקריפט חדש, 
. מקמו שני צלילים בשני ערוצים שונים,
. שנו את הטמפו והאזינו לשיר,
. השמיעו, לחבר/ה, את השיר בשלושה ערכי טמפו שונים. בקשו מהחבר/ה לדרג את השירים לפי הטמפו, מהנמוך לגבוה.
****

סוגה (ז'אנר) היא קטגוריה של יצירה אומנותית (לדוגמה: מוסיקה) שמאופיינת בדמיון בצורה, בסגנון ובתוכן. לסוגות שונות של מוזיקה אלקטרונית טווחים שונים של טמפו אופייני. לדוגמה:

[cols="^3*"]
|===
|סוגה|BPM|דוגמה

|Hip Hop
|85-95
|Coolio - Gangsta's Paradise (feat. L.V.)
|Pop (פופ)
|110-130
|Lizzo - Juice 
|Techno
|120-125
|Boris Brejcha - Schleierwolken
|Electro (אלקטרו)
|100-130
|Apashe - Behind My Eyes (feat. LIA)
|House (האוס)
|115-130
|DJ Breezy - Kimpinstik (feat. Dahlin Gage & Medikal)
|Dubstep and Trap (דאבסטפ אנד טראפ)
|140-150
|Jessica Audiffred & Walshy Fire - Stupid Love (feat. Nia V)
|Drum & Bass (דראם אנ'בייס)
|160-180
|Mollie Collins - Lost & Found
|===

.תרגלו
****
. בחרו אמן או אמנית שאתם מאוד אוהבים. בררו לאיזו סוגה (ז'אנר) הוא/היא שייכים.
. חפשו את הסוגה הזו (ב-Soundcloud או באתר דומה) והקשיבו למספר קטעי שירים מסוגה זו.
. נסו למצוא קווי דמיון בין השירים.
. אתם יכולים לחקור וללמוד על סוגה זו בעזרת וויקיפדיה ומקורות אחרים.
****
 
שימו לב לכך שקליפ יכול להישמע אחרת כשאתם שומעים אותו כמו שהוא וכשהוא משולב בשיר שלכם. סיבה אפשרית לכך היא שהטמפו של הקליפ שונה מהטמפו של השיר שלכם. כדי לדעת מהו הטמפו של קליפ בספרית הצלילים, עברו עם העכבר מעל השם שלו ברשימה. תוכלו לשנות את הטמפו של השיר שלכם לטמפו של הקליפ או לבחור קליפ אחר שמתאים לטמפו של השיר שלכם.


[[comments]]
=== הוספת הערות לקוד

[role="curriculum-python"]
*הערות* הן שורות קוד שלא מבוצעות על-ידי המחשב. הן משמשות אותנו, בני-אדם, להפיכת הקוד לקריא ומובן, לארגון הקוד וכדי לכתוב תזכורות לשימוש עתידי. Iבפייתון, הערות הן שורות המתחילות בסולמית `#`. 

[role="curriculum-javascript"]
*הערות* הן שורות קוד שלא מבוצעות על-ידי המחשב. הן משמשות אותנו, בני-אדם, להפיכת הקוד לקריא ומובן, לארגון הקוד וכדי לכתוב תזכורות לשימוש עתידי. ב-JavaScript, הערות הן שורות המתחילות בשני "סלאשים" `//`.

שימו לב לכך ששורות הפתיחה בכל סקריפט הן הערות המתארות את הסקריפט. בכל סקריפט שתכתבו, יהיה עליכם/ן למלא שורות אלה בהערות המתאימות. זה מקל על מתכנתים אחרים להבין על מה הקוד שלכם.

.תרגלו
****
בסקריפט שאתם/ן עובדים/ות עליו, מלאו את הפרטים הבאים בהערות בתחילת הקוד:

. שם הסקריפט: שם השיר
. המחבר: השם שלכם/ן
. תיאור: תיאור קצר של הפרויקט
****

אפשר להשתמש בהערות כדי לציין מה עושים חלקים שונים בקוד. הנה דוגמה. אפשר להריץ את הקוד. שימו לב שההערות מתארות את החלקים השונים בקוד:

[role="curriculum-python"]
[source,python]
----
# Comments: Using comments to describe what the code does

# Setup
from earsketch import *
setTempo(130)

# Music
# Leads
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9)
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5)
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9)

# Beat
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9)
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3)
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5)
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9)

# Bass and noise
fitMedia(ELECTRO_ANALOGUE_BASS_008, 5, 1, 9)
fitMedia(TECHNO_WHITENOISESFX_001, 6, 7, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Comments: Using comments to describe what the code does

// Setup
setTempo(130);

// Music
// Leads
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9);
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5);
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9);

// Beat
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9);
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3);
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5);
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9);

// Bass and noise
fitMedia(ELECTRO_ANALOGUE_BASS_008, 5, 1, 9);
fitMedia(TECHNO_WHITENOISESFX_001, 6, 7, 9);
----


[[uploadingsounds]]
=== טעינת קליפים של צלילים

ניתן להעלות לספריית הצלילים קליפים של צלילים בעזרת דפדפן הצלילים. פתחו את דפדפן הצלילים ולחצו על "add sound" מתחת לפילטרים (אם הכפתור לא קיים, ודאו שבצעתם log in). ייפתח חלון. נבדוק את שלוש האפשרויות הראשונות:

. *Upload new Sound*  מאפשר לכם לבחור קובץ שמע שנמצא במחשב שלכם. שנו את שם הקובץ, אם יש צורך בכך ("constant value(required)"), ולחצו "UPLOAD".
. *Quick Record* מאפשרת לכם להקליט קטע קצר ישירות לספרייה של EarSketch. צפו בווידאו בהמשך למידע נוסף.
. *Freesound* מאפשרת יבוא של צלילים מ-Freesound.org, מאגר של קבצי שמע. אתם יכולים לחפש במאגר סוג מסוים של צלילים (כמו: ציוץ ציפורים, גשם, רחוב סואן וכו'). תחת "Results", תופיע רשימה של קליפים. אתם יכולים לשמוע את הקליפ על-ידי לחיצה על play. אם הקליפ מוצא חן בעיניכם, תוכלו להעלות אותו על-ידי לחיצה על "UPLOAD".

כדי למצוא את הצליל שהעליתם או הקלטתם, הקלידו את שם הקובץ בסרגל החיפוש בדפדפן הצלילים.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.תרגלו
****
מוסיקה, ואמנות בכלל, היא, לעיתים קרובות, אמצעי להעברת מסר. המסר מועבר בעזרת המילים ו/או האופי של השיר. כתבו שיר קצר שמבטא משהו. זה יכול להיות הרגשה, שתרצו לשתף, או סיפור.

. החליטו מה תרצו להביע בשיר 
. ואז, או שתכתבו מילים ותקליטו את עצמכם שרים או קוראים אותן או שתקליטו או תעלו צלילים שקשורים למסר
. הוסיפו את ההקלטות לשיר בעזרת הפונקציה `()fitMedia`
. הוסיפו צלילים מספריית הצלילים של EarSketch בעזרת הפונקציה `()fitMedia`
. השמיעו את השיר לחבר/ה
. שוחחו על השיר ועל הדברים שניסיתם להביע בו
****

////
OPTIONAL
////

*Processes*, או תהליכים, הם תוכניות מחשב שרצות במחשב שלכם. יחידת העיבוד המרכזית של המחשב או ה-*Central Processing Unit*, מבצעת אותן. יחידת העיבוד המרכזית נקראת, בקיצור, ה-CPU. 

ה- *זיכרון* של המחשב מאחסן נתונים והוראות עיבוד בהן משתמש ה-CPU. הזיכרון, שנקרא גם אחסון ראשי או RAM (Random Access Memory), מאחסן נתונים באופן זמני. רק מידע של תהליכים, שרצים כרגע, מאוחסן ב-RAM. זה מאפשר ל-CPU לגשת במהירות להוראות ולנתונים.

יש הבדל בין זיכרון (או אחסון קצר טווח) לבין אחסון ארוך טווח. אחסון ארוך טווח, כמו דיסק קשיח או ענן, נקרא גם אחסון משני. *האחסון המשני* מכיל כמויות גדולות של נתונים לתקופות ארוכות, גם אחרי שהמחשב מכובה. ה-CPU לא מתקשר ישירות עם האחסון המשני. כשה-CPU מריץ תהליך, קודם כל, נטענים נתונים מהאחסון המשני אל הזיכרון כך שה-CPU יוכל לגשת אליהם במהירות.

לפעמים הנתונים בזיכרון, בהם משתמש ה-CPU, מגיעים מאמצעי קלט ולא מהאחסון המשני. *קלטים* הם האותות או הנתונים הנקלטים על-ידי המחשב, כמו שמע ממיקרופון, למשל. בדומה לכך, *פלטים* הם אותות או נתונים הנשלחים מהמחשב, כמו אות שמע דרך הרמקול, למשל. קלט/פלט או I/O, היא הדרך בה המחשב מתקשר עם העולם החיצוני, כולל בני אדם!

נסתכל על הקלטת צליל לתוך EarSketch כדוגמה לתהליך. ראשית, אנחנו מקליטים נתונים לתוך המחשב בעזרת אמצעי קלט - המיקרופון. ה-CPU מאחסן את נתוני השמע בזיכרון. כשנלחץ "play" כדי לשמוע את ההקלטה, ה-CPU ניגש לנתונים ושולח אותם לאמצעי פלט - אזניות או רמקול. כשנלחץ על upload, ה-CPU יריץ את התהליך שממיר את נתוני השמע לקובץ בפורמט שמע סטנדרטי (wav), וישלח את הקובץ לשרת EarSketch. השרת הוא מערכת חיצונית שמספקת שירותים לכל משתמשי EarSketch, כולל המחשב שלנו. שרת EarSketch יעביר את קובץ השמע מהזיכרון אל הזיכרון המשני כך שיוכל לגשת אליו בעתיד.

צפו בווידאו הבא:

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== זכויות יוצרים

*זכויות יוצרים* זה החלק של החוק שדן ב*קניין רוחני*, או הבעלות על יצירות, כמו מוסיקה. כשמשתמשים בסימפולים או עושים רמיקס למוסיקה קיימת, צריך לתת קרדיט למחברים. בסקריפט של EarSketch אפשר לעשות זאת בהערות בקוד. לפני שמשתמשים בצלילים של מוסיקאים אחרים וחולקים מוסיקה, יש ללמוד על זכויות יוצרים!

*זכויות יוצרים* זה החלק של החוק שדן ב*קניין רוחני*, או הבעלות על יצירות, כמו מוסיקה. 

כשאתם יוצרים משהו מקורי וממשי, יש לכם זכויות יוצרים עליו באופן אוטומטי! זה אומר שאתם יכולים להכין ממנו עותקים, לשנות אותו ולחלוק אותו.

יש שתי זכויות יוצרים הקשורות לשיר: זכויות על השיר עצמו (של המחבר/ת) וזכויות על הביצוע, כלומר ההקלטה של השיר (בדרך כלל של חברת התקליטים). תמלוגים מביצועים פומביים של השיר משולמים למחבר/ת, ורוב התמלוגים ממכירת הקלטות של השיר משולמים לחברת התקליטים. 

*הפרת זכויות יוצרים* היא פגיעה בזכויות היוצרים, כמו הורדה לא חוקית של מוסיקה, למשל. *שימוש סביר* מתיר שימוש בתוכן מוגן בזכויות יוצרים תחת מגבלות מסוימות, כמו שימוש לצרכי הוראה או שימוש לצרכי ביקורת, בהם משתמשים רק בקטעים קצרים מהיצירה. שימוש סביר נקבע לכל מקרה לגופו.

בזכות השימוש הסביר, ישנה דרך לשימוש במוסיקה ושיתופה. זכויות יוצרים אמורות להקל על יצירה ושיתוף, ולא להכביד עליהן. EarSketch אפשרית בזכות אמניות ואמנים שמשתפים את עבודתם אתכם באמצעות *סימפולים* (קטעים קצרים של הקלטות) בספריית הצלילים. אמניות ואמנים אלה משתפים את הסימפולים תחת רישיון *Creative Commons*, שנותן הרשאה להשתמש ביצירות שלהם. ב-EarSketch יש לכם גישה חופשית לכל הסימפולים האלה. אתם יכולים לשתף אחרים במוסיקה שאתם יוצרים, אבל אסור לכם למכור אותה. שיתוף המוסיקה שיצרתם ולאפשר לאחרים להשתמש בקוד שלכם, היא הדרך שלכם להעביר את זה הלאה, ולתרום ליצירת עוד אמנות.

רישיון*Creative Commons* (או CC) מאפשר ליוצרים לקבוע על אילו זכויות הם שומרים ועל אילו הם מוותרים. הנה כמה אפשרויות לרישיון CC: "מותר להשתמש ביצירה זו בכל אופן שתרצו ובלבד ש

* שמי יופיע עליה." - Attribution (BY)
* לא תשנו אותה בכלל." - No Derivatives (ND)
* לא תרוויחו כסף ממנה." - Non-Commercial (NC)
* תחלקו כל מה שתיצרו בעזרתה, תחת רישיון זהה." - Share-Alike (SA)

כדי לקבוע את הרשאות ה-Creative Commons יש לבחור את סוג הרישיון ולכלול אותו ביצירה. לסקריפט, שמשותף ב-EarSketch, יש לציין את הרישיון. 



[[chapter2summary]]
=== סיכום פרק שני

[role="curriculum-python"]
* *טמפו* הוא המהירות בה קטע מוסיקה מנוגן. הטמפו נתון בביטים לדקה (bpm). טמפו קשור לסוגה (ז'אנר).
* הקליפים בספריית הצלילים של EarSketch מאורגנים בתיקיות של צלילים דומים. כדי לדעת מה הטמפו של קליפ, עברו בספריית הצלילים, עם העכבר, מעל שמו.
* הערות הן שורות קוד שלא מבוצעות על-ידי המחשב. למרות שהן לא מבוצעות, הן מועילות לכתיבת הערות, הארות ותזכורות בתוך הסקריפט.
* `*from earsketch import ` מוסיפה את ה-API של EarSketch לפרויקט שלך. השורה הזו חייבת להימצא בראש כל סקריפט.
* `()setTempo` מאפשרת לקבוע את הטמפו (מפעם) של השיר. יש לכלול שורה כזו בכל סקריפט.
* אתם יכולים להעלות צלילים משלכם ל-EarSketch בעזרת דפדפן הצלילים. פשוט הקליקו על "Add sound".
* *process או תהליך* הוא משימה שרצה במחשב. העיבוד מתבצע על-ידי ה-*CPU*, שאחראי לביצוע הוראות התכנית.
* *זיכרון* (הנקרא גם RAM ואחסון ראשי) מאחסן, באופן זמני, נתונים והוראות לשימוש ה-CPU.
* *אחסון משני* מתייחס לאחסון נתונים לזמן ארוך, לרוב בכמויות גדולות. נתונים מהאחסון המשני חייבים להטען לזיכרון לפני שה-CPU משתמש בהם.
* *זכויות יוצרים* הוא החלק של החוק הדן בבעלות על עבודה יצירתית, כמו מוסיקה. זכויות יוצרים חשובות למוסיקאים כי הן מגדירות איך אמן או אמנית רשאים להשתמש יצירה של מישהו אחר.
* אם יצרתם יצירה ממשית ומקורית, יש לכם, אוטומטית, זכויות יוצרים עליה. במילים אחריות, יש לכם בעלות על יצירות שיצרתם.
* *Licensing או הרשאה לשימוש* של יצירה מוסיקלית נותנת לאחרים רשות להשתמש בה. לפעמים, זכויות מסוימות נשמרות בעזרת הרשאות *Creative Commons*. EarSketch מאפשרת הוספת הרשאת Creative Commons למוסיקה שלכם בחלונית השיתוף (Share).

[role="curriculum-javascript"]
* *טמפו* הוא המהירות בה קטע מוסיקה מנוגן. הטמפו נתון בביטים לדקה (bpm). טמפו קשור לסוגה (ז'אנר).
* הקליפים בספריית הצלילים של EarSketch מאורגנים בתיקיות של צלילים דומים. כדי לדעת מה הטמפו של קליפ, עברו בספריית הצלילים, עם העכבר, מעל שמו.
* הערות הן שורות קוד שלא מבוצעות על-ידי המחשב. הן משמשות לכתיבת הערות, הארות ותזכורות בקוד.
* `;()setTempo` מאפשרת לקבוע את הטמפו (מפעם) של השיר. יש לכלול שורה כזו בכל סקריפט.
* אתם יכולים להעלות צלילים משלכם ל-EarSketch בעזרת דפדפן הצלילים. פשוט הקליקו על "Add sound".
* *process או תהליך* הוא משימה שרצה במחשב. העיבוד מתבצע על-ידי ה-*CPU*, שאחראי לביצוע הוראות התכנית.
* *זיכרון* (הנקרא גם RAM ואחסון ראשי) מאחסן, באופן זמני, נתונים והוראות לשימוש ה-CPU.
* *אחסון משני* מתייחס לאחסון נתונים לזמן ארוך, לרוב בכמויות גדולות. נתונים מהאחסון המשני חייבים להטען לזיכרון לפני שה-CPU משתמש בהם.
* *זכויות יוצרים* הוא החלק של החוק הדן בבעלות על עבודה יצירתית, כמו מוסיקה. זכויות יוצרים חשובות למוסיקאים כי הן מגדירות איך אמן או אמנית רשאים להשתמש יצירה של מישהו אחר.
* אם יצרתם יצירה ממשית ומקורית, יש לכם, אוטומטית, זכויות יוצרים עליה. במילים אחריות, יש לכם בעלות על יצירות שיצרתם.
* *Licensing או הרשאה לשימוש* של יצירה מוסיקלית נותנת לאחרים רשות להשתמש בה. לפעמים, זכויות מסוימות נשמרות בעזרת הרשאות *Creative Commons*. EarSketch מאפשרת הוספת הרשאת Creative Commons למוסיקה שלכם בחלונית השיתוף (Share).




[[chapter-questions]]
=== שאלות

[question]
--
מה `()setTempo` מאפשרת לעשות ב- EarSketch?
[answers]
* לקבוע את הטמפו (מפעם) של השיר
* הוספת צליל לערוץ
* שינוי ביט תיפוף
* שינוי האיכויות של צליל בפרויקט
--

[question]
--
מה היחידה לטמפו?
[answers]
* פעימות לדקה (BPM)
* תיבות
* דציבלים (dB)
* שניות
--

[question]
--
למה משמשות הערות?
[answers]
* כל התשובות נכונות
* ארגון הקוד
* כתיבת תיאור של הסקריפט בתחילתו
* הפיכת הקוד לקריא יותר, עבור מתכנתים אחרים
--

[question]
--
מי מהטענות הבאות נכונה?
[answers]
* דיסק קשיח הוא דוגמה לאחסון משני
* נתוני שמע נשמרים ב-CPU
* ה-CPU מאחסן הוראות לתכניות
* אחסון משני מאחסן נתונים לזמן קצר
--

[question]
--
כיצד משיגים זכויות יוצרים?
[answers]
* על-ידי יצירה ופרסום של עבודה חדשה
* על-ידי קניית פטנט
* על-ידי הצטרפות לארגון חשאי
* על-ידי בחירת הרשאות ליצירה שלכם
--

[question]
--
מה זה Creative Commons?
[answers]
* הרשאה להשתמש ביצירה שלכם תחת מגבלות מסוימות
* תהליך הלחנה
* הרשות לתבוע כל מי שמשתמש במוסיקה שלכם
* רישיון שמאפשר לכם לגבות תגמולים
--
