version: 0.2

env:
  parameter-store:
    ES_VERSION_LIST: /earsketch-webclient/version_number
  secrets-manager:
    GITHUB_USER: Github_EarSketch_CICD_Credentials:github_user
    GITHUB_TOKEN: Github_EarSketch_CICD_Credentials:github_token

phases:
  build:
    commands:
      - npm ci
      - grunt less
      - npm run serve &
      - npm run test-cypress