version: 0.2

env:
  parameter-store:
    NPM_BUILD_COMMAND: /earsketch-webclient/BuildConfig/$ES_BUILD_ENVIRONMENT/npm-build-command
    ENV_FLAGS_FILE: /earsketch-webclient/BuildConfig/$ES_BUILD_ENVIRONMENT/npm-env-flags-file
    ES_VERSION_MAJOR: /earsketch-webclient/version_number/major
    ES_VERSION_MINOR: /earsketch-webclient/version_number/minor
  secrets-manager:
    GITHUB_USER: Github_EarSketch_CICD_Credentials:github_user
    GITHUB_TOKEN: Github_EarSketch_CICD_Credentials:github_token

phases:
  pre_build:
    commands:
      - export ES_SCRIPT_HOME="$CODEBUILD_SRC_DIR/scripts/earsketch-deployment/scripts"
      - export LOCAL_STAGING_DIR_NAME="${CODEBUILD_SOURCE_VERSION//\//-}"
      - export LOCAL_STAGING_DIR="$CODEBUILD_SRC_DIR/$LOCAL_STAGING_DIR_NAME"
      - export ES_VERSION="$ES_VERSION_MAJOR.$ES_VERSION_MINOR.$CODEBUILD_BUILD_NUMBER"
  build:
    commands:
      - du -sh $CODEBUILD_SRC_DIR
      - echo $ES_SCRIPT_HOME
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $LOCAL_STAGING_DIR
      - echo Finished printing variables
      - echo "Entered the build phase..."
      - npm install
      - grunt less
      - npm run $NPM_BUILD_COMMAND -- --env.release=${ES_VERSION} --env.flags=config/$ENV_FLAGS_FILE
      - mkdir $LOCAL_STAGING_DIR
      - echo "Copying the client files to local distribution folder..."
      - cp -r index.html sc.html sorry.html favicon.ico tunepadESLogin.html tpBody.html autograder/ autograder2/ autograder3/ css/ ExportToReaper/ fonts/ img/ scripts/ templates/ dist/ "$LOCAL_STAGING_DIR"
      # - python "$ES_SCRIPT_HOME/github_create_deployment.py" $GITHUB_USER $GITHUB_TOKEN $CODEBUILD_RESOLVED_SOURCE_VERSION $LOCAL_STAGING_DIR_NAME
artifacts:
  files:
    - $LOCAL_STAGING_DIR_NAME/**/*