version: 0.2

env:
  parameter-store:
    ES_VERSION_LIST: /earsketch-webclient/version_number
  secrets-manager:
    GITHUB_USER: Github_EarSketch_CICD_Credentials:github_user
    GITHUB_TOKEN: Github_EarSketch_CICD_Credentials:github_token

phases:
  install:
    commands:
#      yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
  build:
    commands:
      - npm ci
      - grunt less
      - npm run serve & npx wait-on http://localhost:8888
      - npm run test-cypress

reports:
  cypress-reports:
    files:
      - "tests/e2e-cypress/reports/*.xml"
    file-format: "JUNITXML"