[[ch_29]]
== Tous les effets expliqués en détail
:nofooter:

[[importerror]]
=== Import Error

//Python only

[role="curriculum-python"]
*Message de la console :* ImportError : Impossible de trouver ou d'importer les modules appropriés.

[role="curriculum-python"]
*Description :* Une erreur de type « Import Error » se produit lorsqu'un programme ne parvient pas à charger le module indiqué dans une instruction `from...import`, comme `from module import *`. Cela peut être dû à une erreur d'orthographe ou au fait que le module à importer n'existe pas.

[role="curriculum-python"]
*Exemple :* Bien que l'extrait de code ci-dessous indique le mot « EarSketch » dans son style habituel, les modules Python doivent être indiqués en minuscules.

////
Can't turn off pasted without this appearing in JS mode.
////

[role="curriculum-python"]
[source,python]
----
from EarSketch import *
----

[role="curriculum-python"]
L'instruction devrait plutôt être la suivante :

[role="curriculum-python"]
[source,python]
----
from earsketch import *
----

[role="curriculum-python"]
*Solution :* Vérifiez que les instructions `from...import` dans la section supérieure de votre script ne comportent pas de fautes de frappe ni d'erreurs de casse.

[role="curriculum-javascript"]
Les erreurs de type « Import Error » ne se produisent pas en JavaScript. Open a Python script for an explanation of this error type, or move on to <<every-error-explained-in-detail#indexerror, index errors>>.

[[indentationerror]]
=== Indentation Error

//Python only

[role="curriculum-python"]
*Message de la console :* IndentationError : Une erreur d'indentation s'est produite dans le code (manque d'espaces ou espaces en trop).

[role="curriculum-python"]
*Description :* Rappelez-vous qu'une indentation appropriée est nécessaire en Python lors de l'utilisation de boucles, de fonctions et d'instructions conditionnelles, soit toute instruction qui se termine par un deux-points (`:`). Une erreur de type « Indentation Error » est renvoyée lorsque le niveau d'indentation utilisé est incorrect, qu'il soit insuffisant ou en excessif.

[role="curriculum-python"]
*Exemple :* L'éditeur de code EarSketch indentera automatiquement les lignes de code suivant un deux-point (:), mais le programmeur peut accidentellement modifier l'indentation manuellement, par exemple lors de modifications apportées au corps d'un code. Dans l'extrait de code ci-dessous, il est difficile de savoir quelles lignes doivent être dans la boucle, à la fois pour l'utilisateur que pour celui qui lit le code.

////
Can't turn off pasting without this appearing in JS mode
////

[role="curriculum-python"]
[source,python]
----
for measure in range(1, 9, 2):
    fitMedia(melody, 1, measure, measure + 2)
    makeBeat(kick, 2, measure, beatString)
  makeBeat(kick, 2, measure + 1, beatString)
fitMedia(beat, 3, 3, 9)
----

[role="curriculum-python"]
Un corps de code à l'indentation correcte devrait plutôt ressembler à l'extrait ci-dessous. Le corps de la boucle « for » est indenté d'une tabulation et on peut constater que le dernier appel de fonction `fitMedia()` est en dehors de la boucle.

[role="curriculum-python"]
[source,python]
----
for measure in range(1, 9, 2):
    fitMedia(melody, 1, measure, measure + 2)
    makeBeat(kick, 2, measure, beatString)
    makeBeat(kick, 2, measure + 1, beatString)

fitMedia(beat, 3, 3, 9)
----

[role="curriculum-python"]
*Solution :* Essayez de supprimer toutes les tabulations devant le code dans le corps pour que chaque ligne soit contre le côté gauche de l'éditeur de code. Indentez ensuite chaque ligne du corps à la fois, en veillant à ce que le niveau d'indentation soit constant.

[role="curriculum-javascript"]
Les erreurs relatives à l'indentation ne se produisent pas en JavaScript, bien qu'il soit recommandé de toujours utiliser l'indentation correcte pour une lisibilité optimale. Open a Python script for an explanation of this error type, or move on to <<every-error-explained-in-detail#indexerror, index errors>>.

[[indexerror]]
=== Index Error

[role="curriculum-python"]
*Message de la console :* IndexError : Une erreur s'est produite lors de l'utilisation d'un index hors de plage.

[role="curriculum-javascript"]
*Message de la console :* TypeError : Une erreur s'est produite lors de l'utilisation d'un index hors de plage.

[role="curriculum-python"]
*Description :* Une erreur de type « Index Error » est renvoyée lors de la tentative d'accès à un index qui est hors de plage ou qui n'existe pas dans une liste ou une chaîne de caractères.

[role="curriculum-javascript"]
*Description :* Une erreur de type « Index Error » est renvoyée lors de la tentative d'accès à un index qui est hors de plage ou qui n'existe pas dans un tableau ou une chaîne de caractères. Elle est renvoyée comme erreur de type « Type Error » en JavaScript. For an explanation of more general type errors, see the section on <<every-error-explained-in-detail#typeerror, type errors>>.

[role="curriculum-python"]
*Exemple :* Dans le code suivant, nous allons tenter de créer une structure additive à l'aide de clips à partir d'une liste.

[role="curriculum-javascript"]
*Exemple :* Dans le code suivant, nous allons tenter de créer une structure additive à l'aide de clips à partir d'un tableau.

[role="curriculum-python"]
[source,python]
----
# Index Error : Exemple

from earsketch import *
setTempo(100)

orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2]

fitMedia(orch[1], 1, 1, 17)
fitMedia(orch[2], 2, 5, 17)
fitMedia(orch[3], 3, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Index Error : Exemple

setTempo(120);

var orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2];

fitMedia(orch[1], 1, 1, 17);
fitMedia(orch[2], 2, 5, 17);
fitMedia(orch[3], 3, 9, 17);
----

[role="curriculum-python"]
Une erreur de type « Index Error » est renvoyée et la console nous pointe vers la ligne 19, indiquant que l'index est hors de plage. Nous avons trois clips de sons, mais nous avons oublié que les index de liste commencent à 0, donc le dernier index auquel nous devrions avoir accès est l'index 2 :

[role="curriculum-javascript"]
Une erreur de type « Type Error » est renvoyée et la console indique qu'un type de données différend était attendu à la ligne 17. Une valeur hors de plage a été fournie lors du dernier appel à la fonction `fitMedia()`. Nous avons trois clips de sons, mais nous avons oublié que les index de tableau commencent à 0, donc le dernier index auquel nous devrions avoir accès est l'index 2 :

[role="curriculum-python"]
[source,python]
----
# Index Error : Correction

from earsketch import *
setTempo(100)

orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2]

fitMedia(orch[0], 1, 1, 17)
fitMedia(orch[1], 2, 5, 17)
fitMedia(orch[2], 3, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Index Error : Correction

setTempo(120);

var orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2];

fitMedia(orch[0], 1, 1, 17);
fitMedia(orch[1], 2, 5, 17);
fitMedia(orch[2], 3, 9, 17);
----

[role="curriculum-python"]
*Solution :* Notez le nom de chaque clip dans votre liste et étiquetez chacun d'entre eux avec son index correspondant, à partir de 0. Cela vous aide à comprendre la structure de la liste et ce qui peut causer une erreur de type « Index Error ».

[role="curriculum-javascript"]
*Solution :* Notez le nom de chaque clip dans votre tableau et étiquetez chacun d'entre eux avec son index correspondant, à partir de 0. Cela vous aide à comprendre la structure du tableau et ce qui peut causer une erreur de type « Type Error ».

[[nameerror]]
=== Name Error

[role="curriculum-python"]
*Message de la console :* NameError : Une erreur relative à un nom de variable ou de fonction non défini s'est produite.

[role="curriculum-javascript"]
*Message de la console :* ReferenceError : Une erreur relative à un nom de variable ou de fonction non défini s'est produite.

[role="curriculum-python"]
*Description :* Une erreur de type « Name Error » se produit lorsqu'un programme essaie d'utiliser une variable ou d'appeler une fonction qui n'a jamais été définie, le plus souvent en raison d'une faute de frappe.

[role="curriculum-javascript"]
*Description :* Une erreur de type « Name Error » se produit lorsqu'un programme essaie d'utiliser une variable ou d'appeler une fonction qui n'a jamais été définie, le plus souvent en raison d'une faute de frappe. JavaScript fait spécifiquement référence à ce type d'erreur comme étant une erreur de type « Reference Error ».

[role="curriculum-python"]
*Exemple :* Ci-dessous se trouve un script simple pour afficher la chaîne de caractères assignée à la variable `today`. Cependant, une erreur relative à l'instruction « print » empêche le script de s'exécuter.

[role="curriculum-javascript"]
*Exemple :* Ci-dessous se trouve un script simple pour afficher la chaîne de caractères assignée à la variable `today`. Cependant, une erreur relative à la fonction `println()` empêche le script de s'exécuter.


[role="curriculum-python"]
[source,python]
----
# Name Error : Exemple

from earsketch import *
setTempo(120)

today = readInput("What day is it?")
print("Today is " + Today)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Reference Error : Exemple

setTempo(120);

var today = readInput("What day is it?");
println("Today is " + Today);
----

Dans ce cas, la variable contenant la chaîne de caractères à concaténer n'a pas été référencée par le nom approprié ; un « t » en minuscule aurait dû être utilisé.

[role="curriculum-python"]
[source,python]
----
# Name Error : Correction

from earsketch import *
setTempo(120)

today = readInput("What day is it?")
print("Today is " + today)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Reference Error : Correction

setTempo(120);

var today = readInput("What day is it?");
println("Today is " + today);
----

*Solution :* Vérifiez l'orthographe et la casse de vos variables et de vos fonctions. Lorsque vous utilisez une variable ou que vous appelez une fonction, assurez-vous que chacune a été précédemment définie et veillez à bien définir une fonction avant de l'appeler. Bien que vous puissiez coller les noms directement, assurez-vous que vos noms de constantes de sons s'alignent sur les noms de clips dans le navigateur de sons.

[[parseerror]]
=== Parse Error

[role="curriculum-python"]
*Message de la console :* ParseError : Une erreur s'est produite lors de la lecture du code.

[role="curriculum-python"]
*Description :* Le terme *Parsing ou analyse syntaxique* signifie convertir une forme d'informations en une autre. Par conséquent, une erreur de type « Parse Error » se produit lorsque l'interpréteur est incapable de convertir votre code en des informations que l'ordinateur peut utiliser pour faire de la musique. Le formatage du code, c'est-à-dire les parenthèses et les crochets, est souvent la cause d'une erreur de type « Parse Error ».

[role="curriculum-python"]
*Exemple :* Dans l'exemple suivant, nous tentons de nous amuser en sélectionnant des beats aléatoires à jouer sur une mélodie, mais quelque chose empêche l'exécution du code.

[role="curriculum-python"]
[source,python]
----
# Parse Error : Exemple

from earsketch import *
setTempo(98)

soundFolder = HIP_HOP_98_BPM__HHDUSTYGROOVE

chords1 = RD_WORLD_PERCUSSION_PAN_FLUTE_1
chords2 = RD_WORLD_PERCUSSION_PAN_FLUTE_2

fitMedia(chords1, 1, 1, 9)
fitMedia(chords2, 1, 9, 17)

for measure in range(1, 17, 2):
  # sélectionnez un clip aléatoire à l'aide de la fonction API de EarSketch
  beat = selectRandomFile(soundFolder
  fitMedia(beat, 2, measure, measure + 2)
----

////
The parse error included in the example above breaks AsciiDoc syntax highlighting here for some reason. Same happens in Ch. 3. If removed while editing, the closing parentheses of selectRandomFile() should be omitted.
////

[role="curriculum-python"]
Lors de l'exécution du code, la console pointe vers la ligne 26. Cette ligne semble correcte, mais les parenthèses de fermeture manquent à la fonction `selectRandomFile()` de la ligne précédente. Dans de nombreux cas, les erreurs de type « Parse Error » peuvent être corrigées rapidement.

[role="curriculum-python"]
[source,python]
----
# Parse Error : Correction

from earsketch import *
setTempo(98)

soundFolder = HIP_HOP_98_BPM__HHDUSTYGROOVE

chords1 = RD_WORLD_PERCUSSION_PAN_FLUTE_1
chords2 = RD_WORLD_PERCUSSION_PAN_FLUTE_2

fitMedia(chords1, 1, 1, 9)
fitMedia(chords2, 1, 9, 17)

for measure in range(1, 17, 2):
    # sélectionnez un clip aléatoire à l'aide de la fonction API de EarSketch
    beat = selectRandomFile(soundFolder)
    fitMedia(beat, 2, measure, measure + 2)
----

[role="curriculum-python"]
*Solution :* Consultez la console pour savoir où se trouve la ligne fautive. Assurez-vous que toutes les définitions de fonctions, les appels de fonctions et les autres expressions possèdent des parenthèses d'ouverture et de fermeture. Vérifiez s'il y a des signes de ponctuation manquants ou en trop à d'autres endroits de votre script. De plus, vérifiez s'il manque des définitions de fonctions et des arguments. Enfin, vérifiez l'orthographe des arguments que vous passez aux fonctions.

[role="curriculum-javascript"]
Parse errors are interpreted broadly as syntax errors in JavaScript, which is covered <<every-error-explained-in-detail#syntaxerror, next>>.

[[syntaxerror]]
=== Syntax Error

*Message de la console :* SyntaxError : Une erreur relative à la syntaxe (la disposition) du code s'est produite.

*Description :* Une erreur de type « Syntax Error » se produit lorsqu'un programme rencontre une erreur au niveau de la syntaxe du script, soit les règles d'un langage de programmation spécifique.

*Exemple :* Le script suivant est censé créer des blips futuristes à changement dynamique. Cependant, il contient deux bogues communs qui causent des erreurs de type « Syntax Error ».

[role="curriculum-python"]
[source,python]
----
# Syntax Error : Exemple

from earsketch import *
setTempo(120)

clap = RD_TRAP_ARCADEFIRESFX_1
beatString = "00+-0-00+0+-0+++"

for measure in range(1, 32):
    if measure % 4 = 0
    # Utilisation de la fonction API de EarSketch pour mélanger la chaîne de caractères de beat
    beatString = shuffleString(beatString)
    makeBeat(clap, 1, measure, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Syntax Error : Exemple

setTempo(120);

var clap = RD_TRAP_ARCADEFIRESFX_1;
var beatString = "00+-0-00+0+-0+++";

for (var measure = 1; measure < 32; measure++){
  if (measure % 4 = 0)
    //Utilisation de la fonction API de EarSketch pour mélanger une chaîne de caractères de beat
    beatString = shuffleString(beatString);
  }
  makeBeat(clap, 1, measure, beatString);
}
----

[role="curriculum-python"]
Pour ce script, l'éditeur de code nous signale la ligne fautive. Notez qu'il manque un deux-points (:) dans l'instruction _if_. À la même ligne, il y a également une condition invalide ; il faut utiliser l'opérateur d'égalité `==` au lieu de l'opérateur d'affectation `=`.

[role="curriculum-javascript"]
Pour ce script, l'éditeur de code nous signale la ligne fautive. Notez qu'il manque une accolade d'ouverture dans l'instruction de corps _if_. À la même ligne, il y a également une condition invalide ; il faut utiliser l'opérateur d'égalité stricte `===` au lieu de l'opérateur d'affectation `=`.

[role="curriculum-python"]
[source,python]
----
# Syntax Error : Correction

from earsketch import *
setTempo(120)

clap = RD_TRAP_ARCADEFIRESFX_1
beatString = "00+-0-00+0+-0+++"

for measure in range(1, 32):
    if measure % 4 == 0:
        # Utilisation de la fonction API de EarSketch pour mélanger la chaîne de caractères de beat
        beatString = shuffleString(beatString)
    makeBeat(clap, 1, measure, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Syntax Error : Correction

setTempo(120);

var clap = RD_TRAP_ARCADEFIRESFX_1;
var beatString = "00+-0-00+0+-0+++";

for (var measure = 1; measure < 32; measure++) {
    if (measure % 4 === 0) {
    // Utilisation de la fonction API de EarSketch pour mélanger la chaîne de caractères de beat
        beatString = shuffleString(beatString);
    }
    makeBeat(clap, 1, measure, beatString);
}
----

[role="curriculum-python"]
*Solution :* Vérifiez constamment la console et l'éditeur de code pour trouver des indices. Au-delà des erreurs courantes indiquées ci-dessus, vérifiez la présence des guillemets d'ouverture et de fermeture et veillez à ne pas utiliser les mots-clés de Python comme noms de variables.

////
Added solution from parse error to JS version below.
////

[role="curriculum-javascript"]
*Solution :* Vérifiez constamment la console et l'éditeur de code pour trouver des indices.
Au-delà des erreurs courantes indiquées ci-dessus, vérifiez la présence des guillemets d'ouverture et de fermeture, et assurez-vous que les définitions de fonctions, les appels de fonction et les autres expressions possèdent leurs parenthèses d'ouverture et de fermeture. Vérifiez également s'il y a des signes de ponctuation manquants ou en trop à d'autres endroits de votre script. De plus, vérifiez s'il manque des définitions de fonctions et des arguments. Vous ne pouvez pas utiliser les termes réservés à JavaScript comme noms de variables. Enfin, vérifiez l'orthographe des arguments que vous passez aux fonctions.

[[typeerror]]
=== Type Error

*Message de la console :* TypeError : Une erreur relative au type de données attendu s'est produite.

*Description :* Une erreur de type « Type Error » se produit lorsqu'une opération ou une fonction spécifique attend un type de données, mais en reçoit un autre.

[role="curriculum-python"]
*Exemple :* Supposons que vous ayez écrit un script qui effectue le suivi du nombre de mesures totales utilisées à l'aide d'une variable qui s'actualise. Dans l'extrait de code ci-dessous, nous essayons d'afficher un message indiquant la longueur d'une chanson.

[role="curriculum-javascript"]
*Exemple :* Supposons que vous ayez écrit un script qui prend des entrées d'utilisateur pour déterminer la longueur de la chanson. La valeur de l'utilisateur est passée à la fonction `fitMedia()`.

[role="curriculum-python"]
[source,python]
----
# Type Error : Exemple

from earsketch import *
setTempo(120)

soundClip = DUBSTEP_DRUMLOOP_MAIN_006
beatString = "0+000+++0--0-0--"
measureTotal = 0

for measure in range(1, 9):
    makeBeat(soundClip, 1, measure, beatString)
    measureTotal += 1

print("Votre beat est composé de " + measureTotal + " mesures.")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Type Error : Exemple

setTempo(120);

var soundClip = DUBSTEP_DRUMLOOP_MAIN_006;
var measureTotal = readInput("Combien y a-t-il de mesures ?");

println(measureTotal);

fitMedia(soundClip, 1, 1, measureTotal + 1);
----

[role="curriculum-python"]
Une erreur de type « Type Error » est renvoyée, car le type du nombre ne peut pas être concaténé dans une chaîne de caractères. Nous pouvons plutôt utiliser la conversion du type de données pour d'abord convertir la valeur `measureTotal` en une chaîne de caractères :

[role="curriculum-javascript"]
Une erreur de type « Type Error » est renvoyée, car nous avons accidentellement passé une chaîne de caractères comme dernier argument de la fonction `fitMedia()`. Nous pouvons plutôt utiliser la conversion du type de données pour d'abord convertir la chaîne de caractères `measureTotal` en un nombre :

[role="curriculum-python"]
[source,python]
----
# Type Error : Correction

from earsketch import *
setTempo(120)

soundClips = DUBSTEP_DRUMLOOP_MAIN_006
beatString = "0+000+++0--0-0--"
measureTotal = 0

for measure in range(1, 9):
    makeBeat(soundClips, 1, measure, beatString)
    measureTotal += 1

print("Votre beat est composé de " + str(measureTotal) + " mesures.")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Type Error : Correction

setTempo(120);

var soundClip = DUBSTEP_DRUMLOOP_MAIN_006;
var measureTotal = readInput("Combien y a-t-il de mesures ?");

println(measureTotal);

fitMedia(soundClip, 1, 1, Number(measureTotal) + 1);
----

*Solution :* La console de EarSketch donne le type de données fautif et pointe vers un numéro de ligne spécifique. Vérifiez les types de données cohérents dans les expressions arithmétiques, les opérations de structure de données et les arguments de fonctions. De plus, assurez-vous que vos appels de fonction ont le nombre d'arguments approprié.

////
(ex. trying to concatenate something into string that isn't string, modifying a string value instead of concatenating something in, function call with too few arguments)
////

[[valueerror]]
=== Value Error

[role="curriculum-python"]
*Message de la console :* ValueError : Un argument fourni ne se trouve pas dans l'ensemble ou la plage de valeurs acceptables pour une fonction.

[role="curriculum-javascript"]
*Message de la console :* RangeError : Un argument fourni ne se trouve pas dans l'ensemble ou la plage de valeurs acceptables pour une fonction.

[role="curriculum-python"]
*Description :* Une erreur de type « ValueError » se produit lorsqu'une fonction reçoit un argument de type correct, mais une valeur inappropriée.

[role="curriculum-javascript"]
*Description :* Une erreur de type « ValueError » se produit lorsqu'une fonction reçoit un argument de type correct, mais une valeur inappropriée. JavaScript fait spécifiquement référence à ce type d'erreur comme étant une erreur de type « Range Error ».

[role="curriculum-python"]
*Exemple :* L'extrait de code suivant tente de créer un beat intéressant en utilisant `makeBeat()` avec des listes.

[role="curriculum-javascript"]
*Exemple :* L'extrait de code suivant tente de créer un beat intéressant en utilisant `makeBeat()` avec des tableaux.

[role="curriculum-python"]
[source,python]
----
# Value Error: Exemple

from earsketch import *
setTempo(120)

drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001]
beatString = "1+3+1+221+2+1+24"

makeBeat(drumKit, 1, 1, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Range Error: Exemple

setTempo(120);

var drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001];
var beatString = "1+3+1+221+2+1+24";

makeBeat(drumKit, 1, 1, beatString);
----

[role="curriculum-python"]
Le quatrième argument de la fonction `makeBeat()` est du type approprié, mais une des valeurs d'index auxquelles il doit accéder est invalide. Dans ce scénario, il est probable que le programmeur ait oublié que les index de liste commencent à zéro.

[role="curriculum-javascript"]
Le quatrième argument de la fonction `makeBeat()` est du type approprié, mais une des valeurs d'index auxquelles il doit accéder est invalide. Dans ce scénario, il est probable que le programmeur ait oublié que les index de tableau commencent à zéro.

[role="curriculum-python"]
[source,python]
----
# Value Error : Correction

from earsketch import *
setTempo(120)

drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001]
beatString = "0+2+0+110+1+0+13"

makeBeat(drumKit, 1, 1, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Range error : Correction

setTempo(120);

var drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001];
var beatString = "0+2+0+110+1+0+13";

makeBeat(drumKit, 1, 1, beatString);
----

*Solution :* Vérifiez vos chaînes de caractères de beat pour vous assurer que les valeurs sont dans la plage appropriée. De plus, confirmez que tous les arguments fournis à la fonction `setEffect()` sont dans la plage requise pour l'effet.
