[[ch_29]]
== הסבר מפורט לכל שגיאה
:nofooter:

[[importerror]]
=== Import Error שגיאת ייבוא

//Python only

[role="curriculum-python"]
*ההודעה בקונסול:* ImportError: The appropriate packages cannot be found or imported.

[role="curriculum-python"]
*תיאור:* השגיאה קורית כאשר תכנית לא מצליחה לטעון מודול שנתון בהוראת `from...import`. לדוגמה: ` * from module import`. השגיאה יכולה לנבוע מטעות בהקלדת שם המודול או מקריאה למודול שלא קיים.

[role="curriculum-python"]
*לדוגמה:* בקטע הקוד הבא, המילה "EarSketch" מופיעה באיות הרגיל שלה. אבל, בפייתון שמות מודולים מורכבים רק מאותיות קטנות.

////
Can't turn off pasted without this appearing in JS mode.
////

[role="curriculum-python"]
[source,python]
----
from EarSketch import *
----

[role="curriculum-python"]
השורה צריכה להיות:

[role="curriculum-python"]
[source,python]
----
from earsketch import *
----

[role="curriculum-python"]
*פתרון:* בדקו את הוראות `from...import` בקוד, וודאו ששמות המודולים כתובים ללא שגיאות ובאותיות קטנות.

[role="curriculum-javascript"]
שגיאות ייבוא לא קורות ב-JavaScript. Open a Python script for an explanation of this error type, or move on to <<every-error-explained-in-detail#indexerror, index errors>>.

[[indentationerror]]
=== Indentation Error שגיאת הזחה

//Python only

[role="curriculum-python"]
*ההודעה בקונסול:* IndentationError: There is an indentation error in the code (lack of or extra spaces).

[role="curriculum-python"]
*תיאור:* זכרו שיש לבצע הזחה ימינה (אינדנטציה), בפייתון, כשמשתמשים בלולאות והוראות תנאי וכשמגדירים פונקציות. יש לבצע הזה אחרי כל הוראה שמסתיימת ב- (`:`). שגיאת הזחה קורית, כאשר לא מזיחים מספיק או מזיחים יותר מדי, את הקוד.

[role="curriculum-python"]
*דוגמה:* עורך הקוד של EarSketch מזיח, אוטומטית, את שורות הקוד אחרי נקודתיים, אבל המתכנת/ת עלול/ה לשנות בטעות את ההזחה, כשמבוצעים שינויים בקוד, למשל. בקטע הקוד הבא, לא ברור אלו שורות נכללות בלולאה.

////
Can't turn off pasting without this appearing in JS mode
////

[role="curriculum-python"]
[source,python]
----
for measure in range(1, 9, 2):
    fitMedia(melody, 1, measure, measure + 2)
    makeBeat(kick, 2, measure, beatString)
  makeBeat(kick, 2, measure + 1, beatString)
fitMedia(beat, 3, 3, 9)
----

[role="curriculum-python"]
קוד מוזח היטב יראה כמו הקטע הבא. גוף הלולאה מוזח בטאב אחד. ברור שהקריאה האחרונה ל-`()fitMedia` היא מחוץ ללולאה.

[role="curriculum-python"]
[source,python]
----
for measure in range(1, 9, 2):
    fitMedia(melody, 1, measure, measure + 2)
    makeBeat(kick, 2, measure, beatString)
    makeBeat(kick, 2, measure + 1, beatString)

fitMedia(beat, 3, 3, 9)
----

[role="curriculum-python"]
*פתרון:* מחקו את כל הרווחים בתחילת השורות, כל שכל השורות יתחילו בצמוד לקצה השמאלי של העורך. הזיחו כל שורה, והקפידו שההזחה בכל השורות תהיה זהה.

[role="curriculum-javascript"]
שגיאות הזחה לא קורות ב-JavaScript. Open a Python script for an explanation of this error type, or move on to <<every-error-explained-in-detail#indexerror, index errors>>.

[[indexerror]]
=== Index Error שגיאת אינדוקס

[role="curriculum-python"]
*ההודעה בקונסול:* IndexError: There is an error using an out of range index.

[role="curriculum-javascript"]
*ההודעה בקונסול:* TypeError: There is an error using an out of range index.

[role="curriculum-python"]
*תיאור:* שגיאת אינדוקס קורית כשהקוד מנסה לגשת לאינדקס לא קיים (גדול מדי או שלילי) ברשימה או במחרוזת.

[role="curriculum-javascript"]
*תיאור:* שגיאת אינדוקס קורית כשהקוד מנסה לגשת לאינדקס לא קיים (גדול מדי או שלילי) במערך או במחרוזת. השגיאה היא שגיאת טיפוס (typק error) ב-JavaScript. For an explanation of more general type errors, see the section on <<every-error-explained-in-detail#typeerror, type errors>>.

[role="curriculum-python"]
*לדוגמא:* קטע הקוד הבא, מנסה לגשת לאברי רשימה המכילה שמות קליפים.

[role="curriculum-javascript"]
*לדוגמא:* קטע הקוד הבא, מנסה לגשת לאברי מערך המכיל שמות קליפים.

[role="curriculum-python"]
[source,python]
----
# Index Error: Example

from earsketch import *
setTempo(100)

orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2]

fitMedia(orch[1], 1, 1, 17)
fitMedia(orch[2], 2, 5, 17)
fitMedia(orch[3], 3, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Index Error: Example

setTempo(120);

var orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2];

fitMedia(orch[1], 1, 1, 17);
fitMedia(orch[2], 2, 5, 17);
fitMedia(orch[3], 3, 9, 17);
----

[role="curriculum-python"]
נזרקת שגיאת אינדוקס ובקונסול מודפסת הודעה שאומרת שבשורה 39 האינדקס מחוץ לתחום. הקוד ממקם שלושה קליפים מהרשימה, אבל אינדקסים ברשימה מתחילים מאפס, והאינדקס האחרון ברשימה orch הוא שתיים (ולא שלוש):

[role="curriculum-javascript"]
נזרקת שגיאת טיפוס ומודפסת, בקונסול, הודעה שאומרת שבשורה 17 היה צריך להשתמש בטיפוס אחר. הקריאה האחרונה לפונקציה `()fitMedia`קיבלה ערך מחוץ לתחום. ישנם שלושה קליפים, אבל מערך מתחיל מאינדקס אפס, כך שהאינדקס האחרון ב-orch הוא שתיים (ולא שלוש):

[role="curriculum-python"]
[source,python]
----
# Index Error: Correction

from earsketch import *
setTempo(100)

orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2]

fitMedia(orch[0], 1, 1, 17)
fitMedia(orch[1], 2, 5, 17)
fitMedia(orch[2], 3, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Index Error: Correction

setTempo(100);

var orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2];

fitMedia(orch[0], 1, 1, 17);
fitMedia(orch[1], 2, 5, 17);
fitMedia(orch[2], 3, 9, 17);
----

[role="curriculum-python"]
*פתרון:* יש לכתוב את השם של כל קליפ ברשימה, כל קליפ והאינדקס שלו, ולהתחיל באינדקס אפס. זה מאפשר להבין את מבנה הרשימה ולמצוא מה יכול לגרום לשגיאה.

[role="curriculum-javascript"]
*פתרון:* יש לכתוב את השם של כל קליפ במערך, כל קליפ והאינדקס שלו, ולהתחיל באינדקס אפס. זה מאפשר להבין את מבנה המערךולמצוא מה יכול לגרום לשגיאה.

[[nameerror]]
=== Name Error שגיאת שם

[role="curriculum-python"]
*ההודעה בקונסול:* NameError: There is an error with a variable or function name that is not defined.

[role="curriculum-javascript"]
*ההודעה בקונסול:* Reference Error: There is an error with a variable or function name that is not defined.

[role="curriculum-python"]
*תיאור:* שגיאת שם קורית כשתכנית מנסה להשתמש במשתנה או לקרוא לפונקציה שלא הוגדרו, בדרך כלל בגלל טעות הקלדה.

[role="curriculum-javascript"]
*תיאור:* שגיאת שם קורית כשתכנית מנסה להשתמש במשתנה או לקרוא לפונקציה שלא הוגדרו, בדרך כלל בגלל טעות הקלדה. JavaScript מתייחסת לשגיאות כאלה כשגיאות הפנייה (reference errors).

[role="curriculum-python"]
*דוגמה:* להלן קטע קוד המדפיס את המחרוזת שמאוחסנת במשתנה`today`. אבל, טעות בהוראה print מונעת מהסקריפט לרוץ.

[role="curriculum-javascript"]
*דוגמה:* להלן קטע קוד המדפיס את המחרוזת שמאוחסנת במשתנה`today`. אבל, טעות בפונקציה ()println מונעת מהסקריפט לרוץ.


[role="curriculum-python"]
[source,python]
----
# Name Error: Example

from earsketch import *
setTempo(120)

today = readInput("What day is it?")
print("Today is " + Today)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Reference Error: Example

setTempo(120);

var today = readInput("What day is it?");
println("Today is " + Today);
----

במקרה זה, שם המשתנה שמכיל את המחרוזת לשרשור, לא מאוית נכון. שמו צריך להיות מאוית עם t קטנה.

[role="curriculum-python"]
[source,python]
----
# Name Error: Correction

from earsketch import *
setTempo(120)

today = readInput("What day is it?")
print("Today is " + today)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Reference Error: Correction

setTempo(120);

var today = readInput("What day is it?");
println("Today is " + today);
----

*פתרון:* יש לבדוק את האיות של כל שמות המשתנים והפונקציות. יש לשים לב להבדל בין אותיות קטנות וגדולות. כשמשתמשים במשתנה או פונקציה, יש לוודא שהם הוגדרו. יש לוודא שפונקציה מודרת לפני שקוראים לה. למרות שאפשר להשתמש בהעתק/הדבק, יש לוודא ששמות הקבועים זהם לשמות הקליפים בדפדפן הצלילים.

[[parseerror]]
=== Parse Error שגיאות פריסה

[role="curriculum-python"]
*ההודעה בקונסול:* ParseError: There is an error when reading the code.

[role="curriculum-python"]
*תיאור:* *פריסה (parsing)* היא המרה צורה של ידע לצורה אחרת. שגיאת פריסה קורית כאשר המפרש (interpreter) לא מצליח להמיר את הקוד למידע, שהמחשב יכול ליצור ממנו מוסיקה. שגיאות פריסה נגרמות, בדרך כלל, מטעויות בכתיבת סוגריים למיניהם.

[role="curriculum-python"]
*דוגמה:* בקטע הקוד הבא נבחרים קליפים לנגינה בצורה אקראית. אבל משהו מונע מהקוד לרוץ.

[role="curriculum-python"]
[source,python]
----
# Parse Error : Example

from earsketch import *
setTempo(98)

soundFolder = HIP_HOP_98_BPM__HHDUSTYGROOVE

chords1 = RD_WORLD_PERCUSSION_PAN_FLUTE_1
chords2 = RD_WORLD_PERCUSSION_PAN_FLUTE_2

fitMedia(chords1, 1, 1, 9)
fitMedia(chords2, 1, 9, 17)

for measure in range(1, 17, 2):
  # select a random clip with EarSketch API function
  beat = selectRandomFile(soundFolder
  fitMedia(beat, 2, measure, measure + 2)
----

////
The parse error included in the example above breaks AsciiDoc syntax highlighting here for some reason. Same happens in Ch. 3. If removed while editing, the closing parentheses of selectRandomFile() should be omitted.
////

[role="curriculum-python"]
ההודעה בקונסול מצביעה על בעיה בשורה 26. שורה 26 נראית בסדר גמור, אבל לפונקציה `()selectRandomFile` בשורה הקודמת חסר הסוגר הימני. במקרים רבים, קל לתקן שגיאות פריסה.

[role="curriculum-python"]
[source,python]
----
# Parse Error : Correction

from earsketch import *
setTempo(98)

soundFolder = HIP_HOP_98_BPM__HHDUSTYGROOVE

chords1 = RD_WORLD_PERCUSSION_PAN_FLUTE_1
chords2 = RD_WORLD_PERCUSSION_PAN_FLUTE_2

fitMedia(chords1, 1, 1, 9)
fitMedia(chords2, 1, 9, 17)

for measure in range(1, 17, 2):
    # select a random clip with EarSketch API function
    beat = selectRandomFile(soundFolder)
    fitMedia(beat, 2, measure, measure + 2)
----

[role="curriculum-python"]
*פתרון:* יש לבדוק את ההודעה בקונסול כדי לדעת מי השורה השגויה. יש לוודא שכל הגדרות הפונקציות, הקריאות לפונקציות וביטויים אחרים מכילים גם סוגר שמאלי וגם סוגר ימני. יש לבדוק האם יש סימן פיסוק חסר בכל רחבי הקוד. באותה הזדמנות, כדאי לבדוק האם חסרות הגדרות של פונקציות, והאם בכל קריאה לפונקציה מועברים הפרמטרים הנדרשים. לסיום, יש לבדוק את האיות של שמות הפרמטרים שמועברים לפונקציה.

[role="curriculum-javascript"]
Parse errors are interpreted broadly as syntax errors in JavaScript, which is covered <<every-error-explained-in-detail#syntaxerror, next>>.

[[syntaxerror]]
=== Syntax Error שגיאת תחביר

*ההודעה בקונסול:* SyntaxError: There is an error with the syntax (or arrangement) of code.

*תיאור:* שגיאת תחביר קורית כאשר הקוד מפר את כללי התחביר של שפת התכנות.

*דוגמה:* הסקריפט אמור ליצור "ביפים" עתידניים שמשתנים בצורה דינמית. אבל הוא מכיל שני באגים שגורמים לשגיאות תחביריות.

[role="curriculum-python"]
[source,python]
----
# Syntax Error: Example

from earsketch import *
setTempo(120)

clap = RD_TRAP_ARCADEFIRESFX_1
beatString = "00+-0-00+0+-0+++"

for measure in range(1, 32):
    if measure % 4 = 0
    # Use EarSketch API function to shuffle beat string
    beatString = shuffleString(beatString)
    makeBeat(clap, 1, measure, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Syntax Error: Example

setTempo(120);

var clap = RD_TRAP_ARCADEFIRESFX_1;
var beatString = "00+-0-00+0+-0+++";

for (var measure = 1; measure < 32; measure++){
  if (measure % 4 = 0)
    //Use EarSketch API function to shuffle beat string
    beatString = shuffleString(beatString);
  }
  makeBeat(clap, 1, measure, beatString);
}
----

[role="curriculum-python"]
בסקריפט זה, עורך הקוד מצביע על השורה השגויה. חסרות נקודתיים בסוף הוראת ה-_if_. באותה שורה, צריך היה להשתמש באופרטור ההשוואה `==` ולא באופרטור ההשמה `=`.

[role="curriculum-javascript"]
בסקריפט זה, עורך הקוד מצביע על השורה השגויה. בתחילת גוף הוראת ה- _if_ חסר סוגר מסולסל. באותה שורה, צריך היה להשתמש באופרטור ההשוואה `===` ולא באופרטור ההשמה `=`.

[role="curriculum-python"]
[source,python]
----
# Syntax Error: Correction

from earsketch import *
setTempo(120)

clap = RD_TRAP_ARCADEFIRESFX_1
beatString = "00+-0-00+0+-0+++"

for measure in range(1, 32):
    if measure % 4 == 0:
        # Use EarSketch API function to shuffle beat string
        beatString = shuffleString(beatString)
    makeBeat(clap, 1, measure, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Syntax Error: Correction

setTempo(120);

var clap = RD_TRAP_ARCADEFIRESFX_1;
var beatString = "00+-0-00+0+-0+++";

for (var measure = 1; measure < 32; measure++) {
    if (measure % 4 === 0) {
    // Use EarSketch API function to shuffle beat string
        beatString = shuffleString(beatString);
    }
    makeBeat(clap, 1, measure, beatString);
}
----

[role="curriculum-python"]
*פתרון:* צריך לבדוק את עורך הקוד וחלונית הקונסול כדי למצוא את מיקום השגיאה. מעבר לשגיאות הנפוצות שהוזכרו, יש לבדוק פתיחה וסגירה של מירכאות, ויש לוודא שלא נעשה שימוש במילים שמורות של פייתון כשמות של משתנים.

////
Added solution from parse error to JS version below.
////

[role="curriculum-javascript"]
*פתרון:* צריך לבדוק את עורך הקוד וחלונית הקונסול כדי למצוא את מיקום השגיאה.
מעבר לשגיאות הנפוצות שהוזכרו, יש לבדוק פתיחה וסגירה של מירכאות, ויש לוודא שבכל ההגדרות של פונקציות, הקריאות לפונקציות והביטויים שיש בהם סוגריים, יש גם סוגר ימני וגם סוגר שמאלי. יש לבדוק האם יש סימן פיסוק חסר בכל רחבי הקוד. באותה הזדמנות, כדאי לבדוק האם חסרות הגדרות של פונקציות, והאם בכל קריאה לפונקציה מועברים הפרמטרים הנדרשים. אסור להשתמש במילים שמורות של JavaScript כשמות של משתנים. לסיום, יש לבדוק את האיות של שמות הפרמטרים שמועברים לפונקציה.

[[typeerror]]
=== Type Error שגיאת טיפוס

*ההודעה בקונסול:* TypeError: There is an error with the expected data type.

*תיאור:* שגיאת טיפוס קורית כשפעולה או פונקציה אמורות לקבל ערך מטיפוס מסוים אך מקבלות ערך מטיפוס אחר.

[role="curriculum-python"]
*דוגמה:* נניח שסקריפט עוקב אחרי מספר התיבות בשיר מסוים, בעזרת משתנה שמונה את מספר התיבות. קטע הקוד הבא מנסה להדפיס את מספר התיבות בשיר.

[role="curriculum-javascript"]
*דוגמה:* נניח שסקריפט מקבל מהמשתמש קלט שקובע את אורך השיר. הקלט מועבר כפרמטר ל-`()fitMedia`.

[role="curriculum-python"]
[source,python]
----
# Type Error: Example

from earsketch import *
setTempo(120)

soundClip = DUBSTEP_DRUMLOOP_MAIN_006
beatString = "0+000+++0--0-0--"
measureTotal = 0

for measure in range(1, 9):
    makeBeat(soundClip, 1, measure, beatString)
    measureTotal += 1

print("Your beat is " + measureTotal + " measures long.")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Type Error: Example

setTempo(120);

var soundClip = DUBSTEP_DRUMLOOP_MAIN_006;
var measureTotal = readInput("How many measures?");

println(measureTotal);

fitMedia(soundClip, 1, 1, measureTotal + 1);
----

[role="curriculum-python"]
יש כאן שגיאת טיפוס כי לא ניתן לשרשר מספר למחרוזת. כדי שהשרשור יהיה אפשרי, יש להמיר את הערך של `measureTotal` למחרוזת:

[role="curriculum-javascript"]
נוצרת שגיאת טיפוס, כי פרמטר אחרון מטיפוס מחרוזת הועבר ל-`()fitMedia`. יש להמיר את הערך של `measureTotal` למספר:

[role="curriculum-python"]
[source,python]
----
# Type Error: Correction

from earsketch import *
setTempo(120)

soundClips = DUBSTEP_DRUMLOOP_MAIN_006
beatString = "0+000+++0--0-0--"
measureTotal = 0

for measure in range(1, 9):
    makeBeat(soundClips, 1, measure, beatString)
    measureTotal += 1

print("Your beat is " + str(measureTotal) + " measures long.")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Type Error: Correction

setTempo(120);

var soundClip = DUBSTEP_DRUMLOOP_MAIN_006;
var measureTotal = readInput("How many measures?");

println(measureTotal);

fitMedia(soundClip, 1, 1, Number(measureTotal) + 1);
----

*פתרון:* הקונסול מצביע על טיפוס הנתונים השגוי ועל השורה בה נמצאת השגיאה. יש לבדוק התאמה בין הטיפוסים בביטויים אריתמטיים, פעולות על מבני נתונים ובהעברת פרמטרים לפונקציה. בנוסף, צריך לוודא שלקריאות לפונקציה מועברים פרמטרים בכמות הנדרשת.

////
(ex. trying to concatenate something into string that isn't string, modifying a string value instead of concatenating something in, function call with too few arguments)
////

[[valueerror]]
=== Value Error טעות ערך

[role="curriculum-python"]
*ההודעה בקונסול:* ValueError: A provided argument is not within the set or range of acceptable values for a function.

[role="curriculum-javascript"]
*ההודעה בקונסול:* RangeError: A provided argument is not within the set or range of acceptable values for a function.

[role="curriculum-python"]
*תיאור:* שגיאת ערך קורית כשפונקציה מקבל פרמטר מהטיפוס הנכון אבל בעל ערך לא בתחום הנדרש.

[role="curriculum-javascript"]
*תיאור:* שגיאת ערך קורית כשפונקציה מקבל פרמטר מהטיפוס הנכון אבל בעל ערך לא בתחום הנדרש. JavaScript מתייחסת לשגיאות כאלה כשגיאות טווח (range errors).

[role="curriculum-python"]
*דוגמה:* קטע הקוד הבא מנסה ליצור ביט מעניין בעזרת`()makeBeat` ורשימות.

[role="curriculum-javascript"]
*דוגמה:* קטע הקוד הבא מנסה ליצור ביט מעניין בעזרת`()makeBeat` ומערכים.

[role="curriculum-python"]
[source,python]
----
# Value Error: Example

from earsketch import *
setTempo(120)

drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001]
beatString = "1+3+1+221+2+1+24"

makeBeat(drumKit, 1, 1, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Range Error: Example

setTempo(120);

var drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001];
var beatString = "1+3+1+221+2+1+24";

makeBeat(drumKit, 1, 1, beatString);
----

[role="curriculum-python"]
הפרמטר הרביעי של `makeBeat()` הוא מהטיפוס הנכון, אבל אחד מערכי האינדקס, אליהם הוא ניגש, לא חוקי. סביר להניח, שהמתכנת/ת שכח/ה שאינדקסים ברשימה מתחילים מאפס.

[role="curriculum-javascript"]
הפרמטר הרביעי של `makeBeat()` הוא מהטיפוס הנכון, אבל אחד מערכי האינדקס, אליהם הוא ניגש, לא חוקי. סביר להניח, שהמתכנת/ת שכח/ה שאינדקסים במערך מתחילים מאפס.

[role="curriculum-python"]
[source,python]
----
# Value error: Correction

from earsketch import *
setTempo(120)

drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001]
beatString = "0+2+0+110+1+0+13"

makeBeat(drumKit, 1, 1, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Range error : Correction

setTempo(120);

var drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001];
var beatString = "0+2+0+110+1+0+13";

makeBeat(drumKit, 1, 1, beatString);
----

*פתרון:* יש לבדוק את מחרוזות התיפוף ולוודא שהערכים בטווח הנכון. כמו כן, יש לוודא שכל הפרמטרים המועברים ל-`()setEffect` הם בטווח הערכים המותר לאפקט.
