[[customizeyourfirstsong]]
== Customize your first song
:nofooter:

In this chapter you will learn how to change the tempo of your song, add comments to your code, and upload your own sounds to enhance the message of your song.

[[settempo]]
=== The `setTempo()` function

[role="curriculum-python"]
--
By now you've noticed that when you create a new script, there are preexisting elements that you must absolutely keep for your code to work:

. Some comments starting with `#` in grey: we'll cover that in next section
. the `from earsketch import*` line, which adds the EarSketch functions (like `fitMedia()`) to the project
. the `setTempo(120)` function, which we will see in detail below
--

[role="curriculum-javascript"]
--
By now you've noticed that when you create a new script, there are preexisting elements that you must absolutely keep for your code to work:

. Some comments starting with `//` in grey: we'll cover that in next section
. the `setTempo(120)` function, which we will see in detail below
--

The `setTempo()` function will determine the speed of your song. The *tempo* is a number of beats per minute (bpm) in Western music. In EarSketch, the default tempo (i.e. the initial value of the tempo) is set to 120bpm, which corresponds to a fast walk or march speed. To change the tempo, just change the number between the parentheses of the `setTempo()` function. The higher the tempo, the faster your music. You can select a tempo between _45bpm and 220bpm_.

.PRACTICE
****
. Create a new script. 
. Place sounds on 2 different tracks.
. Modify your tempo and listen to the song.
. Play your song at 3 different tempos for a friend. Then ask them to rank from slowest to fastest tempo.
****

A genre is a category of artistic composition (e.g. music), characterized by similarities in form, style, or subject matter. Different genres have different tempo ranges. For instance:

[cols="^3*"]
|===
|GENRE|BPM|EXAMPLE

|Hip Hop
|85-95
|Coolio - Gangsta's Paradise (feat. L.V.)
|Pop
|110-130
|Lizzo - Juice 
|Techno
|120-125
|Boris Brejcha - Schleierwolken
|Electro
|100-130
|Apashe - Behind My Eyes (feat. LIA)
|House
|115-130
|DJ Breezy - Kimpinstik (feat. Dahlin Gage & Medikal)
|Dubstep and Trap
|140-150
|Jessica Audiffred & Walshy Fire - Stupid Love (feat. Nia V)
|Drum & Bass
|160-180
|Mollie Collins - Lost & Found
|===

.PRACTICE
****
. Select one artist you really like and find out what genre they belong to.
. Search that genre (on https://soundcloud.com/[Soundcloud] or something similar) and listen to a few snippets of songs in that genre.
. Listen for similarities between the songs.
. You can also research the genre on Wikipedia to get more information about it.
****
 
Note that sometimes one sound clip will sound very different when you preview it and when it's played in your song. That might be because the sound clip's tempo is different from your song's tempo. To know the exact tempo of the sample, hover over the clip's name in the Sound Browser. Then you can modify your song's tempo accordingly or choose a sound clip that better matches your song's tempo.


[[comments]]
=== Add comments to your code

[role="curriculum-python"]
*Comments* are lines of code not executed by the computer. They are only used by humans to make the code easier to understand, to help organize code or to make notes for future use. In Python, comments are indicated by a line starting with a pound `#` symbol. 

[role="curriculum-javascript"]
*Comments* are lines of code not executed by the computer. They are only used by humans to make the code easier to understand, to help organize code or to make notes for future use. In JavaScript, comments are indicated by a line starting with two forward slashes, `//`.

Notice that the first lines of each script are comments that describe your script. For each new script, you will need to fill in this information. This makes it easier for other programmers to understand what your code is about.

.PRACTICE
****
On your current script, fill in the following information in the comments at the beginning of your code:

. script name: the name of your song,
. author : your name,
. description: here write a short description of your project
****

You can also use comments to describe what different sections of your code do. Here is an example below. You can paste and run the code. Note how the comments describe the different sections:

[role="curriculum-python"]
[source,python]
----
# Comments: Using comments to describe what the code does

# Setup
from earsketch import *
setTempo(130)

# Music
# Leads
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9)
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5)
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9)

# Beat
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9)
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3)
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5)
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9)

# Bass and noise
fitMedia(ELECTRO_ANALOGUE_BASS_008, 5, 1, 9)
fitMedia(TECHNO_WHITENOISESFX_001, 6, 7, 9)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Comments: Using comments to describe what the code does

// Setup
setTempo(130);

// Music
// Leads
fitMedia(RD_EDM_ANALOGPLUCK_1, 1, 1, 9);
fitMedia(RD_TRAP_ARPBLEEPLEAD_5, 2, 1, 5);
fitMedia(RD_TRAP_ARPBLEEPLEAD_3, 2, 5, 9);

// Beat
fitMedia(HOUSE_BREAKBEAT_023, 3, 1, 9);
fitMedia(HOUSE_BREAKBEAT_006, 4, 1, 3);
fitMedia(HOUSE_BREAKBEAT_012, 4, 3, 5);
fitMedia(HOUSE_BREAKBEAT_012, 4, 7, 9);

// Bass and noise
fitMedia(ELECTRO_ANALOGUE_BASS_008, 5, 1, 9);
fitMedia(TECHNO_WHITENOISESFX_001, 6, 7, 9);
----

{nbsp} +

[[uploadingsounds]]
=== Upload your own sounds

You can upload your own audio through the _Content Manager_. Open your _Content Manager_ on the left side of your screen. Under the "Sounds" tab, click on the "Add sound" button below the filters to open up the add a sound window (if the button doesn’t show, make sure you are logged in). Let's explore the first 3 options:

. *Upload Sound* allows you to choose audio files (.mp3, .aiff, and so on) already on your computer. Modify the file name if needed ("constant value(required)"), and click on "UPLOAD".
. *Quick Record* lets you record short clips directly into the EarSketch library. Check out the video below for more information.
. *Freesound* allows you to directly import sounds from Freesound.org, an open-source audio database. In the search bar, you can look for a type of sound (ex: bird songs, rain, crowded street...). Under “Results”, a list of sounds will appear. You can preview sounds by clicking on the play button, and if you like it, select the toggle button in front of the file name and then click on “UPLOAD” at the very bottom.

To find the sound you have just uploaded or recorded, type its name in the search bar under the Content Manager's Sound tab.

[role="curriculum-mp4"]
[[video101rec]]
video::./videoMedia/010-01-Recording&UploadingSounds-PY-JS.mp4[]

.PRACTICE
****
Music, and art in general, is often a way to convey a message. It can be either through lyrics, and/or through the mood of the song. We would like for you to create a short song that expresses something. It can be a feeling that you'd like to share, or a story.

. Think about what you'd like to express
. Then either:
.. Write some lyrics and record yourself singing or reading them or
.. Record or download some sounds that are related to your message
. Add these recordings to your song using the `fitMedia()` function
. Then add some additional EarSketch clips using the `fitMedia()` function
. Present your song to your friend
. You can discuss your songs and the things you were trying to express
****

*Processes*, or tasks, are programs that run on your computer. The computer's CPU, or *Central Processing Unit*, carries them out. 

A computer's *memory* holds data and processing instructions for the CPU to use. Memory, also called primary storage or RAM (Random Access Memory), stores its data temporarily. Only the information for processes that are actively running is stored in the RAM. This allows fast access to instructions and data for the CPU.

There is a difference between memory (or short-term storage) and long-term storage. Long-term storage, like a hard-drive or cloud, is referred to as secondary storage. *Secondary storage* holds high volumes of data for long periods of time, even after a computer is shut down. The CPU does not interact directly with secondary storage. When the CPU carries a process out, data from secondary storage must first be put into memory so that the CPU can access it quickly.

Sometimes the data in memory for the CPU to use comes from an input device instead of secondary storage. *Inputs* are the signals or data received by the computer, like audio from a microphone. Likewise, *outputs* are the signals or data sent from it, like audio through a speaker. Input/output, or I/O, is how the computer communicates with the outside world, including humans!

Let's examine recording a sound into EarSketch as an example process. First, we record data into the computer with the input device, the microphone. The CPU stores that audio data in its memory. If you press the play button to hear your recording, the CPU accesses the data and sends it to an output, the speakers or headphones. When you press the upload button, the CPU runs a process that converts the audio data into a standard sound file format (a WAV file, or .wav) and sends it to the EarSketch server. The server is an external system that provides services to all EarSketch users, including your own computer. The EarSketch server saves the sound file from memory to the server's secondary storage so that you can access it in the future.

Check out the following supplementary video:

[role="curriculum-mp4"]
[[video11cpu]]
video::./videoMedia/010-02-ProcessesandMemory-PY-JS.mp4[]

////
END OF OPTIONAL
////

[[copyright]]
=== Use Copyright Wisely

*Copyright* is the part of law that covers *intellectual property*, or ownership of creative work, like music. When using samples (small pieces of music) or remixing existing music, you need to give credit to the authors, and you can do so in the comments of your code. Before using sounds from other musicians and sharing your own music, learn more about copyright!

*Copyright* is the part of law that covers *intellectual property*, or ownership of creative work, like music. 

When you create something original and substantial enough, you get a copyright automatically! In the United States, this means you can: make copies, make modifications, and share what you create.

There are two copyrights involved with a song: rights to the song (by the writer or composer) and rights to the sound recording (often by the record label). Royalties from public performances go to the songwriter and most royalties from record sales go to the record label. 

*Copyright infringement* is a violation of copyright, like illegally downloading music. In the United States, *fair use* allows for use of copyrighted content under certain conditions, like educational or critical purposes, reusing only small amounts of the work. Fair use is determined for each case by a judge on a case-by-case basis.

Besides fair use, there is a way to use and share music openly. Copyright should help us make and share more art, not less. EarSketch works because artists have shared their work with you through *samples* (a small part of sound recording) in the Sounds Library. These artists have shared their samples under a *Creative Commons* license, which gives permission for others to use their work. In EarSketch, you therefore have an open access to these samples, and all the music you create in EarSketch is shareable, though you cannot sell it. Sharing your music or letting other students remix your code is a way of paying this forward and helping to put new art into the world.

*Creative Commons* (or CC) licenses let creators specify what rights they keep and what rights they give away. Here are the possible parts of a CC license: "You can use this work however you like, EXCEPT..."

* "...you have to put my name on it." - Attribution (BY)
* "...you cannot change it at all." - No Derivatives (ND)
* "...you cannot make money from it." - Non-Commercial (NC)
* "...you have to share whatever new thing you make under the same license." - Share-Alike (SA)

To specify a Creative Commons license, all you have to do is choose a type and put it on your work. In EarSketch, when you share a script, you will be asked to specify a license for your song. 



[[chapter2summary]]
=== Chapter 2 Summary

[role="curriculum-python"]
* *Tempo* is the speed at which a piece of music is played, specified in beats per minute (bpm). Tempo is tied to genre.
* The clips in the EarSketch Sounds Library are organized into folders of related sounds. To see the exact tempo of a clip, hover over the name in the Sound Browser.
* Comments are lines of code that are not executed by the computer. However, they are useful for making notes within a script.
* `from earsketch import *` adds the EarSketch API to your project. It must be included at the top of every script.
* `setTempo()` lets you specify the tempo of your song. It must be included in every EarSketch script.
* You can upload your own sounds to EarSketch through the Sound Browser. Just click "Add Sound".
* A *process* is a task running on a computer. Processing is carried out by a computer's *CPU*, which is responsible for executing program instructions.
* *Memory* (a.k.a RAM or primary storage) holds data and processing instructions temporarily for the CPU to use.
* *Secondary storage* refers to long term storage of data, often in high volumes. Data from secondary storage must be put into memory before the CPU can access it.
* *Copyright* is a portion of law that covers ownership of creative work, like music. It is important to musicians because it defines how another person's work can be used and shared.
* If you create a musical work that is tangible and new, you have an automatic copyright. In other words, you have rights over the work you created.
* *Licensing* a piece of music gives others permission to use it. Sometimes, certain rights to a work are kept with *Creative Commons* licenses. EarSketch allows you to add Creative Commons licenses to your music via the Share window.

[role="curriculum-javascript"]
* *Tempo* is the speed at which a piece of music is played, specified in beats per minute (bpm). Tempo is tied to genre.
* The clips in the EarSketch Sounds Library are organized into folders of related sounds. To see the exact tempo of a clip, hover over the name in the Sound Browser.
* Comments are lines of code that are not executed by the computer. However, they are useful for making notes within a script.
* `setTempo();` lets you specify the tempo of your song. It must be included in every EarSketch script.
* You can upload your own sounds to EarSketch through the Sound Browser. Just click "Add Sound".
* A *process* is a task running on a computer. Processing is carried out by a computer's *CPU*, which is responsible for executing program instructions.
* *Memory* (a.k.a RAM or primary storage) holds data and processing instructions temporarily for the CPU to use.
* *Secondary storage* refers to long term storage of data, often in high volumes. Data from secondary storage must be put into memory before the CPU can access it.
* *Copyright* is a portion of law that covers ownership of creative work, like music. It is important to musicians because it defines how another person's work can be used and shared.
* If you create a musical work that is tangible and new, you have an automatic copyright. In other words, you have rights over the work you created.
* *Licensing* a piece of music gives others permission to use it. Sometimes, certain rights to a work are kept with *Creative Commons* licenses. EarSketch allows you to add Creative Commons licenses to your music via the Share window.




[[chapter-questions]]
=== Questions

[question]
--
What does `setTempo()` allow you to do in EarSketch?
[answers]
* Specify the tempo of a song
* Add a sound to a track
* Create a drum beat
* Change the qualities of sound within a project
--

[question]
--
What is the unit for tempo?
[answers]
* Beats Per Minute (BPM)
* Measures
* Decibels(dB)
* Seconds
--

[question]
--
What can you use comments for?
[answers]
* All of the above
* Organizing your code
* Writing a description of your script at the beginning of your script
* Making your code easy to read for other programmers
--

[question]
--
Which of the following statements is true?
[answers]
* A hard drive is an example of secondary storage
* Audio data is saved to a computer’s CPU
* The CPU holds instructional data for programs
* Secondary storage stores data for short periods of time
--

[question]
--
How do you get a copyright?
[answers]
* By creating and publishing any new work
* By buying a patent
* By joining a secret organization
* By choosing a license for your work
--

[question]
--
What is Creative Commons?
[answers]
* A license to share your work openly under certain restrictions
* A composing process
* The right to sue anyone who uses your music
* A license that allows you to collect royalties
--
