[[welcome]]
== Welcome Students and Teachers!
:nofooter:

Welcome to EarSketch!

*Teachers*: View our https://earsketch.gatech.edu/teachermaterials/EarSketch_Alignment_Guide.pdf[new curriculum guide^], and visit our https://www.teachers.earsketch.org[EarSketch Teacher Site^] for additional resources.

*Students*: Continue below to learn more about EarSketch

Here you will learn computer science and music technology side by side. You will use either Python or JavaScript to create your own music. 

Musicians and programmers write computer code to create new sounds, effects, and songs.

[role="curriculum-mp4"]
[[video0]]
video::../landing/media/homepagevid.a1cf3d01.mp4[poster=../landing/img/homepagevid-poster.8993a985.png]

Learning to write computer code is a skill that will be useful to you in a variety of career paths. 

Maybe you'll become a legendary music producer or the industry's most sought-after recording engineer! We wish you good luck on your EarSketch journey.

Click on the right arrow at the top of this text to get started.

Teachers, get access to free teacher materials and community https://www.teachers.earsketch.org/[here^]!

