[[mixingwithconditionnals]]
== Mixer à l'aide d'instructions conditionnelles
:nofooter:

Il est possible d'automatiser beaucoup d'opérations grâce au codage. Un exemple d’automatisation consisterait à programmer un robot pour qu’il s’arrête à la détection d'un obstacle : le robot n’aura donc pas besoin d’un être humain pour le faire arrêter manuellement. Au lieu de cela, le robot aura un capteur pour détecter les obstacles, et s'il y en rencontre, il s'arrêtera. Il est possible de faire des automatisations musicales dans EarSketch, en utilisant des instructions conditionnelles (« if »). Nous allons maintenant voir comment automatiser le mixage des pistes. Le mixage signifie que si une piste est trop forte, nous réduirons son volume et si elle est trop faible, nous augmenterons son volume.


[[analyzetrack]]
=== Utilisation de la fonction `analyzeTrack()`

Nous allons maintenant voir comment détecter l'intensité sonore ou le volume d'une piste. Assurez-vous de bien comprendre la différence entre la hauteur (aiguë ou grave) et le volume (fort ou faible) d'un son. Nous utiliserons une fonction EarSketch nommée `analyzeTrack()`. Copiez et exécutez le code suivant :

[role="curriculum-python"]
[source,python]
----
# AnalyzeTrack() : Utilisation de la fonction analyzeTrack() pour afficher l'intensité sonore d'une piste
# Paramétrage
from earsketch import *
setTempo(120)

# Placement d'un son sur la piste 1
sound = COMMON_LOVE_VOX_COMMON_1
fitMedia(sound, 1, 1, 9)

# Création d'une variable pour stocker l'intensité sonore de la piste 1
loudness1 = analyzeTrack(1, RMS_AMPLITUDE)

# Affichage de l'intensité sonore dans la console
print(loudness1)
----

[role="curriculum-javascript"]
[source,javascript]
----
// AnalyzeTrack() : Utilisation de la fonction analyzeTrack() pour afficher l'intensité sonore d'une piste

// Paramétrage
setTempo(120);

// Placement d'un son sur une piste
var sound = COMMON_LOVE_VOX_COMMON_1;
fitMedia(sound, 1, 1, 9);

// Création d'une variable pour stocker l'intensité sonore de la piste 1
var loudness1 = analyzeTrack(1, RMS_AMPLITUDE);

// Affichage de l'intensité sonore dans la console
println(loudness1);
----


Vous pouvez lire dans votre console que l'intensité sonore affichée est de 0.0967737948641.

* L'intensité sonore peut aller de 0 (silence) à 1 (intensité sonore maximale). 
* Parfois, vous verrez un nombre comme ceci : 1.74630733714e-05. C'est ce qu'on appelle la notation scientifique. Vous voyez le e-05 à la fin ? Cela signifie écrire cinq zéros avant le nombre 17... Ceci correspond à 0,0000174630733714. 
* La plupart des sons auront une intensité sonore inférieure à 0.4. 

La fonction `analyzeTrack()` prend 2 arguments :
* le numéro de piste,
* le paramètre que nous voulons analyser. Pour le volume, il s'agit de : `RMS_AMPLITUDE`.

.ENTRAÎNEZ-VOUS
****
. Vous pouvez essayer ce code avec différents sons (changez la variable "sound") pour découvrir ce que donnera la sortie.
. Ajoutez une seconde piste et utilisez la fonction `analyzeTrack()` pour afficher son intensité sonore dans la console. Lorsque vous exécutez le code, avant de regarder votre console, écoutez votre musique et essayez de deviner quelle piste est la plus forte.
****

Le paramètre de `analyzeTrack()` peut être soit `RMS_AMPLITUDE`, afin d'évaluer l'intensité sonore, soit `SPECTRAL_CENTROID` pour analyser la hauteur du son. Nous allons nous concentrer sur l'analyse de l'intensité sonore dans ce chapitre.

[[booleansandcomparisons]]
=== Booléens et comparaisons

Nous allons maintenant voir comment fonctionne la *logique booléenne*. Cela nous aidera à automatiser certaines tâches.

[role="curriculum-python"]
Les *booléens* sont un type de données. Le type de données booléen peut prendre deux valeurs : `True` ou `False`. `True` et `False` commencent par une lettre majuscule et n'ont pas de guillemets.

[role="curriculum-javascript"]
Les *booléens* sont un type de données. Le type de données booléen peut prendre deux valeurs : `true` ou `false`. `true` et `false` commencent par une lettre minuscule et n'ont pas de guillemets.

[role="curriculum-python"]
--
Pour créer un booléen, vous pouvez soit initialiser une variable (`variable1 = True`), soit utiliser une comparaison. Pour faire une comparaison, nous utilisons un *opérateur de comparaison*. Voici les opérateurs de comparaison :
[cols="^h,1"]
|===
|==
| est identique à
|!=
| n'est pas identique à
|>
| est supérieur à
|>=
| est supérieur ou égal à
|<
| est inférieur à
|\<=
| est inférieur ou égal à
|===
--

[role="curriculum-javascript"]
--
Pour créer un booléen, vous pouvez soit initialiser une variable (`variable1 = true;`), soit utiliser une comparaison. Pour faire une comparaison, nous utilisons un *opérateur de comparaison*. Voici les opérateurs de comparaison :
[cols="^h,1"]
|===
| ==
| est identique à
|!=
| n'est pas identique à
|>
| supérieur à
|>=
| supérieur ou égal à
|<
| inférieur à
|\<=
| inférieur ou égal à
|===
--

Note the difference between:
1. Comparing two values to see if they are identical: `==`
2. l'affectation d'une valeur à une variable `=`

[role="curriculum-python curriculum-mp4"]
[[video17apy]]
video::./videoMedia/Screencast-Ch17-2-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video17ajs]]
video::./videoMedia/Screencast-Ch17-2-JS.mp4[]

// this video will be cut at 2' to delete the section about boolean operators//


[role="curriculum-python"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script et ajouter des sons sur deux pistes.
* Imprimez dans la console `True` si la première piste est plus forte que la seconde piste et `False` sinon.
* Utilisez une boucle « for » avec le compteur `track` pour vérifier si l'intensité sonore est strictement supérieure à 0.01 pour chaque piste. Si c'est le cas, affichez `True`, sinon, imprimez dans la console `False`.
* Vous pouvez utiliser des instructions d'affichage supplémentaires avant d'afficher `True` ou `False`, afin que vous puissiez savoir ce qui est `True` ou `False` lorsque vous lirez la console.
****

[role="curriculum-javascript"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script et ajouter des sons sur deux pistes.
* Imprimez dans la console `true` si la première piste est plus forte que la seconde piste et `false` sinon.
* Utilisez une boucle « for » avec le compteur `track` pour vérifier si l'intensité sonore est strictement supérieure à 0.01 pour chaque piste. Si c'est le cas, affichez `true`, sinon, imprimez `false` dans la console.
* Vous pouvez utiliser des instructions d'affichage supplémentaires avant d'afficher `true` ou `false`, afin que vous puissiez savoir ce qui est `true` ou `false` lorsque vous lirez la console.
****

Voici un exemple :

[role="curriculum-python"]
[source,python]
----
# Exemple de booléen : Analyse de l'intensité sonore de pistes.

# Paramétrage
from earsketch import *
setTempo(120)

# Création de deux pistes
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 2, 1, 9)

# Évaluation de l'intensité sonore des pistes
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)

# Vérification si la piste 1 est plus forte que la piste 2
# Nous créons la comparaison booléenne 1
comparison1 = loudnessTrack1 > loudnessTrack2
print("La piste 1 est-elle plus forte que la piste 2 ?")
print(comparison1)

# Création d'une boucle pour comparer l'intensité sonore de chaque piste à la valeur 0.5
for track in range(1, 3):
    loudness = analyzeTrack(track, RMS_AMPLITUDE)
    print("Est-ce que l'intensité sonore de la piste " + str(track) + " est plus élevée que 0.01?")
    print(loudness > 0.01)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Exemple de booléen : Analyse de l'intensité sonore de pistes
// Paramétrage
setTempo(120);

// Création de deux pistes
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1,1,1,9);
fitMedia(melody2,2,1,9);

// Évaluation de l'intensité sonore des pistes
var loudnessTrack1 = analyzeTrack(1,RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2,RMS_AMPLITUDE);

// Vérification si la piste 1 est plus forte que la piste 2
// Nous créons la comparaison booléenne 1
var comparison1 = (loudnessTrack1 > loudnessTrack2);
println('La piste 1 est-elle plus forte que la piste 2 ?');
println(comparison1);

// Création d'une boucle for pour comparer l'intensité sonore de chaque piste à la valeur 0.5
for (var track = 1; track < 3; track++) {
  var loudness = analyzeTrack(track,RMS_AMPLITUDE);
  println ('Est-ce que l'intensité sonore de la piste ' + track + ' est plus élevée que 0.01 ?');
  println (loudness > 0.01);
}
----

[role="curriculum-python"]
Remarque : dans cet exemple, nous avons utilisé des instructions d'affichage avec des chaînes de caractères pour aider à lire le contenu de la console. Nous avons utilisé l'opérateur `+` pour *concaténer* ou ajouter des chaînes et la fonction str() pour convertir des nombres en chaînes de caractères.

[role="curriculum-javascript"]
Remarque : dans cet exemple, nous avons utilisé des instructions d'affichage avec des chaînes de caractères pour aider à lire le contenu de la console. Nous avons utilisé l'opérateur `+` pour *concaténer* (coller ensemble) des chaînes de caractères.

[[conditionalstatements]]
=== Instructions conditionnelles

Qu'est-ce qu'une instruction conditionnelle ? Une *instruction* correspond à une commande pour l'ordinateur. Une *instruction conditionnelle* est une instruction qui ne doit être exécutée que si une certaine *condition* est remplie (vraie). Par exemple, si vous programmez un robot pour qu'il s'arrête devant un obstacle, la condition sera "Y a-t-il un obstacle ?". Si oui, il doit s'arrêter. Si non, ne faites rien (continuez).

Voyez ci-dessous un exemple d'instruction conditionnelle. Notez la similitude avec une boucle « for » :

[role="curriculum-python"]
[source,python]
----
if condition:
    # Ici, vous devez écrire les instructions que l'ordinateur doit exécuter si la condition est True (vraie)
    # Notez que les instructions sont indentées, tout comme pour les boucles
----

[role="curriculum-javascript"]
[source,javascript]
----
if (condition){
    // Ici, vous devez écrire les instructions que l'ordinateur doit exécuter si la condition est true (vraie)
    // Notez que les instructions sont indentées, comme pour les boucles
----

.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script avec deux pistes.
* Si la première piste est plus forte que la deuxième, réduisez alors son volume. Vous aurez besoin des fonctions `analyzeTrack()` et `setEffect()`, en plus d'une instruction « if ».
* Vous aurez besoin d'un gain négatif (entre -1 et -60dB) pour réduire le volume. 
****

Voici un exemple :
[role="curriculum-python"]
[source,python]
----
# Mélange automatique 1 : Si la piste 1 est plus forte que la piste 2, nous réduirons le volume

# Paramétrage
from earsketch import *
setTempo(120)

# Création de deux pistes
melody1 = RD_CINEMATIC_SCORE_STRINGS_14
melody2 = RD_UK_HOUSE__5THCHORD_1
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 2, 1, 9)

# Évaluation de l'intensité sonore des pistes
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)

# Mélange automatique 1 : Si la piste 1 est plus forte que la piste 2, nous réduirons son volume
if loudnessTrack1 > loudnessTrack2:
    setEffect(1, VOLUME, GAIN, -10)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Mélange automatique 1 : Si la piste 1 est plus forte que la piste 2, nous réduirons le volume

// Paramétrage
setTempo(120);

// Création de deux pistes
var melody1 = RD_CINEMATIC_SCORE_STRINGS_14;
var melody2 = RD_UK_HOUSE__5THCHORD_1;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 2, 1, 9);

// Évaluation de l'intensité sonore des pistes
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);

// Si la piste 1 est plus forte que la piste 2, nous réduirons le volume
if (loudnessTrack1 > loudnessTrack2) {
    setEffect(1, VOLUME, GAIN, -10);
}
----
Il est possible de vérifier plusieurs conditions et d'exécuter des instructions différente selon chaque condition. Vous pouvez ajouter autant de conditions que vous le souhaitez. Nous utiliserons la syntaxe suivante :

[role="curriculum-python"]
[source,python]
----
if condition1:
    # Ici, écrivez les instructions que l'ordinateur doit exécuter si la condition1 est True (vraie). Si la condition est False (n'est pas respectée), passez à la ligne suivante
elif condition2:
    # Ici, écrivez les instructions si condition2 est True. Si la condition2 est False, passez à la ligne suivante
elif condition3:
    # Ici, écrivez ici les instructions si condition3 est True. Si la condition3 est False, passez à la ligne suivante
else:
    # Ici, écrivez les instructions au cas où toutes les 3 conditions sont False
----

[role="curriculum-javascript"]
[source,javascript]
----
if (condition1) {
    // Ici, écrivez les instructions que l'ordinateur doit exécuter si la condition1 est true (vraie)
} else if (condition2) {
    // Ici, écrivez les instructions si la condition2 est True. Si la condition2 est False, passez à la prochaine ligne
    // elif est l'abbréviation de else if
} else if (condition3) {
    // Ici, écrivez les instructions si la condition3 est True. Si la condition3 est False, passez à la ligne suivante
} else {
    // Ici, écrivez les instructions au cas où toutes les 3 conditions sont False
}
----

[[mixingyourtracks]]
=== Mixer vos pistes

Utilisons maintenant tous ces outils pour mixer votre chanson. Le mixage modifie le volume des pistes pour qu'elles soient bien équilibrées. 

[role="curriculum-python"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script.
* Ajoutez des sons, au moins trois pistes, pour un minimum de 16 mesures.
* Vous pouvez utiliser la fonction `makeBeat()` et une boucle « for » pour ajouter des percussions.
* Choisissez votre piste « principale ». Il peut s'agir de votre mélodie ou d'une piste que vous souhaitez mettre en évidence.
* Si votre piste principale n'est pas plus forte que les autres pistes, assurez-vous d'augmenter son volume à l'aide de la fonction `setEffect()`. Ne prenez pas en compte la piste percussive, car la fonction `analyzeTrack()` n'est pas pertinente pour les percussions. `analyzeTrack()` renvoie une moyenne alors que les percussions sont des rafales de son, donc une moyenne n'évalue pas vraiment l'intensité sonore.
* Utilisez des impressions dans la console pour montrer votre processus dans la console. Voici un exemple d'instruction d'impression : `print('Est-ce que le numéro de piste' + str(track) + 'est plus élevé que 0.01 ?')`, si le compteur `track` est égal à `1`, cela affichera 'Est-ce que le numéro de piste 1 est plus élevé que 0.01 ?". La fonction `str()` permet de convertir un nombre (p. ex. : 1) en une chaîne de caractères (p. ex. : '1').
****

[role="curriculum-javascript"]
.ENTRAÎNEZ-VOUS
****
* Créez un nouveau script.
* Ajoutez des sons, au moins trois pistes, pour un minimum de 16 mesures.
* Vous pouvez utiliser la fonction `makeBeat()` et une boucle « for » pour ajouter des percussions.
* Choisissez votre piste « principale ». Il peut s'agir de votre mélodie ou de la piste que vous souhaitez mettre en évidence.
* Si votre piste principale n'est pas plus forte que les autres pistes, assurez-vous d'augmenter son volume à l'aide de la fonction `setEffect()`. Ne prenez pas en compte la piste percussive, car la fonction `analyzeTrack()` n'est pas pertinente pour les percussions.
* Utilisez des impressions dans la console pour montrer votre processus dans la console. Voici un exemple d'instruction d'impression : `println('Est-ce que le numéro de piste' + track + 'est plus élevé que 0.01 ?')`, si le compteur `track` est égal à `1`, cela affichera 'Est-ce que le numéro de piste 1 est plus élevé que 0.01 ?".
****


Let's review some vocabulary:
1. *Operator*: a character that represents an action. We have seen arithmetic operators (`+`, `-`, `\*`, `=`) and comparison operators (`>`, `>=`, `<`, `\<=`, `==`, `!=`).
2. *Expression*: A combination of values, constants, variables, operators, and functions. The computer evaluates expressions to produce a result, usually a single numeric or boolean value.  For example: `1+2` (evaluated to 3) or `1<2` (evaluated to True) or `analyzeTrack(1,RMS_AMPLITUDE)` (evaluated to the loudness of track 1, a float between 0 and 1).
3. *Statements*: instructions for the computer to execute.


Below is an example of automated mixing. We can say it's automated because if you change one or more sounds, you won't have to check their loudness and modify the volume accordingly yourself, since it's already included in the code.

[role="curriculum-python"]
[source,python]
----
# Mélange automatique 2 : Utilisation d'instructions conditionnelles pour mixer les pistes

# Setup
from earsketch import *
setTempo(120)

# Adding a melody and bass
melody1 = YG_ALT_POP_GUITAR_3
melody2 = YG_ALT_POP_GUITAR_1
bass1 = YG_ALT_POP_BASS_1
bass2 = DUBSTEP_SUBBASS_008
strings = YG_HIP_HOP_STRINGS_4
fitMedia(melody1, 1, 1, 9)
fitMedia(melody2, 1, 9, 17)
fitMedia(bass1, 2, 1, 9)
fitMedia(bass2, 2, 9, 17)
fitMedia(strings, 3, 9, 17)

# Adding percussion using makeBeat()
beatKick = "0---0-----0-0---"
beatSnare = "--0-0------000-"
soundKick = OS_KICK02
soundSnare = OS_SNARE06
for measure in range(5, 17):
    makeBeat(soundKick, 4, measure, beatKick)
    makeBeat(soundSnare, 5, measure, beatSnare)

# Mixing my tracks
# First, we analyze the tracks for loudness
loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE)
print("The loudness of track 1 is" + str(loudnessTrack1))
loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE)
print("The loudness of track 2 is" + str(loudnessTrack2))
loudnessTrack3 = analyzeTrack(3, RMS_AMPLITUDE)
print("The loudness of track 3 is" + str(loudnessTrack3))

if loudnessTrack1 < loudnessTrack2:
    # if track 1 is quieter than track 2 then we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5)
    print("track 1 was quieter than track 2")
elif loudnessTrack1 < loudnessTrack3:
    # if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5)
    print("track 1 was quieter than track 3")
else:
    # if track 1 is louder than tracks 2 and 3, then we change nothing
    print("track 1 was the loudest track already")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Mélange automatique 2 : Utilisation d'instructions conditionnelles pour mixer les pistes

// Setup
setTempo(120);

// Adding a melody and bass
var melody1 = YG_ALT_POP_GUITAR_3;
var melody2 = YG_ALT_POP_GUITAR_1;
var bass1 = YG_ALT_POP_BASS_1;
var bass2 = DUBSTEP_SUBBASS_008;
var strings = YG_HIP_HOP_STRINGS_4;
fitMedia(melody1, 1, 1, 9);
fitMedia(melody2, 1, 9, 17);
fitMedia(bass1, 2, 1, 9);
fitMedia(bass2, 2, 9, 17);
fitMedia(strings, 3, 9, 17);

//  Adding percussion using makeBeat()
var beatKick = "0---0-----0-0---";
var beatSnare = "--0-0------000-";
var soundKick = OS_KICK02;
var soundSnare = OS_SNARE06;
for (var measure = 5; measure > 17; measure++) {
    makeBeat(soundKick, 4, measure, beatKick);
    makeBeat(soundSnare, 5, measure, beatSnare);
}

// Mixing my tracks
// First, we analyze the tracks for loudness
var loudnessTrack1 = analyzeTrack(1, RMS_AMPLITUDE);
println("The loudness of track 1 is" + loudnessTrack1);
var loudnessTrack2 = analyzeTrack(2, RMS_AMPLITUDE);
println("The loudness of track 2 is" + loudnessTrack2);
var loudnessTrack3 = analyzeTrack(3, RMS_AMPLITUDE);
println("The loudness of track 3 is" + loudnessTrack3);

if (loudnessTrack1 < loudnessTrack2) {
    // if track 1 is quieter than track 2 then we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5);
    println("track 1 was quieter than track 2");
} else if (loudnessTrack1 < loudnessTrack3) {
    // if track 1 is louder than track 2 but quieter than track 3, we increase the volume of track 1
    setEffect(1, VOLUME, GAIN, +5);
    println("track 1 was quieter than track 3");
} else {
    // if track 1 is louder than tracks 2 and 3, then we change nothing
    println("track 1 was the loudest track already");
}
----


[[chapter6summary]]
=== Résumé du chapitre 6

[role="curriculum-python"]
* La fonction `analyzeTrack()` nécessite deux arguments :
le numéro de piste et un paramètre. Lorsque le paramètre est `RMS_AMPLITUDE`, la fonction renvoie le volume de la piste (un nombre compris entre 0 et 1). Lorsque le paramètre est `SPECTRAL_CENTROID`, la fonction renvoie la brillance de la piste.
* Le type de données *booléen* peut seulement prendre deux valeurs : `True` ou `False`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` évalue si deux valeurs sont égales, alors que `=` affecte une valeur à une variable.
* Un *opérateur * est un caractère qui représente une action.
* Les *expressions* sont évaluées par l'ordinateur pour produire une valeur.
* Une *instruction* correspond à une commande pour l'ordinateur.
* Une *condition* est une expression qui peut être évaluée `True` (vraie) ou `False` (fausse). 
* L'instruction _if_ n'exécute son bloc de code que lorsque sa condition est `True` (vraie). 
* Dans le cas où une condition _if_ est `False`, une instruction facultative _else_ permet l'exécution d'un bloc de code alternatif.

[role="curriculum-javascript"]
* La fonction `analyzeTrack()` prend deux arguments :
le numéro de piste et un paramètre. Lorsque le paramètre est `RMS_AMPLITUDE`, la fonction renvoie l'intensité sonore de la piste (un nombre compris entre 0 et 1). Lorsque le paramètre est `SPECTRAL_CENTROID`, la fonction renvoie la hauteur de la piste.
* Le type de données *booléen* peut valoir seulement deux valeurs : `true` ou `false`.
* Boolean values are generated by comparison operators: `==`, `!=`, `>`, `>=`, `<`, `\<=`.
* `==` évalue si deux valeurs sont égales, alors que `=` affecte une valeur à une variable.
* Un *opérateur * est un caractère qui représente une action.
* Les *expressions* sont évaluées par l'ordinateur pour produire une valeur.
* Une *instruction* correspond à une commande pour l'ordinateur.
* Une *condition* est une expression qui peut être évaluée `true` (vraie) ou `false` (fausse).
* L'instruction _if_ n'exécute son bloc de code que lorsque sa condition est `true` (vraie).
* Dans le cas où une condition _if_ est `false`, une instruction facultative _else_ permet l'exécution d'un bloc de code alternatif.


[[chapter-questions]]
=== Questions

[question]
--
Parmi les éléments suivants, lesquels sont des booléens ?
[answers]
* `5+4 == 5`
* `measure = 1`
* `2<3<4`
* `False()`
--

[role="curriculum-python"]
[question]
--
Quelle serait la valeur de retour du bloc de code suivant (qu'est-ce qui s'afficherait dans la console) ?
[source,python]
----
n = 5
if (n * 3) == 15:
    print(n + 5)
else:
    print(n)
----
[answers]
* 10
* 5
* True
* False
--

[role="curriculum-javascript"]
[question]
--
Quelle serait la valeur de retour du bloc de code suivant (qu'est-ce qui s'afficherait dans la console) ?
[source,javascript]
----
var n = 5;
if (n * 3 == 15) {
    println(5 + n);
} else {
    println(n);
}
----
[answers]
* 10
* 5
* True
* False
--

[question]
--
Qu'est-ce que le mixage ?
[answers]
* Adapter le volume de chaque piste pour qu'elles paraissent bien équilibrées
* Adapter la hauteur de chaque piste pour qu'elles paraissent bien équilibrées
* L'ajout d'un fondu d'ouverture
* L'ajout d'un fondu de fermeture
--

[question]
--
Combien de conditions pouvez-vous vérifier avec une instruction conditionnelle ?
[answers]
* n'importe quel nombre
* 1 condition
* 2 conditions
* 3 conditions
--
