[[ch_15]]
== Debugging Logic
:nofooter:
In this chapter, we define a series of steps to assist with the debugging process. We look at printing variables and other information to the console to help understand how a program is running and identify problems.

[[printingtotheconsole]]
=== Printing to the Console

[role="curriculum-python"]
Printing to the console helps you debug and learn the state of your program. The `print` statement evaluates its argument and displays it in the console. To *evaluate* an expression is to simplify it to its basic form, like showing what a variable or a mathematical expression equals. The expression that `print` evaluates can be any data type. Refer to <<building-blocks#datatypes,Chapter 2>> for a review of data types. Note that in Python, `print` is different from other functions because we do not use it with parentheses.

[role="curriculum-javascript"]
Printing to the console helps you debug and learn the state of your program. The function `println()` evaluates its argument and displays it in the console. To *evaluate* an expression is to simplify it to its basic form, like showing what a variable or a mathematical expression equals. The argument can be any data type. Refer to <<building-blocks#datatypes,Chapter 2>> for a review of data types.

[role="curriculum-python"]
Before running the following code, try to guess what the console will display for each `print` statement.

[role="curriculum-javascript"]
Before running the following code, try to guess what the  console will display for each `println()` call.

[role="curriculum-python"]
[source,python]
----
# Printing: Using print() to print messages in the console

# Setup
from earsketch import *
setTempo(120)

# Printing
# prints the result of 3*4
print(3 * 4)

# prints the value of x
x = 3 * 4
print(x)

# evaluates x/y, then prints the result
y = 2
print(x / y)

# prints the result of the concatenation
print("De" + "bug")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Printing: Using println() to print messages in the console

// Setup
setTempo(120);

// Printing
// prints the result of 3*4
println(3 * 4);

// prints the value of x
var x = 3 * 4;
println(x);

// evaluates x/y, then prints the result
var y = 2;
println(x / y);

// prints the result of the concatenation
println("De" + "bug");
----

[[thedebuggingprocess]]
=== The Debugging Process

Printing, commenting, and the console can all be used to debug your code. Try following these steps if you run into an error.

[role="curriculum-python"]
. *Reproduce the error:* In EarSketch, you should get the same error every time you run the same code.
. *Read the console for clues:* The console will often tell you which line of code caused the error and what type of error it is.
. *Locate the error in your code:* If the console provided a line number, take a look at that line and the previous line in your code. If you cannot find where the error is, use the "comment out" method detailed in <<debugging-and-documenting#documentingcode,Chapter 3>>. *Print debugging* can also be used to locate an error. Read through the problem section of your code and try to follow the logic. Insert `print` statements where you are unsure of the logic, getting the value of variables and checking program state. This helps you check your understanding of the program against what is actually happening. If all else fails, go through your code line by line, just like the computer reads it.
. *Squash the bug:* Check for syntax errors, like unclosed parentheses, quotations, or brackets. Other common errors include incorrect spelling or capitalization of function or variable names, adding media to the wrong measure number, and counting to the wrong number in a loop index. Edit the offending code, and run it to verify its correctness.
. *Ask for help*: If you find you have spent too much time on a bug, then ask someone for help! A fresh pair of eyes can do wonders for spotting mistakes. You can ask your teacher or a student in your class, or you can post a question to the EarSketch Q & A site (click the link at the top of the EarSketch page).

[role="curriculum-javascript"]
. *Reproduce the error:* In EarSketch, you should get the same error every time you run the same code.
. *Read the console for clues:* The console will often tell you which line of code caused the error and what type of error it is.
. *Locate the error in your code:* If the console provided a line number, take a look at that line and the previous line in your code. If you cannot find where the error is, use the "comment out" method detailed in <<debugging-and-documenting#documentingcode,Chapter 3>>. *Print debugging* can also be used to locate an error. Read through the problem section of your code and try to follow the logic. Insert `println()` calls where you are unsure of the logic, getting the value of variables and checking program state. This helps you check your understanding of the program against what is actually happening. If all else fails, go through your code line by line, just like the computer reads it.
. *Squash the bug:* Check for syntax errors, like unclosed parentheses, quotations, or brackets. Other common errors include incorrect spelling or capitalization of function or variable names, adding media to the wrong measure number, and counting to the wrong number in a loop index. Edit the offending code, and run it to verify its correctness.
. *Ask for help*: If you find you have spent too much time on a bug, then ask someone for help! A fresh pair of eyes can do wonders for spotting mistakes. You can ask your teacher or a student in your class, or you can post a question to the EarSketch Q & A site (click the link at the top of the EarSketch page).

Below, we walk through an example of printing variables to help debug a script:

[role="curriculum-python curriculum-mp4"]
[[video15py]]
video::./videoMedia/015-02-TheDebuggingProcess-PY.mp4[]

[role="curriculum-javascript curriculum-mp4"]
[[video15js]]
video::./videoMedia/015-02-TheDebuggingProcess-JS.mp4[]

[[commonerrors]]
=== Common Errors

The following list expands on some common errors covered previously and details some additional common errors.

[role="curriculum-python"]
. *Misspelling:* Spelling mistakes are the most prevalent error across programming languages. When using variables, make sure to use the same name you gave at assignment. Likewise, check the spelling of your functions, arguments, and sound constants.
. *Case sensitivity:* Most constructs used in programming are case sensitive, meaning you must pay attention to lowercase and uppercase letters used in variable names, functions, arguments, and sound constants.
. *Parentheses:* Forgetting an opening or closing parentheses where needed will cause a <<every-error-explained-in-detail#syntaxerror,syntax error>>. Make sure your arguments are enclosed by parentheses on both ends when defining and calling functions.
. *Initializing variables*: A variable must be initialized before it can be used in a script. This means you should assign values to your variables at the top of your script.
. *Script setup:* EarSketch adds some code to a new script automatically, but you might accidentally delete `from earsketch import *`.
. *Comments:* Improper commenting will cause a syntax error. Remember that Python comments must start with a `#` symbol.
. *Colons:* Colons are used to declare the start of an indented block in Python. Check that your function definitions, for-loops, and conditional statements end with a colon `:`.
. *Assignment and equality:* The assignment operator (`=`) and equality operator (`==`) perform very different tasks. They cannot be used interchangeably, so ensure you are using the correct operator. We will learn more about the equality operator in <<console-input-and-conditionals#booleans,Chapter 17>>.
. *Indentation:* Indentation is critical in Python. Lack of indentation in function, for-loop, and conditional statement (see <<console-input-and-conditionals#conditionalstatements,Chapter 17>>) bodies will cause an <<every-error-explained-in-detail#indentationerror,indentation error>>.
. *Quotations:* Forgetting an opening or closing quatation mark can also cause a <<every-error-explained-in-detail#syntaxerror,syntax error>>. Make sure you enclose strings by quotation marks on both ends.
. *Function definitions vs. calls:* A custom function must be defined before it is called. Check that your function definitions precede any function calls. Likewise, check any empty function definitions. These will cause a <<every-error-explained-in-detail#parseerror,parse error>> if not deleted.
. *Parameter vs. argument:* Parameters are used in function definitions. Arguments are the information that is passed to the function, taking the place of the parameters. In other words, the argument is the actual value that is passed into the function.
. *Indices:* Providing incorrect indices can lead to confusing logic errors. Likewise, providing indices that are out of range can lead to <<every-error-explained-in-detail#indexerror,index errors>> and <<every-error-explained-in-detail#valueerror,value errors>>. Remember that all string indices (and later, data structure indices) start at 0.
. *Arguments:* Mistakes with function arguments can lead to all kinds of errors. You must provide the correct number and type of arguments to a function call. Make sure the arguments you pass are spelled correctly as well.
. *Punctuation:* Extra or lacking punctuation can lead to <<every-error-explained-in-detail#parseerror,parse errors>> and <<every-error-explained-in-detail#syntaxerror,syntax errors>>. Check the console and Code Editor for help.

[role="curriculum-javascript"]
. *Misspelling:* Spelling mistakes are the most prevalent error across programming languages. When using variables, make sure to use the same name you gave at assignment. Likewise, check the spelling of your functions, arguments, and sound constants.
. *Case sensitivity:* Most constructs used in programming are case sensitive, meaning you must pay attention to lowercase and uppercase letters used in variable names, functions, arguments, and sound constants.
. *Parentheses:* Forgetting an opening or closing parentheses where needed will cause a syntax error. Make sure your arguments are enclosed by parentheses on both ends when defining and calling functions.
. *Initializing variables*: A variable must be initialized before it can be used in a script. This means you should assign values to your variables at the top of your script.
. *Initializing without var:* Forgetting to initialize a variable with `var` in JavaScript can cause some confusing errors. Remember, the correct way to initialize a variable looks like this: `var measure = 1`.
. *Comments:* Improper commenting will cause a syntax error. Remember that JavaScript comments must start with `//`.
. *Semicolons:* Including semicolons after every statement is highly recommended in JavaScript. JavaScript may interpret your code differently in their absence, leading to confusing logic errors. The EarSketch Code Editor will alert you if you are missing a semicolon.
. *Assignment and equality:* The assignment operator (`=`), the equality operator (`==`), and the strict equality operator (`===`) perform very different tasks. They cannot be used interchangeably, so ensure you are using the correct operator. We will learn more about the equality operators in <<console-input-and-conditionals#booleans,Chapter 17>>.
. *Quotations:* Forgetting an opening or closing quatation mark can also cause a <<every-error-explained-in-detail#syntaxerror,syntax error>>. Make sure you enclose strings by quotation marks on both ends.
. *Curly braces:* Code bodies beneath function definitions, for-loops and conditional statements must be enclosed by curly braces. This can be tricky to catch, so make of habit of using curly braces when programming in JavaScript.
. *Function definitions vs. calls:* A custom function must be defined before it is called. Check that your function definitions precede any function calls.
. *Parameter vs. argument:* Parameters are used in function definitions. Arguments are the information that is passed to the function, taking the place of the parameters. In other words, the argument is the actual value that is passed into the function.
. *Indices:* Providing incorrect indices can lead to confusing logic errors. Likewise, providing indices that are out of range can lead to <<every-error-explained-in-detail#indexerror,index errors>> and <<every-error-explained-in-detail#valueerror,value errors>>. Remember that all string indices (and later, data structure indices) start at 0.
. *Arguments:* Mistakes with function arguments can lead to all kinds of errors. You must provide the correct number and type of arguments to a function call. Make sure the arguments you pass are spelled correctly as well.
. *Punctuation:* Extra or lacking punctuation can lead to <<every-error-explained-in-detail#syntaxerror,syntax errors>>. Check the console and Code Editor for help.

[[moredebuggingexercises]]
=== More Debugging Exercises

The following exercises expand on the knowledge of common errors and how they can be handled in code.

Suppose we want to create an alternating drum beat, with each beat switching off every two measures. In the example below we set up a for-loop to place sound clips on alternating tracks. Try running the script. Do you notice anything strange?

[role="curriculum-python"]
[source,python]
----
# Overlap Logic: Code that causes an Overlapping Clips Warning

from earsketch import *
setTempo(120)

groove1 = HIPHOP_DUSTYGROOVE_011
groove2 = HIPHOP_DUSTYGROOVE_010

for measure in range(1, 9):
    fitMedia(groove1, 1, measure, measure + 2)
    fitMedia(groove2, 2, measure + 2, measure + 4)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Overlap Logic: Code that causes an Overlapping Clips Warning

setTempo(120);

var groove1 = HIPHOP_DUSTYGROOVE_011;
var groove2 = HIPHOP_DUSTYGROOVE_010;

for (var measure = 1; measure < 9; measure++) {
    fitMedia(groove1, 1, measure, measure + 2);
    fitMedia(groove2, 2, measure + 2, measure + 4);
}
----

[role="curriculum-python"]
We end up placing a clip on every measure as we iterate through the for-loop, but each clip is two measures long. This causes the second half (right side) of each clip to overlap with the previous half. Our code ran, but this was not the intended result; we have encountered a logic error. Following the control flow of the for-loop helps to debug this script. When `measure` is equal to 2, the `fitMedia()` calls attempt to place clips on measures that already contain music. We can solve this issue by incrementing our loop counter by four on each iteration instead of one. That way, we jump ahead four measures before placing clips again. In Python, this can be achieved using the `range()` function's third argument, like `range(1, 9, 4)`. The following code corrects the logic error:

[role="curriculum-javascript"]
We end up placing a clip on every measure as we iterate through the for-loop, but each clip is two measures long. This causes the second half (right side) of each clip to overlap with the previous half. Our code ran, but this was not the intended result; we have encountered a logic error. Following the control flow of the for-loop helps to debug this script. When `measure` is equal to 2, the `fitMedia()` calls attempt to place clips on measures that already contain music. We can solve this issue by incrementing our iteration statement by four on each iteration instead of one, like `measure += 4`. That way, we jump ahead four measures before placing clips again. The following code corrects the logic error:

[role="curriculum-python"]
[source,python]
----
# Overlap Correction: Errors fixed

from earsketch import *
setTempo(120)

groove1 = HIPHOP_DUSTYGROOVE_011
groove2 = HIPHOP_DUSTYGROOVE_010

for measure in range(1, 9, 4):
    fitMedia(groove1, 1, measure, measure + 2)
    fitMedia(groove2, 2, measure + 2, measure + 4)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Overlap Correction: Errors fixed

setTempo(120);

var groove1 = HIPHOP_DUSTYGROOVE_011;
var groove2 = HIPHOP_DUSTYGROOVE_010;

for (var measure = 1; measure < 9; measure += 4) {
    fitMedia(groove1, 1, measure, measure + 2);
    fitMedia(groove2, 2, measure + 2, measure + 4);
}
----

Let's take a look at another example. The script below takes advantage of all of `setEffect()` 's parameters to spice up a transition with an envelope. As the drop approaches, we attempt to slowly filter out the clap sounds for a more dramatic effect. Even though everything appears to be correct, the code doesn't run. See if you can use the console to figure out what is wrong.

[role="curriculum-python"]
[source,python]
----
# Argument Order: Error caused by argument order using 7-parameter setEffect()

from earsketch import *
setTempo(128)

lead = YG_EDM_LEAD_BIG_1
kick = YG_EDM_KICK_1
riser = RD_EDM_SFX_RISER_AIR_1
bigClaps = YG_EDM_CLAPS_1

fitMedia(bigClaps, 1, 1, 5)
fitMedia(riser, 2, 1, 5)

fitMedia(kick, 3, 5, 9)
fitMedia(lead, 4, 5, 9)

setEffect(2, VOLUME, GAIN, -10)
setEffect(1, FILTER, FILTER_FREQ, 1, 10000, 5, 100)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Argument Order: Error caused by argument order using 7-parameter setEffect()

setTempo(128);

var lead = YG_EDM_LEAD_BIG_1;
var kick = YG_EDM_KICK_1;
var riser = RD_EDM_SFX_RISER_AIR_1;
var bigClaps = YG_EDM_CLAPS_1;

fitMedia(bigClaps, 1, 1, 5);
fitMedia(riser, 2, 1, 5);

fitMedia(kick, 3, 5, 9);
fitMedia(lead, 4, 5, 9);

setEffect(2, VOLUME, GAIN, -10);
setEffect(1, FILTER, FILTER_FREQ, 1, 10000, 5, 100);
----

[role="curriculum-python"]
The console points us to line 27, where we have called `setEffect()` with a FILTER envelope that should drop in frequency from measure one to five. The console also tells us that we provided an argument with a value that is out of range, a <<every-error-explained-in-detail#valueerror,value error>>. Finally, it states that our start measure for the envelope can't be greater than the end measure. This is key - we must have mixed up our arguments. Upon further inspection, we can see that we provided time-value pairs for our envelope instead of value-time pairs. Our last four arguments should instead be (10000, 1, 100, 5):

[role="curriculum-javascript"]
The console points us to line 25, where we have called `setEffect()` with a FILTER envelope that should drop in frequency from measure one to five. The console also tells us that we provided an argument with a value that is out of range, a <<every-error-explained-in-detail#valueerror,range error>>. Finally, it states that our start measure for the envelope can't be greater than the end measure. This is key - we must have mixed up our arguments. Upon further inspection, we can see that we provided time-value pairs for our envelope instead of value-time pairs. Our last four arguments should instead be (10000, 1, 100, 5):

[role="curriculum-python"]
[source,python]
----
# Argument Order Correction: Errors fixed

from earsketch import *
setTempo(128)

lead = YG_EDM_LEAD_BIG_1
kick = YG_EDM_KICK_1
riser = RD_EDM_SFX_RISER_AIR_1
bigClaps = YG_EDM_CLAPS_1

fitMedia(bigClaps, 1, 1, 5)
fitMedia(riser, 2, 1, 5)

fitMedia(kick, 3, 5, 9)
fitMedia(lead, 4, 5, 9)

setEffect(2, VOLUME, GAIN, -10)
setEffect(1, FILTER, FILTER_FREQ, 10000, 1, 100, 5)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Argument Order Correction: Errors fixed

setTempo(128);

var lead = YG_EDM_LEAD_BIG_1;
var kick = YG_EDM_KICK_1;
var riser = RD_EDM_SFX_RISER_AIR_1;
var bigClaps = YG_EDM_CLAPS_1;

fitMedia(bigClaps, 1, 1, 5);
fitMedia(riser, 2, 1, 5);

fitMedia(kick, 3, 5, 9);
fitMedia(lead, 4, 5, 9);

setEffect(2, VOLUME, GAIN, -10);
setEffect(1, FILTER, FILTER_FREQ, 10000, 1, 100, 5);
----

EarSketch provides some additional resources to help you debug your scripts. Take a look at <<every-error-explained-in-detail#,Every Error Explained in Detail>> for a description of different error types and what you can do to prevent them.

////
Video Idea: A quick example of print debugging and commenting out. We discussed maybe using a for loop that trys to add a beat before the first measure of the piece.
////

[[chapter15summary]]
=== Chapter 15 Summary

[role="curriculum-python"]
* The `print` statement evaluates its accompanying expression and displays the result in the console. It is a useful tool for debugging because it allows the programmer to learn the state of the program.
* Printing, commenting out code, and the console can all be used to debug code. Additionally, asking someone for help can significantly speed up the debugging process.
* Revisit the expanded list of common programming errors: <<debugging-logic#commonerrors,Common Errors>>.

[role="curriculum-javascript"]
* The `println()` function evaluates its argument and displays the result in the console. It is a useful tool for debugging because it allows the programmer to learn the state of the program.
* Printing, commenting out code, and the console can all be used to debug code. Additionally, asking someone for help can significantly speed up the debugging process.
* Revisit the expanded list of common programming errors: <<debugging-logic#commonerrors,Common Errors>>.

[[chapter-questions]]
=== Questions

[question]
--
Which of the following is not a recommended technique for debugging?
[answers]
* Copying and pasting code into Google
* Printing variable values to the console
* Looking at error lines identified in the console
* Asking others for help
--

[question]
--
Which of the following is not something that can be printed to the console?
[answers]
* Code Comments
* Strings
* Mathematical Expressions
* Variables
--

