[[ch_29]]
== Every Error Explained in Detail
:nofooter:

[[importerror]]
=== Import Error

//Python only

[role="curriculum-python"]
*Console message:* ImportError: The appropriate packages cannot be found or imported.

[role="curriculum-python"]
*Description:* An import error occurs when a program fails to load the module given in a `from...import` statement, like `from module import *`. This could be due to a misspelling, or maybe the module to be imported does not exist.

[role="curriculum-python"]
*Example:* Although the snippet below shows the word "EarSketch" with its usual styling, Python modules are specified in all lowercase.

////
Can't turn off pasted without this appearing in JS mode.
////

[role="curriculum-python"]
[source,python]
----
from EarSketch import *
----

[role="curriculum-python"]
Instead, our statement should read:

[role="curriculum-python"]
[source,python]
----
from earsketch import *
----

[role="curriculum-python"]
*Solution:* Check your `from...import` statements at the top of your script for typos and letter case.

[role="curriculum-javascript"]
Import errors do not occur in JavaScript. Open a Python script for an explanation of this error type, or move on to <<every-error-explained-in-detail#indexerror,index errors>>.

[[indentationerror]]
=== Indentation Error

//Python only

[role="curriculum-python"]
*Console message:* IndentationError: There is an indentation error in the code (lack of or extra spaces).

[role="curriculum-python"]
*Description:* Recall that proper indentation is needed in Python when using loops, functions, and conditional statements - any statement that ends with a colon (`:`). An indentation error is thrown when an incorrect amount of indentation is used, either not enough or too much.

[role="curriculum-python"]
*Example:* The EarSketch Code Editor automatically indents lines of code following a colon, but the programmer may accidentally change indentation manually, perhaps when making changes to a body of code. In the snippet below, it is unclear which lines should fall within the loop, both to user and the interpreter.

////
Can't turn off pasting without this appearing in JS mode
////

[role="curriculum-python"]
[source,python]
----
for measure in range(1, 9, 2):
    fitMedia(melody, 1, measure, measure + 2)
    makeBeat(kick, 2, measure, beatString)
  makeBeat(kick, 2, measure + 1, beatString)
fitMedia(beat, 3, 3, 9)
----

[role="curriculum-python"]
A properly indented body should instead look like the snippet below. The for-loop body is indented by one tab and it is clear that the last `fitMedia()` call is outside the loop.

[role="curriculum-python"]
[source,python]
----
for measure in range(1, 9, 2):
    fitMedia(melody, 1, measure, measure + 2)
    makeBeat(kick, 2, measure, beatString)
    makeBeat(kick, 2, measure + 1, beatString)

fitMedia(beat, 3, 3, 9)
----

[role="curriculum-python"]
*Solution:* Try deleting all the spaces in front of the code in the body so each line is against the left edge of the code editor. Then, indent the body line by line, ensuring that all indentation is constant.

[role="curriculum-javascript"]
Indentation errors do not occur in JavaScript, though you should still use proper indentation for readability. Open a Python script for an explanation of this error type, or move on to <<every-error-explained-in-detail#indexerror,index errors>>.

[[indexerror]]
=== Index Error

[role="curriculum-python"]
*Console message:* IndexError: There is an error using an out of range index.

[role="curriculum-javascript"]
*Console message:* TypeError: There is an error using an out of range index.

[role="curriculum-python"]
*Description:* An index error is thrown when trying to access an index that is out of range or does not exist within a list or string.

[role="curriculum-javascript"]
*Description:* An index error is thrown when trying to access an index that is out of range or does not exist within an array or string. It is thrown as a type error in JavaScript. For an explanation of more general type errors, see the section on <<every-error-explained-in-detail#typeerror,type errors>>.

[role="curriculum-python"]
*Example:* In the following code, we attempt to create an additive structure using clips from a list.

[role="curriculum-javascript"]
*Example:* In the following code, we attempt to create an additive structure using clips from an array.

[role="curriculum-python"]
[source,python]
----
# Index Error: Example

from earsketch import *
setTempo(100)

orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2]

fitMedia(orch[1], 1, 1, 17)
fitMedia(orch[2], 2, 5, 17)
fitMedia(orch[3], 3, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Index Error: Example

setTempo(120);

var orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2];

fitMedia(orch[1], 1, 1, 17);
fitMedia(orch[2], 2, 5, 17);
fitMedia(orch[3], 3, 9, 17);
----

[role="curriculum-python"]
An Index Error is thrown and the console points us to line 19, stating the index is out of range. We have three sound clips, but we forgot that list indices start at 0, so the last index we should be accessing is index 2:

[role="curriculum-javascript"]
A Type Error is thrown and the console states that a different data type was expected on line 17. An out of range value was provided to the last `fitMedia()` call. We have three sound clips, but we forgot that array indices start at 0, so the last index we should be accessing is index 2:

[role="curriculum-python"]
[source,python]
----
# Index Error: Correction

from earsketch import *
setTempo(100)

orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2]

fitMedia(orch[0], 1, 1, 17)
fitMedia(orch[1], 2, 5, 17)
fitMedia(orch[2], 3, 9, 17)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Index Error: Correction

setTempo(100);

var orch = [Y18_STRINGS_2_3, HIPHOP_DUSTYGROOVE_002, Y41_STRINGS_2];

fitMedia(orch[0], 1, 1, 17);
fitMedia(orch[1], 2, 5, 17);
fitMedia(orch[2], 3, 9, 17);
----

[role="curriculum-python"]
*Solution:* Write down the name of each clip in your list and label each with its associated index, starting at 0. This helps you understand the structure of the list and what may be causing an index error.

[role="curriculum-javascript"]
*Solution:* Write down the name of each clip in your array and label each with its associated index, starting at 0. This helps you understand the structure of the array and what may be causing an index error.

[[nameerror]]
=== Name Error

[role="curriculum-python"]
*Console message:* NameError: There is an error with a variable or function name that is not defined.

[role="curriculum-javascript"]
*Console message:* Reference Error: There is an error with a variable or function name that is not defined.

[role="curriculum-python"]
*Description:* A name error occurs when a program tries to use a variable or call a function that was never defined, most often due to a typo.

[role="curriculum-javascript"]
*Description:* A name error occurs when a program tries to use a variable or call a function that was never defined, most often due to a typo. JavaScript specifically refers to this type of error as a reference error.

[role="curriculum-python"]
*Example:* Below is a simple script to print the string assigned to the `today` variable. However, a mistake with the print statement prevents the script from running.

[role="curriculum-javascript"]
*Example:* Below is a simple script to print the string assigned to the `today` variable. However, a mistake within the `println()` function prevents the script from running.


[role="curriculum-python"]
[source,python]
----
# Name Error: Example

from earsketch import *
setTempo(120)

today = readInput("What day is it?")
print("Today is " + Today)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Reference Error: Example

setTempo(120);

var today = readInput("What day is it?");
println("Today is " + Today);
----

In this case, the variable containing the string to be concatenated was not referred to by the correct name; a lowercase "t" should have been used.

[role="curriculum-python"]
[source,python]
----
# Name Error: Correction

from earsketch import *
setTempo(120)

today = readInput("What day is it?")
print("Today is " + today)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Reference Error: Correction

setTempo(120);

var today = readInput("What day is it?");
println("Today is " + today);
----

*Solution:* Check the spelling and case of your variables and functions. When using a variable or calling a function, make sure each has been defined previously. Make sure you define a function before it is called. Although you can paste the names in directly, ensure your sound constant names align with the clip names in the Sound Browser.

[[parseerror]]
=== Parse Error

[role="curriculum-python"]
*Console message:* ParseError: There is an error when reading the code.

[role="curriculum-python"]
*Description:* *Parsing* means converting one form of information into another. Therefore, a parse error occurs when the interpreter is unable to convert your code into information that the computer can use to make music. Code formatting, like brackets and parentheses, is often the cause of a parse error.

[role="curriculum-python"]
*Example:* In the following example, we attempt to have some fun by selecting random beats to play over a melody, but something is preventing the code from running.

[role="curriculum-python"]
[source,python]
----
# Parse Error: Example

from earsketch import *
setTempo(98)

soundFolder = HIP_HOP_98_BPM__HHDUSTYGROOVE

chords1 = RD_WORLD_PERCUSSION_PAN_FLUTE_1
chords2 = RD_WORLD_PERCUSSION_PAN_FLUTE_2

fitMedia(chords1, 1, 1, 9)
fitMedia(chords2, 1, 9, 17)

for measure in range(1, 17, 2):
  # select a random clip with EarSketch API function
  beat = selectRandomFile(soundFolder
  fitMedia(beat, 2, measure, measure + 2)
----

////
The parse error included in the example above breaks AsciiDoc syntax highlighting here for some reason. Same happens in Ch. 3. If removed while editing, the closing parentheses of selectRandomFile() should be omitted.
////

[role="curriculum-python"]
Upon running the code, the console points us to line 26. This line looks fine, but the `selectRandomFile()` function in the previous line is missing its closing parentheses. In many cases, parse errors can be fixed quickly.

[role="curriculum-python"]
[source,python]
----
# Parse Error: Correction

from earsketch import *
setTempo(98)

soundFolder = HIP_HOP_98_BPM__HHDUSTYGROOVE

chords1 = RD_WORLD_PERCUSSION_PAN_FLUTE_1
chords2 = RD_WORLD_PERCUSSION_PAN_FLUTE_2

fitMedia(chords1, 1, 1, 9)
fitMedia(chords2, 1, 9, 17)

for measure in range(1, 17, 2):
    # select a random clip with EarSketch API function
    beat = selectRandomFile(soundFolder)
    fitMedia(beat, 2, measure, measure + 2)
----

[role="curriculum-python"]
*Solution:* Check the console for an indication of where the offending line may be. Make sure all function definitions, function calls, and other expressions have opening and closing parentheses. Check for missing or extra punctuation marks in  other areas of your script. Additionally, check for missing function definitions and arguments. Finally, check spelling of the arguments you pass to functions.

[role="curriculum-javascript"]
Parse errors are interpreted broadly as syntax errors in JavaScript, which is covered <<every-error-explained-in-detail#syntaxerror,next>>.

[[syntaxerror]]
=== Syntax Error

*Console message:* SyntaxError: There is an error with the syntax (or arrangement) of code.

*Description:* A syntax error occurs when a program encounters a mistake in the script's syntax, the rules of a particular language.

*Example:* The following script is supposed to create dynamically changing futuristic bleeps. However it contains two common bugs that cause syntax errors.

[role="curriculum-python"]
[source,python]
----
# Syntax Error: Example

from earsketch import *
setTempo(120)

clap = RD_TRAP_ARCADEFIRESFX_1
beatString = "00+-0-00+0+-0+++"

for measure in range(1, 32):
    if measure % 4 = 0
        # Use EarSketch API function to shuffle beat string
        beatString = shuffleString(beatString)
    makeBeat(clap, 1, measure, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Syntax Error: Example

setTempo(120);

var clap = RD_TRAP_ARCADEFIRESFX_1;
var beatString = "00+-0-00+0+-0+++";

for (var measure = 1; measure < 32; measure++){
    if (measure % 4 = 0)
        // Use EarSketch API function to shuffle beat string
        beatString = shuffleString(beatString);
    }
    makeBeat(clap, 1, measure, beatString);
}
----

[role="curriculum-python"]
For this script, the code editor flags the offending line for us. Notice that we forgot to end our _if_ statement with a colon. On the same line, we also gave an invalid condition; we should be using the equality operator `==` instead of the assignment operator `=`.

[role="curriculum-javascript"]
For this script, the code editor flags the offending line for us. Notice that we forgot to open our _if_ statement body with a curly brace. On the same line, we also gave an invalid condition; we should be using the strict equality operator `===` instead of the assignment operator `=`.

[role="curriculum-python"]
[source,python]
----
# Syntax Error: Correction

from earsketch import *
setTempo(120)

clap = RD_TRAP_ARCADEFIRESFX_1
beatString = "00+-0-00+0+-0+++"

for measure in range(1, 32):
    if measure % 4 == 0:
        # Use EarSketch API function to shuffle beat string
        beatString = shuffleString(beatString)
    makeBeat(clap, 1, measure, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Syntax Error: Correction

setTempo(120);

var clap = RD_TRAP_ARCADEFIRESFX_1;
var beatString = "00+-0-00+0+-0+++";

for (var measure = 1; measure < 32; measure++) {
    if (measure % 4 === 0) {
    // Use EarSketch API function to shuffle beat string
        beatString = shuffleString(beatString);
    }
    makeBeat(clap, 1, measure, beatString);
}
----

[role="curriculum-python"]
*Solution:* Always check the console and code editor for clues. Beyond the common errors given above, check for opening and closing quotations and make sure you are not using Python keywords as variable names.

////
Added solution from parse error to JS version below.
////

[role="curriculum-javascript"]
*Solution:* Always check the console and code editor for clues.
Beyond the common errors given above, check for opening and closing quotations and ensure all function definitions, function calls, and other expressions have opening and closing parentheses. Also, check for missing or extra punctuation marks in other areas of your script. Additionally, check for missing function definitions and arguments. You cannot use JavaScript reserved words as variable names. Finally, check spelling of the arguments you pass to functions.

[[typeerror]]
=== Type Error

*Console message:* TypeError: There is an error with the expected data type.

*Description:* A type error occurs when a particular operation or function is expecting one data type, but receives another.

[role="curriculum-python"]
*Example:* Suppose you have written a script that keeps track of the total measures used with an updating variable. In the snippet below, we attempt to print a message stating the length of a song.

[role="curriculum-javascript"]
*Example:* Suppose you have written a script that takes user input to determine the length of the song. The user's value is passed to `fitMedia()`.

[role="curriculum-python"]
[source,python]
----
# Type Error: Example

from earsketch import *
setTempo(120)

soundClip = DUBSTEP_DRUMLOOP_MAIN_006
beatString = "0+000+++0--0-0--"
measureTotal = 0

for measure in range(1, 9):
    makeBeat(soundClip, 1, measure, beatString)
    measureTotal += 1

print("Your beat is " + measureTotal + " measures long.")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Type Error: Example

setTempo(120);

var soundClip = DUBSTEP_DRUMLOOP_MAIN_006;
var measureTotal = readInput("How many measures?");

println(measureTotal);

fitMedia(soundClip, 1, 1, measureTotal + 1);
----

[role="curriculum-python"]
A type error is thrown because the number type cannot be concatenated into a string. Instead, we can use data type conversion to first convert the `measureTotal` value into a string:

[role="curriculum-javascript"]
A type error is thrown because we accidentally passed a string as the last `fitMedia()` argument. Instead, we can use data type conversion to first convert the `measureTotal` string into a number:

[role="curriculum-python"]
[source,python]
----
# Type Error: Correction

from earsketch import *
setTempo(120)

soundClips = DUBSTEP_DRUMLOOP_MAIN_006
beatString = "0+000+++0--0-0--"
measureTotal = 0

for measure in range(1, 9):
    makeBeat(soundClips, 1, measure, beatString)
    measureTotal += 1

print("Your beat is " + str(measureTotal) + " measures long.")
----

[role="curriculum-javascript"]
[source,javascript]
----
// Type Error: Correction

setTempo(120);

var soundClip = DUBSTEP_DRUMLOOP_MAIN_006;
var measureTotal = readInput("How many measures?");

println(measureTotal);

fitMedia(soundClip, 1, 1, Number(measureTotal) + 1);
----

*Solution:* The EarSketch console gives the offending data type and points to a specific line number. Check for consistent data types within arithmetic expressions, data structure operations, and function arguments. In addition, make sure your function calls have the correct number of arguments.

////
(ex. trying to concatenate something into string that isn't string, modifying a string value instead of concatenating something in, function call with too few arguments)
////

[[valueerror]]
=== Value Error

[role="curriculum-python"]
*Console message:* ValueError: A provided argument is not within the set or range of acceptable values for a function.

[role="curriculum-javascript"]
*Console message:* RangeError: A provided argument is not within the set or range of acceptable values for a function.

[role="curriculum-python"]
*Description:* A value error occurs when a function receives an argument of the correct type but inappropriate value.

[role="curriculum-javascript"]
*Description:* A value error occurs when a function receives an argument of the correct type but inappropriate value. JavaScript specifically refers to this type of error as a range error.

[role="curriculum-python"]
*Example:* The following snippet attempts to create an interesting beat by using `makeBeat()` with lists.

[role="curriculum-javascript"]
*Example:* The following snippet attempts to create an interesting beat by using `makeBeat()` with arrays.

[role="curriculum-python"]
[source,python]
----
# Value Error: Example

from earsketch import *
setTempo(120)

drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001]
beatString = "1+3+1+221+2+1+24"

makeBeat(drumKit, 1, 1, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Range Error: Example

setTempo(120);

var drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001];
var beatString = "1+3+1+221+2+1+24";

makeBeat(drumKit, 1, 1, beatString);
----

[role="curriculum-python"]
`makeBeat()` 's fourth argument is the appropriate type, but one of the index values it must access is invalid. In this scenario, it is likely that the programmer forgot that list indices start at zero.

[role="curriculum-javascript"]
`makeBeat()` 's fourth argument is the appropriate type, but one of the index values it must access is invalid. In this scenario, it is likely that the programmer forgot that array indices start at zero.

[role="curriculum-python"]
[source,python]
----
# Value error: Correction

from earsketch import *
setTempo(120)

drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001]
beatString = "0+2+0+110+1+0+13"

makeBeat(drumKit, 1, 1, beatString)
----

[role="curriculum-javascript"]
[source,javascript]
----
// Range error: Correction

setTempo(120);

var drumKit = [OS_KICK06, RD_UK_HOUSE_SOLODRUMPART_15, OS_COWBELL01, TECHNO_ACIDBASS_001];
var beatString = "0+2+0+110+1+0+13";

makeBeat(drumKit, 1, 1, beatString);
----

*Solution:* Check your beat strings to ensure values fall within the correct range. Also, confirm any arguments provided to `setEffect()` are within the effect's required range.
