---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  # To report GitHub Actions status checks
  statuses: write
  pull-requests: read
  checks: write

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      ################################
      # Run Linter against code base #
      ################################
      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v6.4.1
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CPP: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          JSCPD_CONFIG_FILE: .jscpd.json
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          VALIDATE_JSX: false
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          FILTER_REGEX_EXCLUDE: (.*fonts/icomoon_ultimate/.*|.*lib/.*|.*tests/karma/.*.results.js|.*tests/cypress/fixtures/.*|.*node_modules/.*)

      - name: Run ESLint
        run: npm run lint:report
        continue-on-error: true

      - name: Annotate PR with Lint Results
        uses: ataylorme/eslint-annotate-action@3.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
